### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 531 "Sea Life Center Königswinter":
	Status from: available to: retired
	Title from: Sea Life Center KÃ¶nigswinter to: Sea Life Center Königswinter

### CODE REVIEW

**Comment by NinaWie** [comment]
New machine 7508 named Granby Grand Mountain Trading Co submitted.

**Comment by jannisborn** [comment]
2024-09-03 22:30:03 INFO ======Location differ joblog from 2024-09-03 22:30:03=======
2024-09-03 22:39:26 INFO 64/70: Found machine to be added: Great Wplf Lodge
2024-09-03 22:39:29 INFO Location Maryland (7/125): Changes in 1/70 machines found.
2024-09-03 22:42:40 INFO Horseshoe Curve National Historic Landmark is currently unavailable
2024-09-03 22:44:44 INFO 192/218: Found machine to be added: Great Wolf Lodge Poconos
2024-09-03 22:44:57 INFO Location Pennsylvania (11/125): Changes in 2/218 machines found.
2024-09-03 22:49:33 INFO 492/763: Found machine to be added: The Mart (Antique Mall)
2024-09-03 22:50:48 INFO 693/763: Found machine to be added: Strathern Historical Park
2024-09-03 22:51:33 INFO Location California (12/125): Changes in 2/763 machines found.
2024-09-03 22:57:15 INFO SeaQuest Roseville Aquarium & Petting Zoo  is currently unavailable
2024-09-03 22:57:37 INFO Location Minnesota (16/125): Changes in 1/107 machines found.
2024-09-03 23:07:36 INFO 215/389: Found machine to be added: Great Wolf Lodge Water Park - Southwest Florida
2024-09-03 23:09:17 INFO Location Florida (24/125): Changes in 1/389 machines found.
2024-09-03 23:13:56 INFO Georgia Aquarium is available again
2024-09-03 23:15:11 INFO Location Georgia (27/125): Changes in 1/130 machines found.
2024-09-03 23:15:53 INFO 8/102: Found machine to be added: Old Bryce Town Ice Cream and Candy Shop
2024-09-03 23:17:02 INFO Location Utah (29/125): Changes in 1/102 machines found.
2024-09-03 23:17:20 INFO Scoop of Paradise is currently unavailable
2024-09-03 23:17:38 INFO Location Hawaii (30/125): Changes in 1/96 machines found.
2024-09-03 23:35:00 INFO 28/64: Found machine to be added: Barrel House Distilling Co.
2024-09-03 23:35:21 INFO Location Kentucky (48/125): Changes in 1/64 machines found.
2024-09-04 00:14:18 INFO 
 Result: 11 changes, 8 new machines found and 3 machines retired
2024-09-04 00:31:53 ERROR Found 3 problems that require manual intervention
2024-09-04 00:31:53 INFO ======Location differ completed at 2024-09-04 00:31:53=======
2024-09-04 00:31:54 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-09-04 22:30:01 INFO ======Location differ joblog from 2024-09-04 22:30:01=======
2024-09-04 22:45:40 INFO Idlewild and Soak Zone is available again
2024-09-04 22:46:57 INFO Location Pennsylvania (11/125): Changes in 1/218 machines found.
2024-09-04 22:53:55 INFO Rocket Fizz is currently unavailable
2024-09-04 22:56:21 INFO Location Michigan (13/125): Changes in 1/194 machines found.
2024-09-04 23:17:07 INFO 125/131: Found machine to be added: Wave Surf Shop (second location)
2024-09-04 23:17:12 INFO Location Georgia (27/125): Changes in 1/131 machines found.
2024-09-04 23:20:50 INFO Rio Suite Hotel & Casino - Paradise Island Wear is currently unavailable
2024-09-04 23:21:17 INFO Location Nevada (31/125): Changes in 1/207 machines found.
2024-09-05 00:10:03 INFO 9/14: Found machine to be added: ASTRA Museum
2024-09-05 00:10:06 INFO Location Romania (104/125): Changes in 1/14 machines found.
2024-09-05 00:17:31 INFO 
 Result: 5 changes, 3 new machines found and 2 machines retired
2024-09-05 00:34:44 ERROR Found 3 problems that require manual intervention
2024-09-05 00:34:44 INFO ======Location differ completed at 2024-09-05 00:34:44=======
2024-09-05 00:34:45 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-09-05 22:30:01 INFO ======Location differ joblog from 2024-09-05 22:30:01=======
2024-09-05 23:53:32 INFO 42/150: Found machine to be added: Kings Landing
2024-09-05 23:54:31 INFO Location Canada (61/125): Changes in 1/150 machines found.
2024-09-05 23:59:32 INFO 389/445: Found machine to be added: Brooklands Museum
2024-09-06 00:00:03 INFO Location England (69/125): Changes in 1/445 machines found.
2024-09-06 00:08:30 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=257451': HTTPConnectionPool(host='209.221.138.252', port=80): Max retries exceeded with url: /Details.aspx?location=257451 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc6574ac880>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-09-06 00:08:40 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=256776': HTTPConnectionPool(host='209.221.138.252', port=80): Max retries exceeded with url: /Details.aspx?location=256776 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc66c58efa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-09-06 00:28:28 INFO 
 Result: 2 changes, 2 new machines found and 0 machines retired
2024-09-06 00:45:28 ERROR Found 3 problems that require manual intervention
2024-09-06 00:45:28 INFO ======Location differ completed at 2024-09-06 00:45:28=======
2024-09-06 00:45:29 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-09-06 22:30:02 INFO ======Location differ joblog from 2024-09-06 22:30:02=======
2024-09-06 23:09:14 INFO Powder House Ski & Snowboard Main Store is available again
2024-09-06 23:09:58 INFO Location California (12/125): Changes in 1/764 machines found.
2024-09-06 23:14:26 INFO George Orthodontics is available again
2024-09-06 23:17:14 INFO Location Colorado (15/125): Changes in 1/220 machines found.
2024-09-06 23:36:38 INFO Dairy Palace is available again
2024-09-06 23:40:57 INFO Location Texas (26/125): Changes in 1/308 machines found.
2024-09-06 23:43:04 INFO 9/34: Found machine to be added: Nebraska State Fair 
2024-09-06 23:43:27 INFO Location Nebraska (28/125): Changes in 1/34 machines found.
2024-09-07 00:17:09 INFO 99/447: Found machine to be added: Nothe Fort
2024-09-07 00:17:36 INFO 130/447: Found machine to be added: Hovercraft Museum
2024-09-07 00:21:21 INFO Location England (69/125): Changes in 2/447 machines found.
2024-09-07 00:33:20 INFO Seems that machine Ristorante Nuovo Edelweiss already exists as: Ristorante Bar Nuovo Edelweiss
2024-09-07 00:49:58 INFO 
 Result: 6 changes, 6 new machines found and 0 machines retired
2024-09-07 01:05:06 ERROR Our machine Stuh Museum Gift Shop in Nebraska from Server shown as available but http://209.221.138.252/Details.aspx?location=398575 responds Internal Server Error (500)
2024-09-07 01:06:49 ERROR Found 3 problems that require manual intervention
2024-09-07 01:06:49 INFO ======Location differ completed at 2024-09-07 01:06:49=======
2024-09-07 01:06:50 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-09-07 22:30:01 INFO ======Location differ joblog from 2024-09-07 22:30:01=======
2024-09-07 22:48:15 INFO 210/219: Found machine to be added: Penn State All Sports Museum
2024-09-07 22:48:19 INFO Location Pennsylvania (11/125): Changes in 1/219 machines found.
2024-09-08 00:23:22 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-09-08 00:40:14 ERROR Found 3 problems that require manual intervention
2024-09-08 00:40:14 INFO ======Location differ completed at 2024-09-08 00:40:14=======
2024-09-08 00:40:15 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7524 named The Garst Museum submitted.

**Comment by jannisborn** [comment]
2024-09-08 22:30:01 INFO ======Location differ joblog from 2024-09-08 22:30:01=======
2024-09-08 22:34:35 INFO Maine Souvenir shop  is available again
2024-09-08 22:34:41 INFO Location Maine (4/125): Changes in 1/30 machines found.
2024-09-08 22:53:24 INFO Colorado Welcome Center at Alamosa is available again
2024-09-08 22:55:36 INFO Location Colorado (15/125): Changes in 1/220 machines found.
2024-09-09 00:11:49 INFO 
 Result: 2 changes, 2 new machines found and 0 machines retired
2024-09-09 00:28:22 ERROR Found 3 problems that require manual intervention
2024-09-09 00:28:22 INFO ======Location differ completed at 2024-09-09 00:28:22=======
2024-09-09 00:28:23 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7525 named Mystery Town submitted.

**Comment by jannisborn** [comment]
2024-09-09 22:30:02 INFO ======Location differ joblog from 2024-09-09 22:30:02=======
2024-09-09 22:58:47 INFO 30/181: Found machine to be added: Made In The USA Store
2024-09-09 23:00:19 INFO Location Missouri (22/125): Changes in 1/181 machines found.
2024-09-09 23:02:27 INFO 184/202: Found machine to be added: Buc-ee's
2024-09-09 23:02:36 INFO Location Tennessee (23/125): Changes in 1/202 machines found.
2024-09-10 00:08:29 INFO 
 Result: 2 changes, 2 new machines found and 0 machines retired
2024-09-10 00:25:03 ERROR Found 3 problems that require manual intervention
2024-09-10 00:25:03 INFO ======Location differ completed at 2024-09-10 00:25:03=======
2024-09-10 00:25:04 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
No website updates today!

**Review by jannisborn — APPROVED** [review]

**Comment by jannisborn** [comment]
2024-09-11 22:30:02 INFO ======Location differ joblog from 2024-09-11 22:30:02=======
2024-09-11 23:22:37 INFO 2/133: Found machine to be added: Mount Rainier National Park - Paradise Inn Gift Shop
2024-09-11 23:24:02 INFO Location Washington (38/125): Changes in 1/133 machines found.
2024-09-12 00:11:09 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-09-12 00:27:37 ERROR Found 3 problems that require manual intervention
2024-09-12 00:27:37 INFO ======Location differ completed at 2024-09-12 00:27:37=======
2024-09-12 00:27:38 INFO Detected change in server_locations.json - push to github

**Pull request merged**
