### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by jannisborn**
2024-04-27 22:30:02 INFO ======Location differ joblog from 2024-04-27 22:30:02=======
2024-04-27 23:15:36 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-04-27 23:56:12 INFO Bataviawerf is available again
2024-04-27 23:56:13 INFO Keukenhof Tulip Gardens is available again
2024-04-27 23:56:27 INFO Slot Loevestein is available again
2024-04-27 23:57:02 INFO Location Netherlands (94/125): Changes in 3/143 machines found.
2024-04-27 23:57:20 INFO Interislander Ferries Aratere, Arahura, and Kaiitaki is available again
2024-04-27 23:57:20 INFO Location New Zealand (95/125): Changes in 1/34 machines found.
2024-04-28 00:02:29 INFO 96/172: Found machine to be added: Souvenirs & Carcasa
2024-04-28 00:03:31 INFO Location Spain (112/125): Changes in 1/172 machines found.
2024-04-28 00:05:51 INFO 
 Result: 5 changes, 5 new machines found and 0 machines retired
2024-04-28 00:07:49 ERROR Our machine Unknown???? in Netherlands from Device shown as available but http://209.221.138.252/Details.aspx?location=101237 responds Internal Server Error (500)
2024-04-28 00:17:27 ERROR Our machine Sint Jacobsstraat  in Netherlands from Device shown as retired but http://209.221.138.252/Details.aspx?location=298064 responds Internal Server Error (500)
2024-04-28 00:17:28 ERROR Our machine Oldehoven in Netherlands from Device shown as retired but http://209.221.138.252/Details.aspx?location=295084 responds Internal Server Error (500)
2024-04-28 00:20:21 ERROR Found 4 problems that require manual intervention
2024-04-28 00:20:21 INFO ======Location differ completed at 2024-04-28 00:20:21=======
2024-04-28 00:20:22 INFO Detected change in server_locations.json - push to github

### CODE REVIEW

**Comment by jannisborn** [comment]
No website updates today!

**Comment by NinaWie** [comment]
New machine 7152 named World Famous Coffee Cup Café submitted.

**Comment by jannisborn** [comment]
2024-04-29 22:30:02 INFO ======Location differ joblog from 2024-04-29 22:30:02=======
2024-04-29 22:50:16 INFO Frankenmuth Cheese Haus is available again
2024-04-29 22:50:18 INFO Michigan Shoppe is available again
2024-04-29 22:51:49 INFO Location Michigan (13/125): Changes in 2/190 machines found.
2024-04-29 22:57:57 INFO 83/85: Found machine to be added: Yankton Mall - Located (???)
2024-04-29 22:57:59 INFO 84/85: Found machine to be added: Yankton Mall, - near the movie theater
2024-04-29 22:57:59 INFO Location South Dakota (20/125): Changes in 2/85 machines found.
2024-04-29 23:00:12 INFO 8/198: Found machine to be added: Chattanooga Lookouts AT&T Field
2024-04-29 23:02:12 INFO Location Tennessee (23/125): Changes in 1/198 machines found.
2024-04-29 23:15:32 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-04-29 23:33:32 INFO Distance match - Seeems that machine Belogradchik Fortress  at ul. "Colo Todorov", 3900 Belogradchik, Bulgaria, Belogradchik already exists as: Belogradchik Rocks
2024-04-29 23:38:18 INFO Paddington Bear Store is currently unavailable
2024-04-29 23:39:10 INFO Fusiliers Museum of Northumberland is available again
2024-04-29 23:40:14 INFO Location England (69/125): Changes in 2/436 machines found.
2024-04-30 00:05:42 INFO 
 Result: 7 changes, 6 new machines found and 1 machines retired
2024-04-30 00:20:08 ERROR Found 4 problems that require manual intervention
2024-04-30 00:20:08 INFO ======Location differ completed at 2024-04-30 00:20:08=======
2024-04-30 00:20:09 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7156 named West Virginia Rest Area 69 submitted.

**Comment by jannisborn** [comment]
2024-05-01 22:40:02 INFO ======Location differ joblog from 2024-05-01 22:40:02=======
2024-05-01 22:48:27 INFO 19/130: Found machine to be added: Hip-Nautic Gifts
2024-05-01 22:49:35 INFO Location Oregon (8/125): Changes in 1/130 machines found.
2024-05-01 23:21:23 INFO 4/97: Found machine to be added: Hovenweep National Monument
2024-05-01 23:21:29 INFO 13/97: Found machine to be added: Rubys Inn 
2024-05-01 23:22:24 INFO Location Utah (29/125): Changes in 2/97 machines found.
2024-05-01 23:24:49 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-05-01 23:42:43 INFO 8/11: Found machine to be added: Eesti Põllumajandusmuuseum
2024-05-01 23:42:45 INFO Location Bulgaria (60/125): Changes in 1/11 machines found.
2024-05-01 23:49:19 INFO 0/21: Found machine to be added: Elistvere Loomapark
2024-05-01 23:49:31 INFO Location Estonia (70/125): Changes in 1/21 machines found.
2024-05-02 00:08:09 INFO Turda Salt Mine is currently unavailable
2024-05-02 00:08:09 INFO Location Romania (104/125): Changes in 1/13 machines found.
2024-05-02 00:14:48 INFO 
 Result: 6 changes, 5 new machines found and 1 machines retired
2024-05-02 00:25:19 ERROR Our machine Fabryka Schindlera in Poland from Device shown as available but http://209.221.138.252/Details.aspx?location=291674 responds Internal Server Error (500)
2024-05-02 00:29:10 ERROR Found 4 problems that require manual intervention
2024-05-02 00:29:10 INFO ======Location differ completed at 2024-05-02 00:29:10=======
2024-05-02 00:29:10 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
No website updates today!

**Review by NinaWie — APPROVED** [review]

**Pull request merged**
