### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Request change to machine 3422 named Westgate Lakes Resort - Changed:
	Status from: available to: retired

### CODE REVIEW

**Comment by NinaWie** [comment]
Request change to machine 5655 named Les Catacombes de Paris (Paris Catacombs) - Changed:
	Status from: available to: out-of-order
	Address from 1 Avenue du Colonel Henri Rol-Tanguy, Paris - Ãle-De-France to: 1 Avenue du Colonel Henri Rol-Tanguy, Paris - Île-De-France

**Comment by jannisborn** [comment]
2024-02-01 22:30:02 INFO ======Location differ joblog from 2024-02-01 22:30:02=======
2024-02-01 22:51:22 INFO Indian River Trading Post / Shell Gas Station / McDonalds is available again
2024-02-01 22:51:48 INFO 118/189: Found machine to be added: Pharaohs Family Fun Center
2024-02-01 22:51:53 INFO 121/189: Found machine to be added: All Things Michigan In Westwood Mall
2024-02-01 22:52:41 INFO Location Michigan (13/125): Changes in 3/189 machines found.
2024-02-01 23:16:29 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-02-02 00:07:11 INFO 
 Result: 3 changes, 3 new machines found and 0 machines retired
2024-02-02 00:20:19 ERROR Found 5 problems that require manual intervention
2024-02-02 00:20:19 INFO ======Location differ completed at 2024-02-02 00:20:19=======
2024-02-02 00:20:20 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
Request change to machine 1926 named Georgetown Loop Railroad, Silver Plume Depot - Changed:
	Status from: available to: out-of-order

**Comment by NinaWie** [comment]
Request change to machine 6838 named 18605 Green Valley Ranch Blvd - Changed:
	Status from: available to: retired

**Comment by NinaWie** [comment]
Request change to machine 5959 named Conwy Castle - Changed:
Machine with pending changes is getting changed *AGAIN* @jannisborn @NinaWie:

**Comment by NinaWie** [comment]
Request change to machine 5959 named Conwy Castle - Changed:
Machine with pending changes is getting changed *AGAIN* @jannisborn @NinaWie:

**Comment by NinaWie** [comment]
Request change to machine 3285 named The Daytona International Speedway, The Daytona 500 Experience - Changed:
	Status from: available to: out-of-order

**Comment by NinaWie** [comment]
Request change to machine 3285 named The Daytona International Speedway, The Daytona 500 Experience - Changed:
Machine with pending changes is getting changed *AGAIN* @jannisborn @NinaWie:

**Comment by NinaWie** [comment]
Request change to machine 3285 named The Daytona International Speedway, The Daytona 500 Experience - Changed:
Machine with pending changes is getting changed *AGAIN* @jannisborn @NinaWie:

**Review by jannisborn — APPROVED** [review]

**Comment by jannisborn** [comment]
2024-02-02 22:30:02 INFO ======Location differ joblog from 2024-02-02 22:30:02=======
2024-02-02 23:15:27 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-02-02 23:21:29 INFO Conner Prairie Interactive History Park is currently unavailable
2024-02-02 23:22:09 INFO Location Indiana (39/125): Changes in 1/102 machines found.
2024-02-03 00:05:53 INFO 
 Result: 1 changes, 0 new machines found and 1 machines retired
2024-02-03 00:18:58 ERROR Found 5 problems that require manual intervention
2024-02-03 00:18:58 INFO ======Location differ completed at 2024-02-03 00:18:58=======
2024-02-03 00:18:59 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
Request change to machine 5097 named Great Wolf Lodge Great Mound - Changed:
	Status from: available to: out-of-order

**Comment by NinaWie** [comment]
Request change to machine 3422 named Westgate Lakes Resort - Changed:
	Status from: retired to: out-of-order

**Comment by NinaWie** [comment]
Request change to machine 3278 named Beach Express - Changed:

**Comment by NinaWie** [comment]
Request change to machine 6173 named Joe's Crab Shack - Changed:
	Status from: available to: out-of-order

**Comment by NinaWie** [comment]
Request change to machine 3284 named Ocean Walk 10 Movies (R/C Theaters) - Changed:

**Comment by NinaWie** [comment]
Request change to machine 3283 named Ocean Blue Beach Shop (Was Beach Bazaar) - Changed:
	Address from 203 N. Atlantic Ave (between Earl St & Oakridge Blvd), Daytona Beach to: 203 N. Atlantic Ave (between Earl St

**Comment by NinaWie** [comment]
Request change to machine 3280 named Buc-ee's - Changed:

**Comment by NinaWie** [comment]
Request change to machine 3283 named Ocean Blue Beach Shop (Was Beach Bazaar) - Changed:
Machine with pending changes is getting changed *AGAIN* @jannisborn @NinaWie:

**Comment by NinaWie** [comment]
Request change to machine 3283 named Ocean Blue Beach Shop (Was Beach Bazaar) - Changed:
Machine with pending changes is getting changed *AGAIN* @jannisborn @NinaWie:
	Address from 203 N. Atlantic Ave (between Earl St to: 203 N. Atlantic Ave (Earl St

**Pull request merged**
