### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 6931 "Rostock Stadtinformation":
	Status from: available to: retired

### CODE REVIEW

**Comment by NinaWie** [comment]
New machine 7683 named San Diego Zoo Machines submitted.

**Comment by jannisborn** [comment]
No website updates today!

**Comment by NinaWie** [comment]
New machine 7684 named Guatapé Piedra el Peñol submitted.

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
2024-12-24 22:30:02 INFO ======Location differ joblog from 2024-12-24 22:30:02=======
2024-12-24 23:20:56 INFO Virginia Air and Space Center  is available again
2024-12-24 23:26:44 INFO White Sands National Park, White Sands Trading Company Gift Shop is available again
2024-12-24 23:36:18 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-12-24 23:42:10 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-12-24 23:51:59 INFO 251/404: Found machine to be added: Magdeburg area shop in Germany
2024-12-24 23:58:15 INFO Ceramica Artistica is available again
2024-12-25 00:03:07 INFO Zoológico de Chapultepec  (in Mexico) is currently unavailable
2024-12-25 00:14:01 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-25 00:14:01 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-25 00:15:16 INFO 
 Result: 5 changes, 4 new machines found and 1 machines retired
2024-12-25 00:30:31 ERROR Found 9 problems that require manual intervention
2024-12-25 00:30:31 INFO ======Location differ completed at 2024-12-25 00:30:31=======
2024-12-25 00:30:32 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
No website updates today!

**Comment by NinaWie** [comment]
New machine 7686 named Stonehenge submitted.

**Comment by jannisborn** [comment]
2024-12-27 22:30:02 INFO ======Location differ joblog from 2024-12-27 22:30:02=======
2024-12-27 22:46:08 INFO 179/768: Found machine to be added: Highland Tattoo in California
2024-12-27 23:15:55 INFO Fort Zion Gift Shop & Petting Zoo (in Utah) is currently unavailable
2024-12-27 23:35:01 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-12-27 23:40:47 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-12-28 00:12:15 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-28 00:12:15 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-28 00:13:29 INFO 
 Result: 2 changes, 1 new machines found and 1 machines retired
2024-12-28 00:28:33 ERROR Our machine Big Bear Snow Play  in California from Server shown as available but http://209.221.138.252/Details.aspx?location=446970 responds Internal Server Error (500)
2024-12-28 00:28:33 ERROR Found 9 problems that require manual intervention
2024-12-28 00:28:33 INFO ======Location differ completed at 2024-12-28 00:28:33=======
2024-12-28 00:28:34 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-12-28 22:30:02 INFO ======Location differ joblog from 2024-12-28 22:30:02=======
2024-12-28 23:25:25 INFO 85/106: Found machine to be added: Uranus Fudge Factory in Indiana
2024-12-28 23:35:04 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-12-28 23:40:51 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-12-28 23:55:43 INFO Ferrigno Lucio S.a.s. is available again
2024-12-28 23:56:17 INFO Edicola il Messaggero (Newspaper kiosk) is available again
2024-12-28 23:59:09 INFO Henn na Hotel Tokyo Nishikasai (in Japan) is currently unavailable
2024-12-29 00:12:13 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-29 00:12:13 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-29 00:13:27 INFO 
 Result: 4 changes, 3 new machines found and 1 machines retired
2024-12-29 00:28:29 ERROR Found 9 problems that require manual intervention
2024-12-29 00:28:29 INFO ======Location differ completed at 2024-12-29 00:28:29=======
2024-12-29 00:28:29 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7689 named 2 Cube houses stay okay submitted.

**Comment by NinaWie** [comment]
New machine 7690 named Ss Rotterdam op het dek submitted.

**Comment by jannisborn** [comment]
2024-12-29 22:30:01 INFO ======Location differ joblog from 2024-12-29 22:30:01=======
2024-12-29 22:56:02 INFO 37/110: Found machine to be added: Bentlyville Gift Shop in Minnesota
2024-12-29 23:03:55 INFO Mine Your Own Gem Mine (formerly Three Bear Gifts) (in Tennessee) is currently unavailable
2024-12-29 23:35:16 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-12-29 23:41:04 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-12-30 00:12:26 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-30 00:12:27 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-30 00:13:41 INFO 
 Result: 2 changes, 1 new machines found and 1 machines retired
2024-12-30 00:28:46 ERROR Found 9 problems that require manual intervention
2024-12-30 00:28:46 INFO ======Location differ completed at 2024-12-30 00:28:46=======
2024-12-30 00:28:47 INFO Detected change in server_locations.json - push to github

**Pull request merged**
