### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 253 "Maritiem Museum Lennusadam":
	 Location from: 59.4514, 24.7384 to: 59.4425, 24.7494

### CODE REVIEW

**Comment by jannisborn** [comment]
2024-07-05 22:30:01 INFO ======Location differ joblog from 2024-07-05 22:30:01=======
2024-07-05 22:59:39 INFO Storybook Island is currently unavailable
2024-07-05 22:59:51 INFO Location South Dakota (20/125): Changes in 1/87 machines found.
2024-07-06 00:10:56 INFO 
 Result: 1 changes, 0 new machines found and 1 machines retired
2024-07-06 00:26:38 ERROR Found 3 problems that require manual intervention
2024-07-06 00:26:38 INFO ======Location differ completed at 2024-07-06 00:26:38=======
2024-07-06 00:26:39 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-07-06 22:30:02 INFO ======Location differ joblog from 2024-07-06 22:30:02=======
2024-07-06 23:36:11 INFO Manitoba Museum is currently unavailable
2024-07-06 23:37:11 INFO Location Canada (61/125): Changes in 1/147 machines found.
2024-07-06 23:42:41 INFO Maritiem Museum Lennusadam is currently unavailable
2024-07-06 23:42:43 INFO 6/22: Found machine to be added: Maritime Museum Tallinn
2024-07-06 23:42:54 INFO Location Estonia (70/125): Changes in 2/22 machines found.
2024-07-07 00:09:06 INFO 
 Result: 3 changes, 1 new machines found and 2 machines retired
2024-07-07 00:24:50 ERROR Found 3 problems that require manual intervention
2024-07-07 00:24:50 INFO ======Location differ completed at 2024-07-07 00:24:50=======
2024-07-07 00:24:51 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-07-07 22:30:02 INFO ======Location differ joblog from 2024-07-07 22:30:02=======
2024-07-07 22:44:21 INFO Pea Soup Andersen's Restaurant is currently unavailable
2024-07-07 22:44:25 INFO Cabazon Dinosaurs is available again
2024-07-07 22:45:47 INFO 233/757: Found machine to be added: Shoreline Village - Santa's Workshop
2024-07-07 22:46:57 INFO World Famous Tree House is currently unavailable
2024-07-07 22:49:47 INFO Location California (12/125): Changes in 4/757 machines found.
2024-07-07 22:50:10 INFO Sundae in the Park - Fort Wilkins  is currently unavailable
2024-07-07 22:52:05 INFO Location Michigan (13/125): Changes in 1/192 machines found.
2024-07-07 22:58:10 INFO Storybook Island is available again
2024-07-07 22:58:21 INFO Location South Dakota (20/125): Changes in 1/87 machines found.
2024-07-07 22:59:24 INFO National Frontier Trails Museum got permanently removed
2024-07-07 23:00:22 INFO Location Missouri (22/125): Changes in 1/177 machines found.
2024-07-07 23:30:16 INFO WIS-CO / Suzie's Sweets is currently unavailable
2024-07-07 23:30:37 INFO Location Wisconsin (47/125): Changes in 1/121 machines found.
2024-07-08 00:07:59 INFO 
 Result: 8 changes, 3 new machines found and 4 machines retired
2024-07-08 00:23:39 ERROR Found 3 problems that require manual intervention
2024-07-08 00:23:39 INFO ======Location differ completed at 2024-07-08 00:23:39=======
2024-07-08 00:23:39 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7271 named Buc-ee’s - St. Augustine submitted.

**Review by jannisborn — APPROVED** [review]
Approving already becasuse we got a lot of re-submitted, identical changes

**Pull request merged**
