### PR TITLE
Updates from website (server_locations)

### PR DESCRIPTION
**Pull request by jannisborn**
2024-02-11 22:30:02 INFO ======Location differ joblog from 2024-02-11 22:30:02=======
2024-02-11 22:31:36 INFO Yogi Bear's Jellystone Park - Resort is currently unavailable
2024-02-11 22:31:44 INFO Location Louisiana (1/125): Changes in 1/88 machines found.
2024-02-11 22:58:26 INFO JoDeans Famous Steak and Buffet  is currently unavailable
2024-02-11 22:58:26 INFO Location South Dakota (20/125): Changes in 1/83 machines found.
2024-02-11 23:09:49 INFO 233/294: Found machine to be added: IMAX at Rivercenter
2024-02-11 23:10:34 INFO Location Texas (26/125): Changes in 1/294 machines found.
2024-02-11 23:16:01 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-02-12 00:06:46 INFO 
 Result: 3 changes, 1 new machines found and 2 machines retired
2024-02-12 00:20:07 ERROR Found 5 problems that require manual intervention
2024-02-12 00:20:07 INFO ======Location differ completed at 2024-02-12 00:20:07=======
2024-02-12 00:20:08 INFO Detected change in server_locations.json - push to github

### CODE REVIEW

**Comment by jannisborn** [comment]
2024-02-12 22:30:02 INFO ======Location differ joblog from 2024-02-12 22:30:02=======
2024-02-12 23:16:38 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-02-12 23:45:12 INFO 72/370: Found machine to be added: Botanika
2024-02-12 23:49:33 INFO Location Germany (73/125): Changes in 1/370 machines found.
2024-02-13 00:08:36 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-02-13 00:25:54 ERROR Found 5 problems that require manual intervention
2024-02-13 00:25:54 INFO ======Location differ completed at 2024-02-13 00:25:54=======
2024-02-13 00:25:55 INFO Detected change in server_locations.json - push to github

**Review by NinaWie — APPROVED** [review]

**Comment by jannisborn** [comment]
2024-02-13 22:30:02 INFO ======Location differ joblog from 2024-02-13 22:30:02=======
2024-02-13 22:44:18 INFO Downtown Disney - Star Wars Trading Post is currently unavailable
2024-02-13 22:44:18 INFO Downtown Disney - Tortilla Jo's Restaurant (Was Monorail Entrance) is currently unavailable
2024-02-13 22:50:29 INFO Location California (12/125): Changes in 2/752 machines found.
2024-02-13 23:17:09 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-02-13 23:22:53 INFO Simply Seattle Gift Shop  is currently unavailable
2024-02-13 23:23:08 INFO Location Washington (38/125): Changes in 1/127 machines found.
2024-02-13 23:42:06 INFO 365/426: Found machine to be added: Jimmys Farm 
2024-02-13 23:42:53 INFO Location England (69/125): Changes in 1/426 machines found.
2024-02-14 00:04:51 INFO Del Olmo book store is currently unavailable
2024-02-14 00:07:01 INFO Location Spain (112/125): Changes in 1/167 machines found.
2024-02-14 00:09:24 INFO 
 Result: 5 changes, 1 new machines found and 4 machines retired
2024-02-14 00:23:25 ERROR Found 5 problems that require manual intervention
2024-02-14 00:23:25 INFO ======Location differ completed at 2024-02-14 00:23:25=======
2024-02-14 00:23:26 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-02-14 22:30:02 INFO ======Location differ joblog from 2024-02-14 22:30:02=======
2024-02-14 23:03:21 INFO 16/380: Found machine to be added: Showcase of Citrus 
2024-02-14 23:06:59 INFO Location Florida (24/125): Changes in 1/380 machines found.
2024-02-14 23:16:44 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-02-15 00:08:40 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-02-15 00:22:26 ERROR Found 5 problems that require manual intervention
2024-02-15 00:22:26 INFO ======Location differ completed at 2024-02-15 00:22:26=======
2024-02-15 00:22:27 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-02-15 22:30:02 INFO ======Location differ joblog from 2024-02-15 22:30:02=======
2024-02-15 23:17:10 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-02-15 23:33:19 INFO 21/55: Found machine to be added: Green River Chamber & Visitor Center
2024-02-15 23:33:42 INFO Location Wyoming (50/125): Changes in 1/55 machines found.
2024-02-15 23:44:37 INFO The Basilica of Sacré-Cur de Montmartre is available again
2024-02-15 23:45:10 INFO Location France (72/125): Changes in 1/104 machines found.
2024-02-16 00:03:39 INFO RRS Discover Dundee is currently unavailable
2024-02-16 00:03:48 INFO Kingdom of Sweets is currently unavailable
2024-02-16 00:04:04 INFO Grantown East Highland Heritage & Cultural Centre is currently unavailable
2024-02-16 00:04:20 INFO Location Scotland (107/125): Changes in 3/89 machines found.
2024-02-16 00:09:54 INFO 
 Result: 5 changes, 2 new machines found and 3 machines retired
2024-02-16 00:23:44 ERROR Found 5 problems that require manual intervention
2024-02-16 00:23:44 INFO ======Location differ completed at 2024-02-16 00:23:44=======
2024-02-16 00:23:45 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
No website updates today!

**Pull request merged**
