### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 5355 "Carnival Cruise Lines/Freedom":
	Status from: available to: retired
	Address from: 3655 NW 87th Avenue, Miami  to: 3655 NW 87th Avenue, Miami

### CODE REVIEW

**Comment by jannisborn** [comment]
No website updates today!

**Comment by NinaWie** [comment]
New machine 7575 named Lanxess Arena submitted.

**Comment by NinaWie** [comment]
New machine 7576 named Lola la de los vinos de Frigiliana submitted.

**Comment by jannisborn** [comment]
2024-10-06 22:30:02 INFO ======Location differ joblog from 2024-10-06 22:30:02=======
2024-10-06 22:31:53 INFO Grandpa's Cheesebarn Inc. is available again
2024-10-06 22:33:23 INFO Location Ohio (2/125): Changes in 1/138 machines found.
2024-10-06 22:40:21 INFO Pickles Gap Village - Ozark Country Market is available again
2024-10-06 22:40:47 INFO Location Arkansas (9/125): Changes in 1/56 machines found.
2024-10-06 22:57:25 INFO 96/106: Found machine to be added: Klig's Kites Superstore
2024-10-06 22:57:32 INFO Location South Carolina (17/125): Changes in 1/106 machines found.
2024-10-06 23:02:01 INFO 36/201: Found machine to be added: Buckboard Too Shop
2024-10-06 23:03:50 INFO Location Tennessee (23/125): Changes in 1/201 machines found.
2024-10-06 23:21:47 INFO 137/139: Found machine to be added: Mimi's Cafe (Was Milltown Market)
2024-10-06 23:21:47 INFO Location Illinois (36/125): Changes in 1/139 machines found.
2024-10-06 23:56:57 INFO 102/222: Found machine to be added: Cape Manzamo
2024-10-06 23:58:29 INFO Location Japan (84/125): Changes in 1/222 machines found.
2024-10-07 00:11:26 INFO 
 Result: 6 changes, 6 new machines found and 0 machines retired
2024-10-07 00:17:15 ERROR Our machine Buckboard Too in Tennessee from Device shown as available but http://209.221.138.252/Details.aspx?location=309947 responds Internal Server Error (500)
2024-10-07 00:26:43 ERROR Our machine Odaiba (????)  in Japan from Server shown as available but http://209.221.138.252/Details.aspx?location=429197 responds Internal Server Error (500)
2024-10-07 00:26:47 ERROR Found 3 problems that require manual intervention
2024-10-07 00:26:47 INFO ======Location differ completed at 2024-10-07 00:26:47=======
2024-10-07 00:26:48 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
New problems require attention.

**Comment by jannisborn** [comment]
2024-10-07 22:30:02 INFO ======Location differ joblog from 2024-10-07 22:30:02=======
2024-10-07 23:45:57 INFO 57/401: Found machine to be added: Zitadelle Spandau
2024-10-07 23:50:54 INFO Location Germany (73/125): Changes in 1/401 machines found.
2024-10-08 00:11:18 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-10-08 00:26:28 ERROR Found 3 problems that require manual intervention
2024-10-08 00:26:28 INFO ======Location differ completed at 2024-10-08 00:26:28=======
2024-10-08 00:26:28 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-10-08 22:30:02 INFO ======Location differ joblog from 2024-10-08 22:30:02=======
2024-10-08 23:05:46 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=311321': ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
2024-10-08 23:05:57 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=432970': ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-10-08 23:13:16 INFO Escape the Netherworld is currently unavailable
2024-10-08 23:13:31 INFO Location Georgia (27/125): Changes in 1/131 machines found.
2024-10-08 23:27:01 INFO 24/205: Found machine to be added: The Great Pumpkin Farm
2024-10-08 23:28:26 INFO Location New York (43/125): Changes in 1/205 machines found.
2024-10-08 23:37:24 INFO 45/152: Found machine to be added: Reversing Falls Restaurant at Stonehammer UNESCO Global Geopark
2024-10-08 23:38:22 INFO Location Canada (61/125): Changes in 1/152 machines found.
2024-10-08 23:43:35 INFO Shakespeare's Birthplace is available again
2024-10-08 23:43:58 INFO Location England (69/125): Changes in 1/450 machines found.
2024-10-09 00:11:55 INFO 
 Result: 4 changes, 3 new machines found and 1 machines retired
2024-10-09 00:27:24 ERROR Our machine Yankton Mall in South Dakota from Server shown as available but http://209.221.138.252/Details.aspx?location=428495 responds Internal Server Error (500)
2024-10-09 00:27:30 ERROR Found 3 problems that require manual intervention
2024-10-09 00:27:30 INFO ======Location differ completed at 2024-10-09 00:27:30=======
2024-10-09 00:27:31 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
2024-10-10 22:30:01 INFO ======Location differ joblog from 2024-10-10 22:30:01=======
2024-10-10 23:41:48 INFO 143/451: Found machine to be added: Submarine Museum/ Gosport 
2024-10-10 23:45:03 INFO Location England (69/125): Changes in 1/451 machines found.
2024-10-11 00:06:21 INFO Urquhart Castle is available again
2024-10-11 00:07:02 INFO Location Scotland (107/125): Changes in 1/94 machines found.
2024-10-11 00:13:04 INFO 
 Result: 2 changes, 2 new machines found and 0 machines retired
2024-10-11 00:28:35 ERROR Found 3 problems that require manual intervention
2024-10-11 00:28:35 INFO ======Location differ completed at 2024-10-11 00:28:35=======
2024-10-11 00:28:36 INFO Detected change in server_locations.json - push to github

**Review by jannisborn — APPROVED** [review]
LGTM

**Pull request merged**
