### PR TITLE
Updates from website (server_locations)

### PR DESCRIPTION
**Pull request by jannisborn**
INFO:__main__:======Location differ joblog from 2023-12-11 22:30:05=======
INFO:googlemaps.client:API queries_quota: 60
ERROR:pennyme.pennycollector:Geolocation failed for: Unknown Location 	 sub: , Arco
INFO:__main__:
 Result: 0 changes, 0 new machines found and 0 machines retired
ERROR:pennyme.utils:Our machine Burg Teck in Germany from Device shown as available but http://209.221.138.252/Details.aspx?location=246970 responds Internal Server Error (500)
ERROR:pennyme.utils:Our machine Hameln Marketing und Tourismus in Germany from Device shown as available but http://209.221.138.252/Details.aspx?location=268665 responds Internal Server Error (500)
ERROR:pennyme.utils:Our machine Souvenir Shop in Germany from Device shown as available but http://209.221.138.252/Details.aspx?location=259089 responds Internal Server Error (500)
ERROR:pennyme.utils:Our machine Otter-Zentrum Hankensbüttel in Germany from Device shown as available but http://209.221.138.252/Details.aspx?location=277935 responds Internal Server Error (500)
ERROR:pennyme.utils:Our machine U-434 in Germany from Device shown as available but http://209.221.138.252/Details.aspx?location=280109 responds Internal Server Error (500)
ERROR:pennyme.utils:Our machine Heringsdorf (Usedom Island) in Germany from Device shown as available but http://209.221.138.252/Details.aspx?location=254858 responds Internal Server Error (500)
ERROR:pennyme.utils:Our machine Schloss Lichtenstein in Germany from Server shown as available but http://209.221.138.252/Details.aspx?location=411920 responds Internal Server Error (500)
ERROR:__main__:Found 5 problems that require manual intervention
INFO:__main__:======Location differ completed at 2023-12-12 00:19:08=======

### CODE REVIEW

**Comment by jannisborn** [comment]
Looks like the machines were silently removed from the website. Not by setting the status to "gone" and keeping the link active, but really by removing the links entirely (as indicated in the logs posted by the bot). 


Since the bot is checking links of ALL machines every day, this is being discovered and the links are being removed.

**Comment by jannisborn** [comment]
INFO:__main__:======Location differ joblog from 2023-12-12 22:30:04=======
INFO:googlemaps.client:API queries_quota: 60
ERROR:pennyme.pennycollector:Geolocation failed for: Unknown Location 	 sub: , Arco
INFO:__main__:Sea Quest Lynchburg is currently unavailable
INFO:__main__:Location Virginia (35/125): Changes in 1/121 machines found.
INFO:__main__:Los Cabos International Airport (SJD) is currently unavailable
INFO:__main__:Location Mexico (93/125): Changes in 1/28 machines found.
INFO:__main__:16/35: Found machine to be added: Tamsui Old Street 
INFO:__main__:19/35: Found machine to be added: Yehliu Ocean World
INFO:__main__:Location Taiwan (118/125): Changes in 2/35 machines found.
INFO:__main__:
 Result: 4 changes, 2 new machines found and 2 machines retired
ERROR:__main__:Found 5 problems that require manual intervention
INFO:__main__:======Location differ completed at 2023-12-13 00:18:51=======

**Comment by NinaWie** [comment]
New machine 6996 named Café du Monde 2 (on the Right) submitted.

**Comment by jannisborn** [comment]
INFO:__main__:======Location differ joblog from 2023-12-13 22:30:04=======
INFO:googlemaps.client:API queries_quota: 60
INFO:__main__:42/104: Found machine to be added: On Point
INFO:__main__:Location Minnesota (16/125): Changes in 1/104 machines found.
ERROR:pennyme.pennycollector:Geolocation failed for: Unknown Location 	 sub: , Arco
INFO:__main__:6/37: Found machine to be added: National Museum of Marine Science and Technology
INFO:__main__:30/37: Found machine to be added: Maokong Gondola - in front of Kuang Ting Tea Garden
INFO:__main__:Location Taiwan (118/125): Changes in 2/37 machines found.
INFO:__main__:
 Result: 3 changes, 3 new machines found and 0 machines retired
ERROR:__main__:Found 5 problems that require manual intervention
INFO:__main__:======Location differ completed at 2023-12-14 00:23:18=======

**Review by NinaWie — APPROVED** [review]

**Pull request merged**
