### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by jannisborn**
2024-05-29 22:30:01 INFO ======Location differ joblog from 2024-05-29 22:30:01=======
2024-05-29 22:43:56 INFO 52/754: Found machine to be added: Beary Bliss
2024-05-29 22:49:25 INFO Location California (12/125): Changes in 1/754 machines found.
2024-05-29 23:18:04 INFO Great Wolf Lodge is currently unavailable
2024-05-29 23:18:42 INFO Location Illinois (36/125): Changes in 1/137 machines found.
2024-05-30 00:05:09 INFO 
 Result: 2 changes, 1 new machines found and 1 machines retired
2024-05-30 00:19:47 ERROR Found 3 problems that require manual intervention
2024-05-30 00:19:47 INFO ======Location differ completed at 2024-05-30 00:19:47=======
2024-05-30 00:19:47 INFO Detected change in server_locations.json - push to github

### CODE REVIEW

**Comment by jannisborn** [comment]
2024-05-30 22:30:02 INFO ======Location differ joblog from 2024-05-30 22:30:02=======
2024-05-30 23:19:33 INFO Grand Coulee Dam Visitor's Arrival Center is currently unavailable
2024-05-30 23:20:43 INFO Location Washington (38/125): Changes in 1/129 machines found.
2024-05-31 00:05:11 INFO 
 Result: 1 changes, 0 new machines found and 1 machines retired
2024-05-31 00:19:56 ERROR Found 3 problems that require manual intervention
2024-05-31 00:19:56 INFO ======Location differ completed at 2024-05-31 00:19:56=======
2024-05-31 00:19:57 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-05-31 22:30:01 INFO ======Location differ joblog from 2024-05-31 22:30:01=======
2024-05-31 22:37:33 INFO Meteor Crater, The Museum of Astrogeology is available again
2024-05-31 22:37:34 INFO Location Arizona (6/125): Changes in 1/223 machines found.
2024-05-31 23:17:06 INFO Harmon Corner - Rainforest Café is available again
2024-05-31 23:18:37 INFO Location Nevada (31/125): Changes in 1/204 machines found.
2024-05-31 23:47:07 INFO 17/105: Found machine to be added: France Miniature
2024-05-31 23:48:23 INFO Location France (72/125): Changes in 1/105 machines found.
2024-06-01 00:12:15 INFO 
 Result: 3 changes, 3 new machines found and 0 machines retired
2024-06-01 00:27:01 ERROR Found 3 problems that require manual intervention
2024-06-01 00:27:01 INFO ======Location differ completed at 2024-06-01 00:27:01=======
2024-06-01 00:27:02 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
2024-06-02 22:30:02 INFO ======Location differ joblog from 2024-06-02 22:30:02=======
2024-06-02 22:55:23 INFO 99/106: Found machine to be added: Two Harbors Area Chamber Of Commerce "Tourist Information" Center
2024-06-02 22:55:28 INFO Location Minnesota (16/125): Changes in 1/106 machines found.
2024-06-02 23:13:58 INFO Distance match - Seeems that machine The Coffee Cup Cafe at 512 Nevada Way, Boulder City already exists as: World Famous Coffee Cup Café
2024-06-02 23:32:41 INFO 2/56: Found machine to be added: Burg Kreuzen
2024-06-02 23:33:29 INFO Location Austria (54/125): Changes in 1/56 machines found.
2024-06-02 23:33:55 INFO Makin Waves got permanently removed
2024-06-02 23:33:55 INFO Location Bermuda (58/125): Changes in 1/3 machines found.
2024-06-03 00:03:44 INFO 118/174: Found machine to be added: Cova de can Marça
2024-06-03 00:04:30 INFO Location Spain (112/125): Changes in 1/174 machines found.
2024-06-03 00:06:49 INFO 
 Result: 4 changes, 3 new machines found and 0 machines retired
2024-06-03 00:21:40 ERROR Found 3 problems that require manual intervention
2024-06-03 00:21:40 INFO ======Location differ completed at 2024-06-03 00:21:40=======
2024-06-03 00:21:41 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-06-03 22:30:01 INFO ======Location differ joblog from 2024-06-03 22:30:01=======
2024-06-03 22:57:19 INFO 15/28: Found machine to be added: Keith's Superstore
2024-06-03 22:57:30 INFO Location Mississippi (19/125): Changes in 1/28 machines found.
2024-06-03 23:15:35 INFO New York New York Hotel & Casino - Arcade is available again
2024-06-03 23:16:10 INFO Location Nevada (31/125): Changes in 1/205 machines found.
2024-06-03 23:57:58 INFO 60/145: Found machine to be added: Souvenirs shop
2024-06-03 23:59:08 INFO Location Netherlands (94/125): Changes in 1/145 machines found.
2024-06-04 00:08:10 INFO 
 Result: 3 changes, 3 new machines found and 0 machines retired
2024-06-04 00:22:10 ERROR Our machine Bsum MS Funny Girl in Germany from Server shown as retired but http://www.elongated-coin.de/phpBB3/viewtopic.php?t=7333 responds Not Found (404)
2024-06-04 00:23:16 ERROR Found 3 problems that require manual intervention
2024-06-04 00:23:16 INFO ======Location differ completed at 2024-06-04 00:23:16=======
2024-06-04 00:23:17 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-06-04 22:30:02 INFO ======Location differ joblog from 2024-06-04 22:30:02=======
2024-06-04 22:47:36 INFO Old Town - Dantes Leather got permanently removed
2024-06-04 22:49:45 INFO Location California (12/125): Changes in 1/754 machines found.
2024-06-04 23:31:37 INFO Craig Thomas Discover & Visitor Center is available again
2024-06-04 23:32:03 INFO Location Wyoming (50/125): Changes in 1/55 machines found.
2024-06-04 23:43:45 INFO Distance match - Seeems that machine Interklassik Ticket & Info Point at Unter den Linden 78, Berlin already exists as: Brandenburg Gate Shop 2
2024-06-05 00:07:39 INFO 
 Result: 2 changes, 1 new machines found and 0 machines retired
2024-06-05 00:21:36 ERROR Our machine Bsum Meereswelten in Germany from Server shown as retired but http://www.elongated-coin.de/phpBB3/viewtopic.php?t=1875 responds Bad Gateway (502)
2024-06-05 00:22:42 ERROR Found 3 problems that require manual intervention
2024-06-05 00:22:42 INFO ======Location differ completed at 2024-06-05 00:22:42=======
2024-06-05 00:22:42 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-06-05 22:30:02 INFO ======Location differ joblog from 2024-06-05 22:30:02=======
2024-06-05 22:51:30 INFO USS Silversides Submarine Museum is currently unavailable
2024-06-05 22:52:07 INFO Location Michigan (13/125): Changes in 1/190 machines found.
2024-06-05 22:58:17 INFO Sturgis Motorcycle Museum and Hall of Fame is available again
2024-06-05 22:58:23 INFO Location South Dakota (20/125): Changes in 1/85 machines found.
2024-06-05 23:01:44 INFO Cooters Place is available again
2024-06-05 23:02:37 INFO Location Tennessee (23/125): Changes in 1/198 machines found.
2024-06-06 00:07:55 INFO 
 Result: 3 changes, 2 new machines found and 1 machines retired
2024-06-06 00:22:54 ERROR Our machine Buc-ee's in Colorado from Server shown as available but http://209.221.138.252/Details.aspx?location=425563 responds Internal Server Error (500)
2024-06-06 00:22:56 ERROR Found 3 problems that require manual intervention
2024-06-06 00:22:56 INFO ======Location differ completed at 2024-06-06 00:22:56=======
2024-06-06 00:22:56 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7200 named Fulton Mansion Historical Site submitted.

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
2024-06-07 22:30:02 INFO ======Location differ joblog from 2024-06-07 22:30:02=======
2024-06-07 23:15:33 INFO Luxor Hotel Casino - Titanic, The Artifact Exhibition is currently unavailable
2024-06-07 23:16:12 INFO Location Nevada (31/125): Changes in 1/205 machines found.
2024-06-07 23:26:48 INFO West Point Military Academy Visitors Center is currently unavailable
2024-06-07 23:26:49 INFO Location New York (43/125): Changes in 1/201 machines found.
2024-06-07 23:32:18 INFO Old Faithful Lodge Gift Shop is available again
2024-06-07 23:32:20 INFO 44/56: Found machine to be added: Old Faithful Snow Lodge
2024-06-07 23:32:20 INFO Yellowstone - Canyon Village  Education Center is currently unavailable
2024-06-07 23:32:21 INFO Yellowstone - Canyon Village General Store is available again
2024-06-07 23:32:25 INFO Seeems that machine Yellowstone - Old Faithful Inn Gift Shop at West Entrance Road, Yellowstone National Park already exists as: West Entrance Road, Yellowstone National Park
2024-06-07 23:32:31 INFO Location Wyoming (1119/125): Changes in 4/56 machines found.
2024-06-07 23:59:47 INFO 0/11: Found machine to be added: St. Mary's Church Bazylika Mariacka Wniebowziecia Najswietszej Maryi Panny 
2024-06-07 23:59:55 INFO Location Poland (100/125): Changes in 1/11 machines found.
2024-06-08 00:08:12 INFO 
 Result: 7 changes, 4 new machines found and 3 machines retired
2024-06-08 00:23:20 ERROR Found 3 problems that require manual intervention
2024-06-08 00:23:20 INFO ======Location differ completed at 2024-06-08 00:23:20=======
2024-06-08 00:23:21 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
No website updates today!

**Pull request merged**
