### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 5943 "San Sebastian de La Gomera":
	Title from: Isla La Gomera to: San Sebastian de La Gomera
	Address from: Tienda Casa de Los Balcones (Artesanía La Gomera) +34 922 14 51 90 https://goo.gl/maps/gLXnMyLCxwLRasEh6, San Sebastian de la Gomera to: Tienda Casa de Los Balcones (Artesanía La Gomera), San Sebastian de la Gomera

### CODE REVIEW

**Comment by NinaWie** [comment]
New machine 7043 named Test and & plus + dollar $ percent % signs submitted.

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
2024-02-09 22:30:02 INFO ======Location differ joblog from 2024-02-09 22:30:02=======
2024-02-09 23:14:52 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-02-09 23:25:42 INFO 35/47: Found machine to be added: Smoky Hill Museum
2024-02-09 23:25:51 INFO Location Kansas (45/125): Changes in 1/47 machines found.
2024-02-10 00:04:20 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-02-10 00:17:22 ERROR Found 5 problems that require manual intervention
2024-02-10 00:17:22 INFO ======Location differ completed at 2024-02-10 00:17:22=======
2024-02-10 00:17:23 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
No website updates today!

**Review by jannisborn — APPROVED** [review]

**Pull request merged**
