### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 712 "Wasserkirche (Zürich)":
	 Location from: 47.3703, 8.5433 to: 47.3703, 8.5433

### CODE REVIEW

**Comment by NinaWie** [comment]
New machine 7610 named Machine 1 submitted.

**Comment by NinaWie** [comment]
New machine 7611 named Gent souvenirs submitted.

**Comment by jannisborn** [comment]
2024-10-29 22:30:02 INFO ======Location differ joblog from 2024-10-29 22:30:02=======
2024-10-29 22:38:17 INFO 27/71: Found machine to be added: Outtens Delites in Maryland
2024-10-29 22:40:56 INFO Caffe Vittoria is available again
2024-10-29 23:34:03 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-10-29 23:34:04 INFO 48/55: Found machine to be added: Mammoth General Store in Wyoming
2024-10-29 23:39:45 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-10-29 23:39:47 INFO 51/452: Found machine to be added: The World of Beatrix Potter Attraction in England
2024-10-29 23:58:01 INFO 179/223: Found machine to be added: Tokyo DisneySea Fantasy Springs Hotel in Japan
2024-10-30 00:10:12 INFO 28/53: Found machine to be added: Old Taichung Main Train Station  in Taiwan
2024-10-30 00:11:42 INFO 
 Result: 6 changes, 6 new machines found and 0 machines retired
2024-10-30 00:19:30 ERROR Our machine Knight Museum & Sandhills Center in Nebraska from Device shown as available but http://209.221.138.252/Details.aspx?location=398574 responds Internal Server Error (500)
2024-10-30 00:26:31 ERROR Found 8 problems that require manual intervention
2024-10-30 00:26:31 INFO ======Location differ completed at 2024-10-30 00:26:31=======
2024-10-30 00:26:32 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
New problems require attention.

**Comment by NinaWie** [comment]
New machine 7617 named Berlin Wall Memorial submitted.

**Comment by NinaWie** [comment]
New machine 7618 named Camera Obscura submitted.

**Comment by jannisborn** [comment]
2024-10-30 22:30:02 INFO ======Location differ joblog from 2024-10-30 22:30:02=======
2024-10-30 22:51:55 INFO 110/195: Found machine to be added: I-75 Plaza  in Michigan
2024-10-30 23:15:16 INFO Zion Lodge is available again
2024-10-30 23:28:30 INFO Rest Area 69, W Virginia Turnpike is available again
2024-10-30 23:34:04 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-10-30 23:39:45 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-10-31 00:04:59 INFO 18/94: Found machine to be added: RRS Discovery in Scotland
2024-10-31 00:11:41 INFO 
 Result: 4 changes, 4 new machines found and 0 machines retired
2024-10-31 00:26:31 ERROR Found 8 problems that require manual intervention
2024-10-31 00:26:31 INFO ======Location differ completed at 2024-10-31 00:26:31=======
2024-10-31 00:26:32 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
New problems require attention.

**Comment by NinaWie** [comment]
New machine 7622 named Yosemite village store submitted.

**Comment by jannisborn** [comment]
2024-10-31 22:30:02 INFO ======Location differ joblog from 2024-10-31 22:30:02=======
2024-10-31 23:07:11 INFO Aunt Matilda's Steampunk Trunk is available again
2024-10-31 23:34:04 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-10-31 23:35:20 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=443418': ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
2024-10-31 23:35:30 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=413510': HTTPConnectionPool(host='209.221.138.252', port=80): Max retries exceeded with url: /Details.aspx?location=413510 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff1950127f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-10-31 23:40:06 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-11-01 00:12:00 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-11-01 00:26:50 ERROR Found 8 problems that require manual intervention
2024-11-01 00:26:50 INFO ======Location differ completed at 2024-11-01 00:26:50=======
2024-11-01 00:26:50 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7623 named Marktplatz Düsseldorf submitted.

**Comment by NinaWie** [comment]
New machine 7624 named Marktplatz Düsseldorf 2 submitted.

**Comment by jannisborn** [comment]
2024-11-01 22:30:02 INFO ======Location differ joblog from 2024-11-01 22:30:02=======
2024-11-01 23:32:02 INFO 55/122: Found machine to be added: Pabst Mansion in Wisconsin
2024-11-01 23:34:23 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-11-01 23:40:05 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-11-01 23:45:43 INFO Phare des Baleines île de ré (in France) is currently unavailable
2024-11-02 00:11:59 INFO 
 Result: 2 changes, 1 new machines found and 1 machines retired
2024-11-02 00:26:53 ERROR Found 8 problems that require manual intervention
2024-11-02 00:26:53 INFO ======Location differ completed at 2024-11-02 00:26:53=======
2024-11-02 00:26:54 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7626 named Ailwee cave bird of prey submitted.

**Comment by jannisborn** [comment]
2024-11-02 22:30:01 INFO ======Location differ joblog from 2024-11-02 22:30:01=======
2024-11-02 23:33:17 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-11-02 23:38:53 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-11-02 23:55:04 INFO 46/224: Found machine to be added: Hotel Ichii in Japan
2024-11-03 00:10:28 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-11-03 00:25:07 ERROR Found 8 problems that require manual intervention
2024-11-03 00:25:07 INFO ======Location differ completed at 2024-11-03 00:25:07=======
2024-11-03 00:25:08 INFO Detected change in server_locations.json - push to github

**Review by jannisborn — APPROVED** [review]

**Pull request merged**
