### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by jannisborn**
2024-11-03 22:30:02 INFO ======Location differ joblog from 2024-11-03 22:30:02=======
2024-11-03 23:08:45 INFO Capitol Visitor's Center is available again
2024-11-03 23:34:05 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-11-03 23:39:46 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-11-03 23:53:34 INFO Distance match - Seeems that machine Aillwee Burren Experience  at  , Ballyvaughan, Co. Clare already exists as: Ailwee cave bird of prey
2024-11-04 00:11:51 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-11-04 00:26:39 ERROR Found 8 problems that require manual intervention
2024-11-04 00:26:39 INFO ======Location differ completed at 2024-11-04 00:26:39=======
2024-11-04 00:26:40 INFO Detected change in server_locations.json - push to github

### CODE REVIEW

**Comment by jannisborn** [comment]
2024-11-04 22:30:01 INFO ======Location differ joblog from 2024-11-04 22:30:01=======
2024-11-04 22:34:08 INFO 59/69: Found machine to be added: Skagway Trading Co. in Alaska
2024-11-04 22:54:38 INFO Seems that machine Buc-ees already exists as: Buc-ee's
2024-11-04 23:01:23 INFO Jesse James Wax Museum (in Missouri) is currently unavailable
2024-11-04 23:34:19 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-11-04 23:40:01 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-11-05 00:00:01 INFO St. John's Cathedral, Valletta is available again
2024-11-05 00:12:04 INFO 
 Result: 3 changes, 2 new machines found and 1 machines retired
2024-11-05 00:26:53 ERROR Found 8 problems that require manual intervention
2024-11-05 00:26:53 INFO ======Location differ completed at 2024-11-05 00:26:53=======
2024-11-05 00:26:54 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-11-05 22:30:02 INFO ======Location differ joblog from 2024-11-05 22:30:02=======
2024-11-05 22:56:07 INFO 77/109: Found machine to be added: Hanisch Bakery & Coffee Shop in Minnesota
2024-11-05 23:33:10 INFO Louisville Mega Cavern (in Kentucky) is currently unavailable
2024-11-05 23:34:21 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-11-05 23:40:03 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-11-05 23:55:35 INFO 135/146: Found machine to be added: Palazzo Storico del Mercato in Italy
2024-11-06 00:12:00 INFO 
 Result: 3 changes, 2 new machines found and 1 machines retired
2024-11-06 00:26:51 ERROR Found 8 problems that require manual intervention
2024-11-06 00:26:51 INFO ======Location differ completed at 2024-11-06 00:26:51=======
2024-11-06 00:26:52 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7631 named Pressed Penny Collectibles submitted.

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
2024-11-07 22:30:01 INFO ======Location differ joblog from 2024-11-07 22:30:01=======
2024-11-07 23:34:08 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-11-07 23:39:50 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-11-08 00:04:20 INFO Señor Frogs (in Puerto Rico) is currently unavailable
2024-11-08 00:11:49 INFO 
 Result: 1 changes, 0 new machines found and 1 machines retired
2024-11-08 00:26:40 ERROR Found 8 problems that require manual intervention
2024-11-08 00:26:40 INFO ======Location differ completed at 2024-11-08 00:26:40=======
2024-11-08 00:26:41 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-11-08 22:30:02 INFO ======Location differ joblog from 2024-11-08 22:30:02=======
2024-11-08 23:25:25 INFO 26/94: Found machine to be added: The Breaking Bad Store ABQ in New Mexico
2024-11-08 23:34:28 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-11-08 23:40:11 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-11-08 23:52:47 INFO Budapest Museum of Agriculture (in Hungary) is currently unavailable
2024-11-08 23:52:49 INFO Citadel (in Hungary) is currently unavailable
2024-11-09 00:12:12 INFO 
 Result: 3 changes, 1 new machines found and 2 machines retired
2024-11-09 00:27:04 ERROR Found 8 problems that require manual intervention
2024-11-09 00:27:04 INFO ======Location differ completed at 2024-11-09 00:27:04=======
2024-11-09 00:27:05 INFO Detected change in server_locations.json - push to github

**Review by NinaWie — APPROVED** [review]

**Pull request merged**
