### PR TITLE
Updates from website (server_locations)

### PR DESCRIPTION
**Pull request by jannisborn**
2024-01-20 22:30:01 INFO ======Location differ joblog from 2024-01-20 22:30:01=======
2024-01-20 23:14:27 INFO Downtown Las Vegas - Golden Nugget Hotel Casino is available again
2024-01-20 23:15:34 INFO Location Nevada (31/125): Changes in 1/203 machines found.
2024-01-20 23:15:47 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-01-21 00:06:34 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-01-21 00:19:44 ERROR Found 5 problems that require manual intervention
2024-01-21 00:19:44 INFO ======Location differ completed at 2024-01-21 00:19:44=======
2024-01-21 00:19:45 INFO Detected change in server_locations.json - push to github

### CODE REVIEW

**Comment by NinaWie** [comment]
Request change to machine 4499 named Downtown Las Vegas - Golden Nugget Hotel Casino - Changed:
	Status from: available to: out-of-order

**Comment by NinaWie** [comment]
Request change to machine 6256 named One Niagara Welcome Center - Changed:
	Status from: available to: out-of-order

**Comment by NinaWie** [comment]
Request change to machine 3065 named Niagara Wax Museum - Changed:

**Comment by NinaWie** [comment]
Request change to machine 3065 named Niagara Wax Museum - Changed:
Machine with pending changes is getting changed *AGAIN* @jannisborn @NinaWie:
	Status from: available to: out-of-order

**Comment by NinaWie** [comment]
Request change to machine 3066 named Quality Hotel - Changed:
	Title from: Quality Hotel & Suites to: Quality Hotel
	Multimachine from: 1 to: 2

**Comment by NinaWie** [comment]
Request change to machine 1743 named Underwater World - Changed:
	Multimachine from: 1 to: 2

**Comment by NinaWie** [comment]
Request change to machine 5199 named Red Rock Impressions - Changed:
	Status from: available to: retired

**Comment by jannisborn** [comment]
No website updates today!

**Comment by NinaWie** [comment]
Request change to machine 5358 named Pirate's Dinner Adventure - Changed:
	Status from: available to: out-of-order

**Comment by NinaWie** [comment]
Request change to machine 4376 named Old Bayfront Bazaar - Changed:
	Status from: available to: retired
	Title from: Old Bayfront Bazaar  to: Old Bayfront Bazaar

**Comment by NinaWie** [comment]
Request change to machine 4376 named Old Bayfront Bazaar - Changed:
Machine with pending changes is getting changed *AGAIN* @jannisborn @NinaWie:

**Comment by jannisborn** [comment]
2024-01-22 22:30:02 INFO ======Location differ joblog from 2024-01-22 22:30:02=======
2024-01-22 23:15:48 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-01-23 00:06:03 INFO 
 Result: 0 changes, 0 new machines found and 0 machines retired
2024-01-23 00:17:39 ERROR Our machine Fort Sumpter National Historic Park in South Carolina from Server shown as available but http://209.221.138.252/Details.aspx?location=403212 responds Internal Server Error (500)
2024-01-23 00:19:08 ERROR Found 5 problems that require manual intervention
2024-01-23 00:19:08 INFO ======Location differ completed at 2024-01-23 00:19:08=======
2024-01-23 00:19:09 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
No website updates today!

**Review by NinaWie — APPROVED** [review]

**Pull request merged**
