### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
New machine 7297 named Souvenir shop entrance portaventura world submitted.

### CODE REVIEW

**Comment by jannisborn** [comment]
2024-07-15 22:30:02 INFO ======Location differ joblog from 2024-07-15 22:30:02=======
2024-07-15 22:41:20 INFO 79/91: Found machine to be added: Mardells gift shop
2024-07-15 22:41:24 INFO Location Massachusetts (10/125): Changes in 1/91 machines found.
2024-07-15 22:43:33 INFO Harley Davidson Tour Center got permanently removed
2024-07-15 22:43:33 INFO Location Pennsylvania (11/125): Changes in 1/211 machines found.
2024-07-15 22:54:56 INFO Legacy Toys is currently unavailable
2024-07-15 22:55:45 INFO Location Minnesota (16/125): Changes in 1/106 machines found.
2024-07-15 23:01:14 INFO 27/199: Found machine to be added: Farmers Furniture 
2024-07-15 23:03:04 INFO Location Tennessee (23/125): Changes in 1/199 machines found.
2024-07-15 23:36:31 INFO Kingston and Pembroke Railway Station Visitor Information Center is currently unavailable
2024-07-15 23:37:12 INFO Location Canada (61/125): Changes in 1/148 machines found.
2024-07-16 00:07:34 INFO 13/48: Found machine to be added: ????DAEBAK (Shifen Old Street)
2024-07-16 00:07:55 INFO 37/48: Found machine to be added: Spy x Family Cafe (inside Eslite Spectrum Wuchang Mall)
2024-07-16 00:08:04 INFO Location Taiwan (118/125): Changes in 2/48 machines found.
2024-07-16 00:09:13 INFO 
 Result: 7 changes, 4 new machines found and 2 machines retired
2024-07-16 00:23:12 ERROR Our machine Liberty Bell Center in Pennsylvania from Server shown as available but http://209.221.138.252/Details.aspx?location=411247 responds Internal Server Error (500)
2024-07-16 00:24:55 ERROR Our machine Cova de can Marça in Spain from Server shown as available but http://209.221.138.252/Details.aspx?location=430679 responds Internal Server Error (500)
2024-07-16 00:24:56 ERROR Found 3 problems that require manual intervention
2024-07-16 00:24:56 INFO ======Location differ completed at 2024-07-16 00:24:56=======
2024-07-16 00:24:57 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7302 named Mackinaw Crossing submitted.

**Comment by jannisborn** [comment]
2024-07-16 22:30:01 INFO ======Location differ joblog from 2024-07-16 22:30:01=======
2024-07-16 22:41:21 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=3963': ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
2024-07-16 22:41:59 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=3952': ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-07-16 22:42:40 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=3956': HTTPConnectionPool(host='209.221.138.252', port=80): Max retries exceeded with url: /Details.aspx?location=3956 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f323cf0a3d0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
2024-07-17 00:09:22 INFO 13/20: Found machine to be added: Barbara Souvenirs 'E' Gifts
2024-07-17 00:09:27 INFO Location Slovenia (109/125): Changes in 1/20 machines found.
2024-07-17 00:13:12 INFO 38/52: Found machine to be added: Tea Colors Cafe - Thermal Valley 
2024-07-17 00:13:23 INFO 49/52: Found machine to be added: The Cyrstal Inn
2024-07-17 00:13:25 INFO 50/52: Found machine to be added: Yiyong Street
2024-07-17 00:13:27 INFO 51/52: Found machine to be added: Shuishe Visitor Center/ Mall
2024-07-17 00:13:27 INFO Location Taiwan (118/125): Changes in 4/52 machines found.
2024-07-17 00:14:36 INFO 
 Result: 5 changes, 5 new machines found and 0 machines retired
2024-07-17 00:30:23 ERROR Found 3 problems that require manual intervention
2024-07-17 00:30:23 INFO ======Location differ completed at 2024-07-17 00:30:23=======
2024-07-17 00:30:24 INFO Detected change in server_locations.json - push to github

**Review by jannisborn — APPROVED** [review]

**Comment by jannisborn** [comment]
2024-07-21 22:32:33 INFO ======Location differ joblog from 2024-07-21 22:32:33=======
2024-07-21 22:37:05 INFO 21/70: Found machine to be added: Fish Connection 
2024-07-21 22:37:08 INFO 22/70: Found machine to be added: Fish Connection 
2024-07-21 22:37:48 INFO Location Alaska (3/125): Changes in 2/70 machines found.
2024-07-21 22:40:22 INFO 58/224: Found machine to be added: Lake Havasu City Visitor Center
2024-07-21 22:42:34 INFO Location Arizona (6/125): Changes in 1/224 machines found.
2024-07-21 22:42:56 INFO 28/69: Found machine to be added: Western Pressed Penny Souvenir shop 
2024-07-21 22:43:15 INFO Dolle's Candyland is available again
2024-07-21 22:43:27 INFO Location Maryland (7/125): Changes in 2/69 machines found.
2024-07-21 23:04:45 INFO Cabela's is currently unavailable
2024-07-21 23:05:13 INFO Location Minnesota (16/125): Changes in 1/106 machines found.
2024-07-21 23:05:56 INFO 50/103: Found machine to be added: Broadway at the Beach - Klig's Kites
2024-07-21 23:06:00 INFO Broadway at the Beach - Wheel Chair and Scooter Rentals is currently unavailable
2024-07-21 23:06:19 INFO Lost Treasure Golf (Professor Hacker's) is available again
2024-07-21 23:06:27 INFO Location South Carolina (17/125): Changes in 3/103 machines found.
2024-07-21 23:13:30 INFO Dolly Parton's Stampede is available again
2024-07-21 23:14:05 INFO Location Tennessee (23/125): Changes in 1/199 machines found.
2024-07-21 23:58:04 INFO 379/442: Found machine to be added: Pleasurewood Hills Family Theme Park
2024-07-21 23:58:42 INFO Location England (69/125): Changes in 1/442 machines found.
2024-07-22 00:07:07 INFO Buda Castle Funicular is currently unavailable
2024-07-22 00:07:23 INFO 26/85: Found machine to be added: Margit Sziget Szabadtéri Színpad
2024-07-22 00:07:41 INFO Distance match - Seeems that machine Gödölloi Kastély at Gödöllo, Grassalkovich-Kastély 5852, 2100, Gödöllo already exists as: Gödöllo Royal Palace
2024-07-22 00:07:46 INFO 51/85: Found machine to be added: Aqua Szuvenír
2024-07-22 00:08:18 INFO Location Hungary (1141/125): Changes in 3/85 machines found.
2024-07-22 00:14:58 INFO 5/147: Found machine to be added: Tourist Office Amersfoort (VVV)
2024-07-22 00:16:43 INFO Location Netherlands (94/125): Changes in 1/147 machines found.
2024-07-22 00:18:31 INFO Clérigos Church Tower is currently unavailable
2024-07-22 00:18:43 INFO Location Portugal (101/125): Changes in 1/73 machines found.
2024-07-22 00:24:14 INFO 22/26: Found machine to be added: Thun Boat Dock
2024-07-22 00:24:17 INFO Location Switzerland (117/125): Changes in 1/26 machines found.
2024-07-22 00:26:17 INFO 
 Result: 17 changes, 13 new machines found and 4 machines retired
2024-07-22 00:27:43 ERROR Our machine Assateague Island gifts and merchandise in Maryland from Device shown as available but http://209.221.138.252/Details.aspx?location=358309 responds Internal Server Error (500)
2024-07-22 00:42:24 ERROR Found 3 problems that require manual intervention
2024-07-22 00:42:24 INFO ======Location differ completed at 2024-07-22 00:42:24=======
2024-07-22 00:42:24 INFO Detected change in server_locations.json - push to github

**Pull request merged**
