### PR TITLE
More robust Queue + Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 6148 "Fort Sumpter National Historic Park":
	Status from: available to: retired

### CODE REVIEW

**Comment by jannisborn** [comment]
2024-02-25 22:30:01 INFO ======Location differ joblog from 2024-02-25 22:30:01=======
2024-02-25 23:16:26 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-02-25 23:34:13 INFO Seeems that machine Scharfberg at On the mountain , Unterrach already exists as: At the boatlanding on the lake shore, Bregenz - Lake Constance
2024-02-25 23:37:38 INFO Seeems that machine Odds Farm at Wooburn Common, Odds Farm Park, Wooburn Common Rd, Wooburn Green,  , BUCKINGHAMSHIRE - High Wycombe already exists as: Lodmoor Country Park, Weymouth DT4 7SX, United Kingdom
2024-02-25 23:38:06 INFO Oasis, Centre Parcs is currently unavailable
2024-02-25 23:40:14 INFO 261/433: Found machine to be added: Tower Of London
2024-02-25 23:41:45 INFO Twycross Zoo (East Midland Zoological Society) is currently unavailable
2024-02-25 23:42:14 INFO Location England (995/125): Changes in 3/433 machines found.
2024-02-26 00:08:11 INFO 
 Result: 3 changes, 1 new machines found and 2 machines retired
2024-02-26 00:22:04 ERROR Found 5 problems that require manual intervention
2024-02-26 00:22:04 INFO ======Location differ completed at 2024-02-26 00:22:04=======
2024-02-26 00:22:05 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-02-26 22:30:02 INFO ======Location differ joblog from 2024-02-26 22:30:02=======
2024-02-26 23:16:27 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-02-26 23:49:38 INFO 0/18: Found machine to be added: Cityplaza
2024-02-26 23:49:55 INFO Location Hong Kong (77/125): Changes in 1/18 machines found.
2024-02-27 00:08:10 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-02-27 00:22:03 ERROR Found 5 problems that require manual intervention
2024-02-27 00:22:03 INFO ======Location differ completed at 2024-02-27 00:22:03=======
2024-02-27 00:22:04 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-02-27 22:30:02 INFO ======Location differ joblog from 2024-02-27 22:30:02=======
2024-02-27 23:16:25 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-02-27 23:37:00 INFO 8/22: Found machine to be added: Bazilika sv. Petra a Pavla 
2024-02-27 23:37:06 INFO 19/22: Found machine to be added: U Fleku
2024-02-27 23:37:08 INFO Location Czech Republic (66/125): Changes in 2/22 machines found.
2024-02-27 23:40:51 INFO Rufford Abbey Country Park is currently unavailable
2024-02-27 23:41:59 INFO Location England (69/125): Changes in 1/433 machines found.
2024-02-28 00:01:02 INFO 0/5: Found machine to be added: François Grimaldi - Il Malizia
2024-02-28 00:01:07 INFO 4/5: Found machine to be added: Souvenirs Shop Monaco
2024-02-28 00:01:07 INFO Location Principality of Monaco (102/125): Changes in 2/5 machines found.
2024-02-28 00:06:36 INFO Tourist Shop on Huanhe Road is currently unavailable
2024-02-28 00:06:41 INFO 26/44: Found machine to be added: Anping Tree House / Former Tait & Co. Merchant House
2024-02-28 00:06:43 INFO 27/44: Found machine to be added: Hayashi Department Store
2024-02-28 00:06:45 INFO 28/44: Found machine to be added: Souvenir shop located near Sicao Green Tunnel 
2024-02-28 00:06:59 INFO Location Taiwan (118/125): Changes in 4/44 machines found.
2024-02-28 00:08:07 INFO 
 Result: 9 changes, 7 new machines found and 2 machines retired
2024-02-28 00:22:08 ERROR Found 5 problems that require manual intervention
2024-02-28 00:22:08 INFO ======Location differ completed at 2024-02-28 00:22:08=======
2024-02-28 00:22:09 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-02-28 22:30:02 INFO ======Location differ joblog from 2024-02-28 22:30:02=======
2024-02-28 22:50:18 INFO Cabela's is available again
2024-02-28 22:52:16 INFO Location Michigan (13/125): Changes in 1/189 machines found.
2024-02-28 23:05:44 INFO 286/381: Found machine to be added: Casa Loma
2024-02-28 23:06:40 INFO Location Florida (24/125): Changes in 1/381 machines found.
2024-02-28 23:16:22 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-02-29 00:07:59 INFO 
 Result: 2 changes, 2 new machines found and 0 machines retired
2024-02-29 00:21:53 ERROR Found 5 problems that require manual intervention
2024-02-29 00:21:53 INFO ======Location differ completed at 2024-02-29 00:21:53=======
2024-02-29 00:21:54 INFO Detected change in server_locations.json - push to github

**Review by jannisborn — APPROVED** [review]

**Comment by NinaWie** [comment]
New machine 7071 named Brienz Lake Quai submitted.

**Pull request merged**
