### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 2383 "Silver Mall (formerly Silver Sun)":
	Status from: available to: out-of-order

### CODE REVIEW

**Comment by NinaWie** [comment]
New machine 7377 named Brüder Grimm Märchenfestspiele submitted.

**Comment by jannisborn** [comment]
2024-08-08 22:30:01 INFO ======Location differ joblog from 2024-08-08 22:30:01=======
2024-08-08 22:36:38 INFO 31/68: Found machine to be added: Cobblestone Creamery 
2024-08-08 22:37:10 INFO Location Oklahoma (5/125): Changes in 1/68 machines found.
2024-08-08 22:47:28 INFO 158/215: Found machine to be added: Acrisure Stadium
2024-08-08 22:48:08 INFO Location Pennsylvania (11/125): Changes in 1/215 machines found.
2024-08-08 23:03:54 INFO Itasca State Park is currently unavailable
2024-08-08 23:04:24 INFO Location Minnesota (16/125): Changes in 1/106 machines found.
2024-08-09 00:05:52 INFO 7/392: Found machine to be added: Aschaffenburg Information Center 
2024-08-09 00:12:33 INFO Location Germany (73/125): Changes in 1/392 machines found.
2024-08-09 00:32:39 INFO 24/27: Found machine to be added: Sunnegga Train Station
2024-08-09 00:32:41 INFO Location Switzerland (117/125): Changes in 1/27 machines found.
2024-08-09 00:34:44 INFO 
 Result: 5 changes, 4 new machines found and 1 machines retired
2024-08-09 00:51:32 ERROR Found 3 problems that require manual intervention
2024-08-09 00:51:32 INFO ======Location differ completed at 2024-08-09 00:51:32=======
2024-08-09 00:51:34 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-08-09 22:30:02 INFO ======Location differ joblog from 2024-08-09 22:30:02=======
2024-08-09 22:43:25 INFO 33/56: Found machine to be added: Clinton Presidential Center
2024-08-09 22:43:41 INFO Location Arkansas (9/125): Changes in 1/56 machines found.
2024-08-09 23:52:19 INFO 57/60: Found machine to be added: Wörschach
2024-08-09 23:52:21 INFO Location Austria (54/125): Changes in 1/60 machines found.
2024-08-09 23:53:50 INFO End of the Thread Cafe is currently unavailable
2024-08-09 23:54:56 INFO Location Canada (61/125): Changes in 1/148 machines found.
2024-08-10 00:22:17 INFO 6/15: Found machine to be added: The Archeological Museum of Krakow
2024-08-10 00:22:24 INFO 12/15: Found machine to be added: Gubalówka Funicular Railway
2024-08-10 00:22:26 INFO Location Poland (100/125): Changes in 2/15 machines found.
2024-08-10 00:24:42 INFO Seems that machine Nelson Monument already exists as: Nelson’s Monument
2024-08-10 00:24:45 INFO The Scott Monument is currently unavailable
2024-08-10 00:25:12 INFO Location Scotland (2667/125): Changes in 1/94 machines found.
2024-08-10 00:31:33 INFO 
 Result: 6 changes, 4 new machines found and 2 machines retired
2024-08-10 00:48:50 ERROR Found 3 problems that require manual intervention
2024-08-10 00:48:50 INFO ======Location differ completed at 2024-08-10 00:48:50=======
2024-08-10 00:48:52 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7386 named Propststraße submitted.

**Comment by NinaWie** [comment]
New machine 7387 named Kings Cross train station submitted.

**Comment by NinaWie** [comment]
New machine 7388 named House of Blues submitted.

**Comment by NinaWie** [comment]
New machine 7389 named Goofy’s Candy submitted.

**Comment by NinaWie** [comment]
New machine 7390 named Art Corner submitted.

**Comment by jannisborn** [comment]
2024-08-10 22:30:01 INFO ======Location differ joblog from 2024-08-10 22:30:01=======
2024-08-10 22:46:19 INFO 93/216: Found machine to be added: Raystown Lake Welcome Center
2024-08-10 22:47:54 INFO Location Pennsylvania (11/125): Changes in 1/216 machines found.
2024-08-10 23:07:55 INFO 69/179: Found machine to be added: Grand River Historical Society & Museum
2024-08-10 23:09:23 INFO Location Missouri (22/125): Changes in 1/179 machines found.
2024-08-10 23:46:05 INFO Louisville Zoo is currently unavailable
2024-08-10 23:46:19 INFO Location Kentucky (48/125): Changes in 1/63 machines found.
2024-08-11 00:26:47 INFO 
 Result: 3 changes, 2 new machines found and 1 machines retired
2024-08-11 00:43:04 ERROR Found 3 problems that require manual intervention
2024-08-11 00:43:04 INFO ======Location differ completed at 2024-08-11 00:43:04=======
2024-08-11 00:43:05 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7393 named Rainforest Cafe submitted.

**Comment by jannisborn** [comment]
2024-08-11 22:30:02 INFO ======Location differ joblog from 2024-08-11 22:30:02=======
2024-08-11 23:04:17 INFO 61/105: Found machine to be added: Broadway Grand Prix
2024-08-11 23:04:43 INFO Location South Carolina (17/125): Changes in 1/105 machines found.
2024-08-12 00:26:01 INFO 120/183: Found machine to be added: Pontevedra, Albergues Virxe Peregrina
2024-08-12 00:26:55 INFO Location Spain (112/125): Changes in 1/183 machines found.
2024-08-12 00:29:47 INFO 
 Result: 2 changes, 2 new machines found and 0 machines retired
2024-08-12 00:46:52 ERROR Found 3 problems that require manual intervention
2024-08-12 00:46:52 INFO ======Location differ completed at 2024-08-12 00:46:52=======
2024-08-12 00:46:53 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-08-12 22:30:02 INFO ======Location differ joblog from 2024-08-12 22:30:02=======
2024-08-12 23:28:51 INFO Griffin Museum of Science + Industry (Museum of Science & Industry, MSI is available again
2024-08-12 23:29:59 INFO Location Illinois (36/125): Changes in 1/139 machines found.
2024-08-13 00:24:38 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-08-13 00:42:21 ERROR Found 3 problems that require manual intervention
2024-08-13 00:42:21 INFO ======Location differ completed at 2024-08-13 00:42:21=======
2024-08-13 00:42:22 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7396 named Jerry’s Rogue Jets Gift Shop submitted.

**Comment by jannisborn** [comment]
2024-08-13 22:30:02 INFO ======Location differ joblog from 2024-08-13 22:30:02=======
2024-08-13 22:41:01 INFO 50/133: Found machine to be added: Wildlife Images
2024-08-13 22:41:55 INFO Location Oregon (8/125): Changes in 1/133 machines found.
2024-08-14 00:13:06 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-08-14 00:29:37 ERROR Found 3 problems that require manual intervention
2024-08-14 00:29:37 INFO ======Location differ completed at 2024-08-14 00:29:37=======
2024-08-14 00:29:38 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-08-14 22:30:02 INFO ======Location differ joblog from 2024-08-14 22:30:02=======
2024-08-14 22:45:23 INFO 216/217: Found machine to be added: Yorktown Hotel
2024-08-14 22:45:23 INFO Location Pennsylvania (11/125): Changes in 1/217 machines found.
2024-08-14 23:03:51 INFO Sunshine T-Shirt and Souvenirs is currently unavailable
2024-08-14 23:04:25 INFO 99/180: Found machine to be added: Joplin History and Mineral Museum
2024-08-14 23:05:34 INFO Location Missouri (22/125): Changes in 2/180 machines found.
2024-08-14 23:16:14 INFO Baylor Bear Habitat  is available again
2024-08-14 23:16:22 INFO Location Texas (26/125): Changes in 1/304 machines found.
2024-08-14 23:26:58 INFO Located somewhere in Historic Smithville is currently unavailable
2024-08-14 23:27:05 INFO Location New Jersey (37/125): Changes in 1/99 machines found.
2024-08-14 23:33:21 INFO 10/39: Found machine to be added: Capital Market
2024-08-14 23:33:38 INFO Location West Virginia (44/125): Changes in 1/39 machines found.
2024-08-15 00:08:26 INFO 66/75: Found machine to be added: Marina Souvenirs
2024-08-15 00:08:33 INFO Location Portugal (101/125): Changes in 1/75 machines found.
2024-08-15 00:09:27 INFO Camera Obscura  is currently unavailable
2024-08-15 00:10:06 INFO Location Scotland (107/125): Changes in 1/94 machines found.
2024-08-15 00:16:04 INFO 
 Result: 8 changes, 5 new machines found and 3 machines retired
2024-08-15 00:32:27 ERROR Found 3 problems that require manual intervention
2024-08-15 00:32:27 INFO ======Location differ completed at 2024-08-15 00:32:27=======
2024-08-15 00:32:28 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-08-15 22:30:01 INFO ======Location differ joblog from 2024-08-15 22:30:01=======
2024-08-15 22:43:18 INFO 13/92: Found machine to be added: Old South Meeting House
2024-08-15 22:43:57 INFO Legoland Discovery Center is currently unavailable
2024-08-15 22:44:12 INFO Location Massachusetts (10/125): Changes in 2/92 machines found.
2024-08-16 00:02:12 INFO Edicola Pantheon (Newspaper kiosk) is available again
2024-08-16 00:02:35 INFO Location Italy (82/125): Changes in 1/142 machines found.
2024-08-16 00:18:29 INFO 
 Result: 3 changes, 2 new machines found and 1 machines retired
2024-08-16 00:34:45 ERROR Our machine News kiosk in Italy from Server shown as available but http://209.221.138.252/Details.aspx?location=432242 responds Internal Server Error (500)
2024-08-16 00:34:47 ERROR Found 3 problems that require manual intervention
2024-08-16 00:34:47 INFO ======Location differ completed at 2024-08-16 00:34:47=======
2024-08-16 00:34:48 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7403 named Mainz Tourist Information submitted.

**Comment by jannisborn** [comment]
2024-08-16 22:30:02 INFO ======Location differ joblog from 2024-08-16 22:30:02=======
2024-08-16 22:46:13 INFO 124/218: Found machine to be added: Meyersdale Area Historical Society
2024-08-16 22:47:27 INFO Location Pennsylvania (11/125): Changes in 1/218 machines found.
2024-08-17 00:11:26 INFO 20/31: Found machine to be added: Zoológico de Chapultepec 
2024-08-17 00:11:33 INFO Location Mexico (93/125): Changes in 1/31 machines found.
2024-08-17 00:16:38 INFO Nevis Range, Fort William is available again
2024-08-17 00:17:05 INFO Location Scotland (107/125): Changes in 1/94 machines found.
2024-08-17 00:23:03 INFO 
 Result: 3 changes, 3 new machines found and 0 machines retired
2024-08-17 00:33:46 ERROR Our machine Fishing Bridge General Store in Montana from Device shown as available but http://209.221.138.252/Details.aspx?location=320044 responds Internal Server Error (500)
2024-08-17 00:33:47 ERROR Our machine Yellowstone - Canyon Village General Store in Wyoming from Server shown as available but http://209.221.138.252/Details.aspx?location=833 responds Internal Server Error (500)
2024-08-17 00:39:35 ERROR Found 3 problems that require manual intervention
2024-08-17 00:39:35 INFO ======Location differ completed at 2024-08-17 00:39:35=======
2024-08-17 00:39:36 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7406 named Naturwildpark Freisen submitted.

**Comment by NinaWie** [comment]
New machine 7407 named Schiffsanlegestelle Saarburg submitted.

**Comment by jannisborn** [comment]
2024-08-17 22:30:02 INFO ======Location differ joblog from 2024-08-17 22:30:02=======
2024-08-17 22:38:01 INFO John Wesley Powell Memorial Museum is currently unavailable
2024-08-17 22:39:37 INFO Location Arizona (6/125): Changes in 1/224 machines found.
2024-08-17 22:56:03 INFO Breck 'N' Boujee  is currently unavailable
2024-08-17 22:58:22 INFO Location Colorado (15/125): Changes in 1/220 machines found.
2024-08-17 23:21:56 INFO Primm Valley Resort & Casino is currently unavailable
2024-08-17 23:22:09 INFO Location Nevada (31/125): Changes in 1/206 machines found.
2024-08-17 23:31:01 ERROR Geolocation failed for: Mahanay Memorial Carillon Tower	 sub: 100 E. Lincoln Way, Jefferson
2024-08-17 23:47:27 INFO 351/444: Found machine to be added: Fishermans Cottage 
2024-08-17 23:48:27 INFO Location England (69/125): Changes in 1/444 machines found.
2024-08-18 00:11:40 INFO Distance match - Seeems that machine Souvenir store near the Cathedral  at Pl. Mayor, 9, 16001 Cuenca, Cuenca already exists as: Artesana shop
2024-08-18 00:16:00 INFO 
 Result: 4 changes, 1 new machines found and 3 machines retired
2024-08-18 00:32:23 ERROR Found 4 problems that require manual intervention
2024-08-18 00:32:23 INFO ======Location differ completed at 2024-08-18 00:32:23=======
2024-08-18 00:32:24 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
New problems require attention.

**Comment by NinaWie** [comment]
New machine 7409 named Buc-ee’s - Sevierville, TN submitted.

**Comment by NinaWie** [comment]
New machine 7410 named Altazimuth pavilion submitted.

**Comment by NinaWie** [comment]
New machine 7411 named Eilean Donan Castle submitted.

**Comment by NinaWie** [comment]
New machine 7412 named Colors Souvenirs - The Plaza Shopping Centre submitted.

**Comment by NinaWie** [comment]
New machine 7413 named Sealife Paris submitted.

**Comment by NinaWie** [comment]
New machine 7414 named Portaal van vlaanderen submitted.

**Comment by NinaWie** [comment]
New machine 7415 named Het lage licht submitted.

**Review by jannisborn — APPROVED** [review]

**Pull request merged**
