### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 2631 "Desert View Trading Post":
	Status from: available to: out-of-order

### CODE REVIEW

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
2024-04-02 22:30:01 INFO ======Location differ joblog from 2024-04-02 22:30:01=======
2024-04-02 22:57:17 INFO USS Natilus / Submarine Force Museum is available again
2024-04-02 22:57:27 INFO Location Connecticut (18/125): Changes in 1/26 machines found.
2024-04-02 23:16:52 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-04-03 00:08:48 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-04-03 00:23:25 ERROR Found 4 problems that require manual intervention
2024-04-03 00:23:25 INFO ======Location differ completed at 2024-04-03 00:23:25=======
2024-04-03 00:23:26 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-04-03 22:30:01 INFO ======Location differ joblog from 2024-04-03 22:30:01=======
2024-04-03 22:34:38 INFO 19/64: Found machine to be added: Chickasaw Nation Welcome Center
2024-04-03 22:35:11 INFO Location Oklahoma (5/125): Changes in 1/64 machines found.
2024-04-03 23:16:31 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-04-03 23:45:51 INFO Seeems that machine Holy Moly Store at Münsterplatz 8, Freiburg im Breisgau already exists as: Münsterplatz 16, Freiburg im Breisgau
2024-04-04 00:08:41 INFO Baiyoke Sky Hotel is currently unavailable
2024-04-04 00:08:59 INFO Location Thailand (119/125): Changes in 1/15 machines found.
2024-04-04 00:10:37 INFO 
 Result: 2 changes, 1 new machines found and 1 machines retired
2024-04-04 00:25:47 ERROR Found 4 problems that require manual intervention
2024-04-04 00:25:47 INFO ======Location differ completed at 2024-04-04 00:25:47=======
2024-04-04 00:25:47 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-04-04 22:30:02 INFO ======Location differ joblog from 2024-04-04 22:30:02=======
2024-04-04 22:34:39 INFO 20/65: Found machine to be added: Chickasaw Nation Welcome Center 
2024-04-04 22:35:13 INFO Location Oklahoma (5/125): Changes in 1/65 machines found.
2024-04-04 23:04:55 INFO 152/383: Found machine to be added: Walt Disney World, Disney Springs, Marketplace, Star Wars Trading Post
2024-04-04 23:06:15 INFO 281/383: Found machine to be added: Walt Disney World Store on International Drive
2024-04-04 23:07:15 INFO Location Florida (24/125): Changes in 2/383 machines found.
2024-04-04 23:09:56 INFO 169/297: Found machine to be added: Caddo Lake State Park
2024-04-04 23:11:26 INFO Location Texas (26/125): Changes in 1/297 machines found.
2024-04-04 23:17:00 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-04-04 23:22:07 INFO Cloud Nine Gifts and Souvenirs is currently unavailable
2024-04-04 23:22:54 INFO Location Washington (38/125): Changes in 1/129 machines found.
2024-04-04 23:39:29 INFO Red Funnel Ferries Southampton - Isle of Wight  is currently unavailable
2024-04-04 23:42:24 INFO Location England (69/125): Changes in 1/436 machines found.
2024-04-05 00:08:45 INFO 
 Result: 6 changes, 4 new machines found and 2 machines retired
2024-04-05 00:23:23 ERROR Found 4 problems that require manual intervention
2024-04-05 00:23:23 INFO ======Location differ completed at 2024-04-05 00:23:23=======
2024-04-05 00:23:23 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7127 named Trail in Birston submitted.

**Comment by jannisborn** [comment]
2024-04-05 22:30:01 INFO ======Location differ joblog from 2024-04-05 22:30:01=======
2024-04-05 23:17:00 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-04-05 23:24:35 INFO 60/92: Found machine to be added: Aspen Copies & Office Supplies
2024-04-05 23:24:57 INFO Location New Mexico (40/125): Changes in 1/92 machines found.
2024-04-06 00:08:40 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-04-06 00:23:15 ERROR Found 4 problems that require manual intervention
2024-04-06 00:23:15 INFO ======Location differ completed at 2024-04-06 00:23:15=======
2024-04-06 00:23:15 INFO Detected change in server_locations.json - push to github

**Review by jannisborn — APPROVED** [review]

**Pull request merged**
