### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 6257 "Rest Area 69, W Virginia Tpke,":
	 Location from: 54.3896, -3.3242 to: 38.1134, -81.4453

### CODE REVIEW

**Comment by jannisborn** [comment]
2024-07-22 22:30:01 INFO ======Location differ joblog from 2024-07-22 22:30:01=======
2024-07-22 22:46:43 INFO Seeems that machine Strip District Terminal already exists as: Strip District Terminal Building
2024-07-22 23:22:20 INFO 69/99: Found machine to be added: National History Museum of Utah
2024-07-22 23:22:37 INFO Location Utah (29/125): Changes in 1/99 machines found.
2024-07-23 00:18:29 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-07-23 00:25:29 ERROR Our machine Pizza Madness in Colorado from Device shown as available but http://209.221.138.252/Details.aspx?location=278089 responds Internal Server Error (500)
2024-07-23 00:34:14 ERROR Found 3 problems that require manual intervention
2024-07-23 00:34:14 INFO ======Location differ completed at 2024-07-23 00:34:14=======
2024-07-23 00:34:15 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-07-23 22:30:02 INFO ======Location differ joblog from 2024-07-23 22:30:02=======
2024-07-23 22:49:36 INFO 231/759: Found machine to be added: Pelican Pier
2024-07-23 22:54:29 INFO Location California (12/125): Changes in 1/759 machines found.
2024-07-23 22:56:26 INFO 129/194: Found machine to be added: Silver Town Mini Golf
2024-07-23 22:57:19 INFO Location Michigan (13/125): Changes in 1/194 machines found.
2024-07-23 23:07:50 INFO Gatlinburg Welcome Center is available again
2024-07-23 23:09:52 INFO Location Tennessee (23/125): Changes in 1/199 machines found.
2024-07-23 23:24:29 INFO Distance match - Seeems that machine Harvey's Lake Tahoe at P.O. Box 128, 18 Highway 50, Lake Tahoe already exists as: Harvey’s hotel casino resort
2024-07-23 23:54:50 INFO 32/107: Found machine to be added: Office de Tourisme de Maisons - Laffitte
2024-07-23 23:56:00 INFO Location France (72/125): Changes in 1/107 machines found.
2024-07-24 00:04:42 INFO Carrolls Irish gift shop is available again
2024-07-24 00:04:55 INFO Location Ireland (80/125): Changes in 1/42 machines found.
2024-07-24 00:22:27 INFO 
 Result: 5 changes, 5 new machines found and 0 machines retired
2024-07-24 00:38:25 ERROR Our machine Fish Connection  in Alaska from Server shown as available but http://209.221.138.252/Details.aspx?location=434940 responds Internal Server Error (500)
2024-07-24 00:38:26 ERROR Our machine Fish Connection  in Alaska from Server shown as available but http://209.221.138.252/Details.aspx?location=434958 responds Internal Server Error (500)
2024-07-24 00:38:26 ERROR Found 3 problems that require manual intervention
2024-07-24 00:38:26 INFO ======Location differ completed at 2024-07-24 00:38:26=======
2024-07-24 00:38:27 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
2024-07-25 22:30:02 INFO ======Location differ joblog from 2024-07-25 22:30:02=======
2024-07-25 22:34:41 INFO 42/68: Found machine to be added: Santa Claus House North Pole
2024-07-25 22:35:04 INFO Location Alaska (3/125): Changes in 1/68 machines found.
2024-07-25 22:42:45 INFO Hot Springs Mountain Tower is currently unavailable
2024-07-25 22:43:10 INFO Location Arkansas (9/125): Changes in 1/55 machines found.
2024-07-25 22:45:08 INFO 48/212: Found machine to be added: Waldameer Park & Waterworld
2024-07-25 22:47:12 INFO Location Pennsylvania (11/125): Changes in 1/212 machines found.
2024-07-25 22:53:26 INFO Winchester Mystery House is available again
2024-07-25 22:55:04 INFO Location California (12/125): Changes in 1/759 machines found.
2024-07-25 23:11:32 INFO Jaxson's Ice Cream Parlor is currently unavailable
2024-07-25 23:16:07 INFO Location Florida (24/125): Changes in 1/387 machines found.
2024-07-25 23:24:06 INFO 27/100: Found machine to be added: Fish Lake Lodge General Store
2024-07-25 23:25:04 INFO Location Utah (29/125): Changes in 1/100 machines found.
2024-07-25 23:29:18 INFO 32/39: Found machine to be added: Drake Field
2024-07-25 23:29:24 INFO Location New Hampshire (34/125): Changes in 1/39 machines found.
2024-07-25 23:39:54 INFO Harpers Ferry NHS - The Hodge Podge is currently unavailable
2024-07-25 23:40:09 INFO Location West Virginia (44/125): Changes in 1/38 machines found.
2024-07-25 23:45:07 INFO 6/55: Found machine to be added: Little Americas Cheyenne Gas Station
2024-07-25 23:45:47 INFO Location Wyoming (50/125): Changes in 1/55 machines found.
2024-07-25 23:57:01 INFO 20/108: Found machine to be added: Normandie - Etretat
2024-07-25 23:58:31 INFO Location France (72/125): Changes in 1/108 machines found.
2024-07-26 00:24:23 INFO 
 Result: 10 changes, 7 new machines found and 3 machines retired
2024-07-26 00:40:23 ERROR Found 3 problems that require manual intervention
2024-07-26 00:40:23 INFO ======Location differ completed at 2024-07-26 00:40:23=======
2024-07-26 00:40:24 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7329 named Legoland submitted.

**Comment by jannisborn** [comment]
2024-07-26 22:30:01 INFO ======Location differ joblog from 2024-07-26 22:30:01=======
2024-07-27 00:16:52 INFO 134/148: Found machine to be added: Gevangenismuseum Veenhuizen
2024-07-27 00:16:59 INFO Location Netherlands (94/125): Changes in 1/148 machines found.
2024-07-27 00:21:57 INFO 42/176: Found machine to be added: Campo de Criptana Windmills
2024-07-27 00:23:11 INFO 129/176: Found machine to be added: Monte Igueldo Amusement Park
2024-07-27 00:23:50 INFO Location Spain (112/125): Changes in 2/176 machines found.
2024-07-27 00:26:20 INFO 
 Result: 3 changes, 3 new machines found and 0 machines retired
2024-07-27 00:42:52 ERROR Found 3 problems that require manual intervention
2024-07-27 00:42:52 INFO ======Location differ completed at 2024-07-27 00:42:52=======
2024-07-27 00:42:52 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7333 named Beef Jerky Outlet submitted.

**Comment by NinaWie** [comment]
New machine 7334 named Adlerwarte Berlebeck submitted.

**Comment by NinaWie** [comment]
New machine 7335 named Adlerwarte submitted.

**Comment by NinaWie** [comment]
New machine 7336 named Basilika Mariazell submitted.

**Comment by NinaWie** [comment]
New machine 7337 named Eybl Jet submitted.

**Comment by jannisborn** [comment]
2024-07-27 22:30:01 INFO ======Location differ joblog from 2024-07-27 22:30:01=======
2024-07-27 23:11:01 INFO Beef Jerky Outlet Pigeon Forge is currently unavailable
2024-07-27 23:11:41 INFO Location Tennessee (23/125): Changes in 1/199 machines found.
2024-07-28 00:16:17 INFO 28/30: Found machine to be added: Iglesia de Santa Prisca
2024-07-28 00:16:17 INFO Location Mexico (93/125): Changes in 1/30 machines found.
2024-07-28 00:28:18 INFO 
 Result: 2 changes, 1 new machines found and 1 machines retired
2024-07-28 00:47:00 ERROR Found 3 problems that require manual intervention
2024-07-28 00:47:00 INFO ======Location differ completed at 2024-07-28 00:47:00=======
2024-07-28 00:47:01 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7339 named Niagara Wax Museum submitted.

**Comment by NinaWie** [comment]
New machine 7340 named Pfänderbahn Bergstation 1 submitted.

**Comment by NinaWie** [comment]
New machine 7341 named Pfänderbahn Bergstation - Machine 2 submitted.

**Review by jannisborn — APPROVED** [review]

**Comment by NinaWie** [comment]
New machine 7342 named Disney Springs stage submitted.

**Comment by NinaWie** [comment]
New machine 7343 named Disney Springs Food court submitted.

**Comment by NinaWie** [comment]
New machine 7344 named Adlerwarte submitted.

**Pull request merged**
