### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 1452 "Coronation Street Tour":
	Status from: available to: retired

### CODE REVIEW

**Comment by jannisborn** [comment]
No website updates today!

**Comment by NinaWie** [comment]
New machine 7639 named Caniço Supermercado submitted.

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
No website updates today!

**Comment by NinaWie** [comment]
New machine 7640 named Funchal Porto submitted.

**Comment by NinaWie** [comment]
New machine 7641 named Penny machine submitted.

**Comment by jannisborn** [comment]
2024-11-14 22:30:02 INFO ======Location differ joblog from 2024-11-14 22:30:02=======
2024-11-14 23:16:45 INFO Downtown Las Vegas - Golden Nugget Hotel Casino is available again
2024-11-14 23:19:51 INFO Robins Nature and Visitor Center at Maymont (in Virginia) is currently unavailable
2024-11-14 23:33:30 INFO 5/19: Found machine to be added: West Acres Mall - Legacy Toys' in North Dakota
2024-11-14 23:34:21 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-11-14 23:40:02 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-11-15 00:12:01 INFO 
 Result: 3 changes, 2 new machines found and 1 machines retired
2024-11-15 00:26:53 ERROR Found 8 problems that require manual intervention
2024-11-15 00:26:53 INFO ======Location differ completed at 2024-11-15 00:26:53=======
2024-11-15 00:26:54 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7643 named Madeira - Cabo Girão Skywalk submitted.

**Comment by jannisborn** [comment]
2024-11-15 22:30:02 INFO ======Location differ joblog from 2024-11-15 22:30:02=======
2024-11-15 23:34:28 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-11-15 23:40:01 INFO Flambards Experience (in England) is currently unavailable
2024-11-15 23:40:09 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-11-15 23:58:29 INFO Snoopy Town Shop Kichijoji (in Japan) is currently unavailable
2024-11-16 00:07:17 INFO 5/192: Found machine to be added: Plaça de Bous d'Alacant in Spain
2024-11-16 00:12:18 INFO 
 Result: 3 changes, 1 new machines found and 2 machines retired
2024-11-16 00:27:20 ERROR Found 8 problems that require manual intervention
2024-11-16 00:27:20 INFO ======Location differ completed at 2024-11-16 00:27:20=======
2024-11-16 00:27:21 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-11-16 22:30:02 INFO ======Location differ joblog from 2024-11-16 22:30:02=======
2024-11-16 22:47:55 INFO Balboa Park - Balboa Park Visitors Center is available again
2024-11-16 22:48:00 INFO Balboa Park - San Diego Comic-Con Museum is available again
2024-11-16 23:33:25 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-11-16 23:39:01 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-11-17 00:10:45 INFO 
 Result: 2 changes, 2 new machines found and 0 machines retired
2024-11-17 00:25:32 ERROR Found 8 problems that require manual intervention
2024-11-17 00:25:33 INFO ======Location differ completed at 2024-11-17 00:25:33=======
2024-11-17 00:25:33 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-11-17 22:30:02 INFO ======Location differ joblog from 2024-11-17 22:30:02=======
2024-11-17 23:25:54 INFO 8/43: Found machine to be added: All American Bullion and coins in Iowa
2024-11-17 23:33:48 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-11-17 23:39:29 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-11-18 00:11:03 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-11-18 00:25:45 ERROR Found 8 problems that require manual intervention
2024-11-18 00:25:45 INFO ======Location differ completed at 2024-11-18 00:25:45=======
2024-11-18 00:25:46 INFO Detected change in server_locations.json - push to github

**Review by jannisborn — APPROVED** [review]
LGTM

**Comment by jannisborn** [comment]
2024-11-18 22:30:01 INFO ======Location differ joblog from 2024-11-18 22:30:01=======
2024-11-18 23:34:31 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-11-18 23:36:55 INFO 12/26: Found machine to be added: Belgian Heritage store in Belgium
2024-11-18 23:40:11 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-11-18 23:54:34 INFO Bar Tabacchi / Caffè Melloni  is available again
2024-11-19 00:08:14 INFO Seeems that machine Restaurante El Kiosko at Parque Ardales, Pantano El Chorro, s/n, Ardales, Málaga already exists as: Parque Ardales, Pantano El Chorro, s/n, 29550 Ardales, Málaga, Ardales
2024-11-19 00:12:07 INFO 
 Result: 2 changes, 2 new machines found and 0 machines retired
2024-11-19 00:26:47 ERROR Found 8 problems that require manual intervention
2024-11-19 00:26:47 INFO ======Location differ completed at 2024-11-19 00:26:47=======
2024-11-19 00:26:48 INFO Detected change in server_locations.json - push to github

**Pull request merged**
