### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 3804 "Sea Turtle Inc.":
	Status from: available to: out-of-order

### CODE REVIEW

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
2024-11-20 22:30:01 INFO ======Location differ joblog from 2024-11-20 22:30:01=======
2024-11-20 23:33:31 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-11-20 23:39:06 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-11-20 23:59:25 INFO 27/32: Found machine to be added: Ex-Hacienda de Chautla  in Mexico
2024-11-21 00:11:03 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-11-21 00:25:58 ERROR Found 8 problems that require manual intervention
2024-11-21 00:25:58 INFO ======Location differ completed at 2024-11-21 00:25:58=======
2024-11-21 00:25:59 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
No website updates today!

**Comment by NinaWie** [comment]
New machine 7649 named Dinosaur World submitted.

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
2024-11-24 22:30:02 INFO ======Location differ joblog from 2024-11-24 22:30:02=======
2024-11-24 23:34:22 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-11-24 23:37:15 INFO 10/11: Found machine to be added: Baba Vida Castle in Bulgaria
2024-11-24 23:38:08 INFO Rainforest Cafe is available again
2024-11-24 23:40:07 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-11-24 23:50:56 INFO 336/403: Found machine to be added: Sigmaringen Castle in Germany
2024-11-24 23:50:58 INFO 337/403: Found machine to be added: Tourist information in Germany
2024-11-25 00:11:02 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-11-25 00:11:02 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-11-25 00:11:51 INFO The Columbus Foundation, British Virgin Islands,  Nina (Replica) (in US Virgin Islands) is currently unavailable
2024-11-25 00:12:15 INFO 
 Result: 5 changes, 4 new machines found and 1 machines retired
2024-11-25 00:27:11 ERROR Found 9 problems that require manual intervention
2024-11-25 00:27:11 INFO ======Location differ completed at 2024-11-25 00:27:11=======
2024-11-25 00:27:12 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
New problems require attention.

**Comment by jannisborn** [comment]
2024-11-25 22:30:01 INFO ======Location differ joblog from 2024-11-25 22:30:01=======
2024-11-25 23:12:11 INFO 309/312: Found machine to be added: Ranch Road Gift in Texas
2024-11-25 23:34:19 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-11-25 23:40:02 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-11-26 00:11:04 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-11-26 00:11:04 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-11-26 00:12:20 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-11-26 00:27:15 ERROR Found 9 problems that require manual intervention
2024-11-26 00:27:15 INFO ======Location differ completed at 2024-11-26 00:27:15=======
2024-11-26 00:27:16 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-11-26 22:30:01 INFO ======Location differ joblog from 2024-11-26 22:30:01=======
2024-11-26 23:34:14 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-11-26 23:39:56 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-11-26 23:52:34 INFO Buda Castle Funicular is available again
2024-11-26 23:57:19 INFO 103/226: Found machine to be added: Henn Na Hotel Tokyo Nishikasai in Japan
2024-11-27 00:08:22 INFO From Madrid with Love (in Spain) is currently unavailable
2024-11-27 00:08:26 INFO 107/194: Found machine to be added: Restaurante Arrabal in Spain
2024-11-27 00:10:56 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-11-27 00:10:56 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-11-27 00:12:09 INFO 
 Result: 4 changes, 3 new machines found and 1 machines retired
2024-11-27 00:27:02 ERROR Found 9 problems that require manual intervention
2024-11-27 00:27:02 INFO ======Location differ completed at 2024-11-27 00:27:02=======
2024-11-27 00:27:03 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7656 named Minnesota Symbols submitted.

**Comment by NinaWie** [comment]
New machine 7657 named Manta Seaworld submitted.

**Comment by jannisborn** [comment]
2024-11-27 22:30:01 INFO ======Location differ joblog from 2024-11-27 22:30:01=======
2024-11-27 23:02:03 INFO 41/203: Found machine to be added: Gatlinburg SkyPark in Tennessee
2024-11-27 23:22:08 INFO 41/100: Found machine to be added: NorthlandZ in New Jersey
2024-11-27 23:34:25 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-11-27 23:36:03 INFO 32/63: Found machine to be added: Rdzeniewski - Amber Shop in Austria
2024-11-27 23:40:09 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-11-27 23:45:14 INFO 43/112: Found machine to be added: Hard Rock Cafe, Nice in France
2024-11-28 00:11:10 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-11-28 00:11:10 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-11-28 00:12:23 INFO 
 Result: 4 changes, 4 new machines found and 0 machines retired
2024-11-28 00:27:16 ERROR Found 9 problems that require manual intervention
2024-11-28 00:27:16 INFO ======Location differ completed at 2024-11-28 00:27:16=======
2024-11-28 00:27:17 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-11-28 22:30:02 INFO ======Location differ joblog from 2024-11-28 22:30:02=======
2024-11-28 23:24:01 INFO 11/105: Found machine to be added: Carmel Christkindlmarkt  in Indiana
2024-11-28 23:34:16 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-11-28 23:39:59 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-11-29 00:10:56 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-11-29 00:10:56 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-11-29 00:12:08 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-11-29 00:27:00 ERROR Found 9 problems that require manual intervention
2024-11-29 00:27:00 INFO ======Location differ completed at 2024-11-29 00:27:00=======
2024-11-29 00:27:01 INFO Detected change in server_locations.json - push to github

**Review by jannisborn — APPROVED** [review]

**Comment by jannisborn** [comment]
No website updates today!

**Pull request merged**
