### PR TITLE
DEV PR

### PR DESCRIPTION
**Pull request by NinaWie**
Request change to machine 4820 named Golden Gate Park - California Academy of Sciences - Changed address

### CODE REVIEW

**Comment by NinaWie** [comment]
Request change to machine 4549 named Pacific Pinball Museum - Changed status

**Comment by NinaWie** [comment]
Request change to machine 4713 named Children's Fairyland - Changed paywall

**Comment by NinaWie** [comment]
Request change to machine 4820 named Golden Gate Park - California Academy of Sciences - Changed multimachine, address

**Comment by NinaWie** [comment]
Request change to machine 7001 named Burg HülshoffChanged paywall, location

**Comment by NinaWie** [comment]
Request change to machine 711 named Ütliberg Kulm - Changed:
 title to Ütliberg Kulm
 address to: 8143 Zurich, Switzerland
 location to: 47.34956730207685, 8.491602063971897

**Comment by NinaWie** [comment]
Request change to machine 711 named Ütliberg Kulm - Changed:
Machine with pending changes is getting changed *AGAIN*:
 address to: Ütliberg Kulm, 8143 Zurich, Switzerland

**Comment by NinaWie** [comment]
Request change to machine 712 named Wasserkirche (Zürich) - Changed:
 status to: retired
 title to Wasserkirche (Zürich)

**Comment by NinaWie** [comment]
Request change to machine 719 named Interlaken - Changed:
	Title from: Interlaken to: Interlaken
	Address from HÃ¶heweg 35 to: Höheweg 35, Interlaken, Switzerland
	 Location from 46.6859, 7.8563 to: 46.6862, 7.8561

**Comment by NinaWie** [comment]
New machine 7028 named F submitted.

**Comment by NinaWie** [comment]
Request change to machine 6026 named Interlaken Ost (landingpier) - Changed:
	Title from: Interlaken Ost (landingpier) to: Interlaken Ost (landingpier)
	 Paywall from: False to: True

**Comment by NinaWie** [comment]
New machine 7029 named Vielleicht submitted.

**Comment by NinaWie** [comment]
New machine 7030 named Testlauf submitted.

**Comment by NinaWie** [comment]
Request change to machine 716 named Grindelwald First Station - Changed:
	Status from: out-of-order to: out-of-order
	Multimachine from: 1 to: 2

**Comment by NinaWie** [comment]
Request change to machine 518 named 1.FC Köln Fanshop - Changed:
	Status from: available to: available
	Title from: 1.FC Köln Fanshop to: 1.FC Köln Fanshop

**Comment by NinaWie** [comment]
Request change to machine 718 named Mount First - Changed:
	Status from: retired to: available
	 Paywall from: False to: True
	Address from  to: Grindelwald First

**Comment by NinaWie** [comment]
Request change to machine 423 named Begus Souvenirs - Changed:
	 Paywall from: False to: True
	 Location from 52.5116, 13.3766 to: 52.5116, 13.3763

**Comment by NinaWie** [comment]
New machine 7031 named First submitted.

**Comment by NinaWie** [comment]
Request change to machine 428 named In between - Changed:
	Title from: Salvatore Dali exhibition to: In between

**Comment by NinaWie** [comment]
New machine 7032 named Second submitted.

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
No website updates today!

**Comment by NinaWie** [comment]
Request change to machine 440 named Madame Tussauds - Changed:
	Status from: available to: out-of-order

**Comment by NinaWie** [comment]
New machine 7033 named Test submitted.

**Comment by NinaWie** [comment]
New machine 7034 named Jannis submitted.

**Pull request closed without merging**
