### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 1275 "Quechee Gorge Visitor Center":
	 Location from: 43.6445, -72.4249 to: 43.6366, -72.4055

### CODE REVIEW

**Comment by jannisborn** [comment]
2024-05-03 22:30:02 INFO ======Location differ joblog from 2024-05-03 22:30:02=======
2024-05-03 23:00:33 INFO Marlowe's Ribs & Restaurant is available again
2024-05-03 23:01:35 INFO Location Tennessee (23/125): Changes in 1/198 machines found.
2024-05-03 23:14:47 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-05-04 00:04:36 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-05-04 00:19:11 ERROR Found 4 problems that require manual intervention
2024-05-04 00:19:11 INFO ======Location differ completed at 2024-05-04 00:19:11=======
2024-05-04 00:19:12 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-05-04 22:30:01 INFO ======Location differ joblog from 2024-05-04 22:30:01=======
2024-05-04 23:14:55 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-05-04 23:36:04 INFO Brighton Marine Palace and Pier is currently unavailable
2024-05-04 23:39:23 INFO Location England (69/125): Changes in 1/436 machines found.
2024-05-05 00:05:10 INFO 
 Result: 1 changes, 0 new machines found and 1 machines retired
2024-05-05 00:19:43 ERROR Found 4 problems that require manual intervention
2024-05-05 00:19:43 INFO ======Location differ completed at 2024-05-05 00:19:43=======
2024-05-05 00:19:44 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7162 named Split Rock Lighthouse Souvenir Pennys submitted.

**Comment by NinaWie** [comment]
New machine 7163 named Snow arena submitted.

**Comment by jannisborn** [comment]
2024-05-05 22:30:02 INFO ======Location differ joblog from 2024-05-05 22:30:02=======
2024-05-05 23:16:20 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-05-06 00:05:58 INFO Alpamare Wasserpark (Waterpark) got permanently removed
2024-05-06 00:06:06 INFO Location Switzerland (117/125): Changes in 1/24 machines found.
2024-05-06 00:07:55 INFO 
 Result: 1 changes, 0 new machines found and 0 machines retired
2024-05-06 00:10:27 ERROR Our machine Yongkang street market  in Taiwan from Device shown as available but http://209.221.138.252/Details.aspx?location=261260 responds Internal Server Error (500)
2024-05-06 00:18:15 ERROR Our machine Mount First in Switzerland from Server shown as retired but http://209.221.138.252/Details.aspx?location=272929 responds Internal Server Error (500)
2024-05-06 00:22:53 ERROR Found 4 problems that require manual intervention
2024-05-06 00:22:53 INFO ======Location differ completed at 2024-05-06 00:22:53=======
2024-05-06 00:22:54 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
2024-05-07 22:30:01 INFO ======Location differ joblog from 2024-05-07 22:30:01=======
2024-05-07 22:33:39 INFO Tongass Historical Museum is currently unavailable
2024-05-07 22:34:00 INFO Location Alaska (3/125): Changes in 1/68 machines found.
2024-05-07 22:46:25 INFO Destination Camp One Morro Bay is currently unavailable
2024-05-07 22:49:48 INFO Location California (12/125): Changes in 1/752 machines found.
2024-05-07 23:16:15 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-05-07 23:53:43 INFO 97/214: Found machine to be added: Odaiba (????) 
2024-05-07 23:55:10 INFO Location Japan (84/125): Changes in 1/214 machines found.
2024-05-08 00:07:17 INFO 
 Result: 3 changes, 1 new machines found and 2 machines retired
2024-05-08 00:22:09 ERROR Found 4 problems that require manual intervention
2024-05-08 00:22:09 INFO ======Location differ completed at 2024-05-08 00:22:09=======
2024-05-08 00:22:10 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-05-08 22:30:02 INFO ======Location differ joblog from 2024-05-08 22:30:02=======
2024-05-08 22:41:04 INFO Costco is currently unavailable
2024-05-08 22:41:08 INFO Location Oregon (8/125): Changes in 1/130 machines found.
2024-05-08 23:17:24 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-05-08 23:20:57 INFO 112/137: Found machine to be added: Historic Auto Attractions
2024-05-08 23:21:10 INFO Location Illinois (36/125): Changes in 1/137 machines found.
2024-05-08 23:42:45 INFO 407/437: Found machine to be added: Birmingham Library
2024-05-08 23:43:04 INFO Location England (69/125): Changes in 1/437 machines found.
2024-05-08 23:58:54 INFO Hagar qim souvenir shop is currently unavailable
2024-05-08 23:58:57 INFO Location Malta (92/125): Changes in 1/6 machines found.
2024-05-09 00:09:57 INFO 
 Result: 4 changes, 2 new machines found and 2 machines retired
2024-05-09 00:24:55 ERROR Found 4 problems that require manual intervention
2024-05-09 00:24:55 INFO ======Location differ completed at 2024-05-09 00:24:55=======
2024-05-09 00:24:56 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-05-09 22:30:02 INFO ======Location differ joblog from 2024-05-09 22:30:02=======
2024-05-09 23:12:39 INFO 26/98: Found machine to be added: The Jeep Guy Museum
2024-05-09 23:13:24 INFO Location Utah (29/125): Changes in 1/98 machines found.
2024-05-09 23:15:50 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-05-10 00:03:18 INFO 89/173: Found machine to be added: From Madrid with Love
2024-05-10 00:04:25 INFO Location Spain (112/125): Changes in 1/173 machines found.
2024-05-10 00:06:44 INFO 
 Result: 2 changes, 2 new machines found and 0 machines retired
2024-05-10 00:21:45 ERROR Found 4 problems that require manual intervention
2024-05-10 00:21:45 INFO ======Location differ completed at 2024-05-10 00:21:45=======
2024-05-10 00:21:46 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7169 named Boomland submitted.

**Comment by jannisborn** [comment]
2024-05-10 22:30:01 INFO ======Location differ joblog from 2024-05-10 22:30:01=======
2024-05-10 22:48:54 INFO Santa Monica Pier - Bait-Tackle is available again
2024-05-10 22:49:43 INFO Location California (12/125): Changes in 1/752 machines found.
2024-05-10 23:13:10 INFO Utah State Capitol Building is available again
2024-05-10 23:13:23 INFO Location Utah (29/125): Changes in 1/98 machines found.
2024-05-10 23:15:50 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-05-11 00:06:32 INFO 
 Result: 2 changes, 2 new machines found and 0 machines retired
2024-05-11 00:21:29 ERROR Found 4 problems that require manual intervention
2024-05-11 00:21:29 INFO ======Location differ completed at 2024-05-11 00:21:29=======
2024-05-11 00:21:30 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-05-11 22:30:02 INFO ======Location differ joblog from 2024-05-11 22:30:02=======
2024-05-11 23:00:53 INFO Dick's Last Resort  Gatlinburg is currently unavailable
2024-05-11 23:02:36 INFO Location Tennessee (23/125): Changes in 1/198 machines found.
2024-05-11 23:03:08 INFO 44/384: Found machine to be added: Pretty Little Things of DeLand
2024-05-11 23:06:30 INFO Location Florida (24/125): Changes in 1/384 machines found.
2024-05-11 23:16:04 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-05-11 23:42:12 INFO Arenas is available again
2024-05-11 23:43:07 INFO Location France (72/125): Changes in 1/104 machines found.
2024-05-11 23:54:19 INFO 142/214: Found machine to be added: Decks Tokyo Building
2024-05-11 23:55:07 INFO Location Japan (84/125): Changes in 1/214 machines found.
2024-05-12 00:07:18 INFO 
 Result: 4 changes, 3 new machines found and 1 machines retired
2024-05-12 00:22:13 ERROR Found 4 problems that require manual intervention
2024-05-12 00:22:13 INFO ======Location differ completed at 2024-05-12 00:22:13=======
2024-05-12 00:22:14 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-05-12 22:30:01 INFO ======Location differ joblog from 2024-05-12 22:30:01=======
2024-05-12 23:15:52 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-05-12 23:40:22 INFO Shakespeare's Birthplace is currently unavailable
2024-05-12 23:40:46 INFO Location England (69/125): Changes in 1/437 machines found.
2024-05-13 00:06:47 INFO 
 Result: 1 changes, 0 new machines found and 1 machines retired
2024-05-13 00:21:49 ERROR Found 4 problems that require manual intervention
2024-05-13 00:21:49 INFO ======Location differ completed at 2024-05-13 00:21:49=======
2024-05-13 00:21:50 INFO Detected change in server_locations.json - push to github

**Review by jannisborn — APPROVED** [review]

**Pull request merged**
