### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
New machine 7226 named Lefty’s Store submitted.

### CODE REVIEW

**Comment by jannisborn** [comment]
2024-06-21 22:30:02 INFO ======Location differ joblog from 2024-06-21 22:30:02=======
2024-06-21 22:36:57 INFO Superstition Sue Gifts is currently unavailable
2024-06-21 22:37:35 INFO Location Arizona (6/125): Changes in 1/223 machines found.
2024-06-21 22:39:21 INFO 85/130: Found machine to be added: Oaks Park - Skating Rink
2024-06-21 22:39:47 INFO Location Oregon (8/125): Changes in 1/130 machines found.
2024-06-21 23:12:27 INFO Goblin Valley State Park is available again
2024-06-21 23:13:12 INFO Location Utah (29/125): Changes in 1/98 machines found.
2024-06-21 23:24:53 INFO Waterfront Living/ Lake George is currently unavailable
2024-06-21 23:25:52 INFO Location New York (43/125): Changes in 1/201 machines found.
2024-06-21 23:50:37 INFO 67/140: Found machine to be added: Nilogi Souvenir Shop 
2024-06-21 23:51:09 INFO 115/140: Found machine to be added: News kiosk
2024-06-21 23:51:25 INFO Location Italy (82/125): Changes in 2/140 machines found.
2024-06-22 00:06:29 INFO 
 Result: 6 changes, 4 new machines found and 2 machines retired
2024-06-22 00:21:46 ERROR Found 3 problems that require manual intervention
2024-06-22 00:21:46 INFO ======Location differ completed at 2024-06-22 00:21:46=======
2024-06-22 00:21:47 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-06-22 22:30:02 INFO ======Location differ joblog from 2024-06-22 22:30:02=======
2024-06-22 22:30:47 INFO 51/67: Found machine to be added: Gulf State Park
2024-06-22 22:30:57 INFO Location Alabama (0/125): Changes in 1/67 machines found.
2024-06-22 23:05:35 INFO 291/386: Found machine to be added: Days Inn, Beach
2024-06-22 23:06:32 INFO Location Florida (24/125): Changes in 1/386 machines found.
2024-06-22 23:17:28 INFO Grand Caverns is available again
2024-06-22 23:18:26 INFO Location Virginia (35/125): Changes in 1/121 machines found.
2024-06-22 23:27:00 INFO 12/49: Found machine to be added: Kansas Wetlands Education Center
2024-06-22 23:27:24 INFO Location Kansas (45/125): Changes in 1/49 machines found.
2024-06-22 23:35:49 INFO 127/147: Found machine to be added: Bass Pro Shop Canada
2024-06-22 23:35:58 INFO Location Canada (61/125): Changes in 1/147 machines found.
2024-06-22 23:58:39 INFO 19/35: Found machine to be added: Footlite and Sole Punakaiki Gift Shop
2024-06-22 23:58:46 INFO Location New Zealand (95/125): Changes in 1/35 machines found.
2024-06-23 00:07:24 INFO 
 Result: 6 changes, 6 new machines found and 0 machines retired
2024-06-23 00:22:37 ERROR Found 3 problems that require manual intervention
2024-06-23 00:22:37 INFO ======Location differ completed at 2024-06-23 00:22:37=======
2024-06-23 00:22:38 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
2024-06-24 22:30:02 INFO ======Location differ joblog from 2024-06-24 22:30:02=======
2024-06-24 22:32:48 INFO Showcase Coins and Bullion is currently unavailable
2024-06-24 22:33:15 INFO Location Ohio (2/125): Changes in 1/136 machines found.
2024-06-24 22:38:51 INFO Roaring Rapids Pizza Company is currently unavailable
2024-06-24 22:39:45 INFO Location Oregon (8/125): Changes in 1/130 machines found.
2024-06-24 22:57:32 INFO 47/87: Found machine to be added: Fort Sisseton Historic State Park
2024-06-24 22:57:59 INFO Location South Dakota (20/125): Changes in 1/87 machines found.
2024-06-24 23:00:30 INFO Gatlinburg Welcome Center is currently unavailable
2024-06-24 23:02:11 INFO Location Tennessee (23/125): Changes in 1/198 machines found.
2024-06-24 23:02:26 INFO Show Case of Citrus is available again
2024-06-24 23:06:06 INFO Location Florida (24/125): Changes in 1/386 machines found.
2024-06-24 23:15:50 INFO Magpie - Downtown Coeur d'Alene Idaho is available again
2024-06-24 23:16:10 INFO Location Idaho (33/125): Changes in 1/41 machines found.
2024-06-24 23:25:05 INFO Dave and Buster's got permanently removed
2024-06-24 23:25:50 INFO Location New York (43/125): Changes in 1/201 machines found.
2024-06-24 23:54:02 INFO 188/216: Found machine to be added: FUJI TV, The Odaiba Observatory
2024-06-24 23:54:20 INFO Location Japan (84/125): Changes in 1/216 machines found.
2024-06-25 00:06:29 INFO 
 Result: 8 changes, 4 new machines found and 3 machines retired
2024-06-25 00:21:47 ERROR Found 3 problems that require manual intervention
2024-06-25 00:21:47 INFO ======Location differ completed at 2024-06-25 00:21:47=======
2024-06-25 00:21:48 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7237 named Skisportarena (Ski & Biathlon) submitted.

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
2024-06-26 22:30:02 INFO ======Location differ joblog from 2024-06-26 22:30:02=======
2024-06-26 22:39:23 INFO 65/131: Found machine to be added: Pietros Pizza
2024-06-26 22:39:58 INFO Location Oregon (8/125): Changes in 1/131 machines found.
2024-06-26 22:47:23 INFO Turtle Bay Exploration Park Museum Store (Next to Sundial Bridge) is available again
2024-06-26 22:50:00 INFO Location California (12/125): Changes in 1/756 machines found.
2024-06-26 22:51:47 INFO 142/192: Found machine to be added: Sparks Pinball Museum
2024-06-26 22:52:21 INFO Location Michigan (13/125): Changes in 1/192 machines found.
2024-06-26 23:08:40 INFO Buc-ees is currently unavailable
2024-06-26 23:10:29 INFO Ripley's Haunted Adventure is currently unavailable
2024-06-26 23:11:09 INFO Location Texas (26/125): Changes in 2/299 machines found.
2024-06-26 23:18:04 INFO Cooter's Place Luray, Dukes of Hazzard Museum is currently unavailable
2024-06-26 23:18:04 INFO Jellystone Park Campground is currently unavailable
2024-06-26 23:18:30 INFO Yellow Barn at Shenandoah Caverns is currently unavailable
2024-06-26 23:18:41 INFO Virginia Beach Fishing Pier - Bait & Tackle shop is currently unavailable
2024-06-26 23:18:55 INFO Location Virginia (35/125): Changes in 4/121 machines found.
2024-06-26 23:22:13 INFO Simply Seattle Gift Shop  is available again
2024-06-26 23:22:27 INFO Location Washington (38/125): Changes in 1/130 machines found.
2024-06-26 23:35:36 INFO 39/148: Found machine to be added: Tsawwassen Ferry Terminal
2024-06-26 23:36:36 INFO Location Canada (61/125): Changes in 1/148 machines found.
2024-06-26 23:43:45 INFO Tahiti Faa'a International Airport is currently unavailable
2024-06-26 23:43:49 INFO Location France (72/125): Changes in 1/105 machines found.
2024-06-27 00:08:12 INFO 
 Result: 12 changes, 5 new machines found and 7 machines retired
2024-06-27 00:23:40 ERROR Found 3 problems that require manual intervention
2024-06-27 00:23:40 INFO ======Location differ completed at 2024-06-27 00:23:40=======
2024-06-27 00:23:40 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-06-27 22:30:02 INFO ======Location differ joblog from 2024-06-27 22:30:02=======
2024-06-27 22:39:12 INFO Mo's Seafood Restaurant is currently unavailable
2024-06-27 22:39:52 INFO Location Oregon (8/125): Changes in 1/131 machines found.
2024-06-27 22:40:45 INFO Charlton Pike Rest Stop  is available again
2024-06-27 22:41:22 INFO Location Massachusetts (10/125): Changes in 1/90 machines found.
2024-06-27 23:05:01 INFO 214/387: Found machine to be added: Baytowne Wharf
2024-06-27 23:06:38 INFO Location Florida (24/125): Changes in 1/387 machines found.
2024-06-27 23:08:28 INFO 102/300: Found machine to be added: Texas Hot Stuff
2024-06-27 23:10:47 INFO Location Texas (26/125): Changes in 1/300 machines found.
2024-06-27 23:11:45 INFO 90/130: Found machine to be added: Chattahoochee Nature Center
2024-06-27 23:12:13 INFO Location Georgia (27/125): Changes in 1/130 machines found.
2024-06-27 23:17:35 INFO Pony Tails Chincoteague's Sweets Superstore is currently unavailable
2024-06-27 23:18:35 INFO Location Virginia (35/125): Changes in 1/121 machines found.
2024-06-27 23:22:06 INFO 126/131: Found machine to be added: Alderbrook Resort and Spa
2024-06-27 23:22:08 INFO Location Washington (38/125): Changes in 1/131 machines found.
2024-06-27 23:27:05 INFO 1/51: Found machine to be added: Amelia Earhart Birthplace Museum
2024-06-27 23:27:07 INFO 2/51: Found machine to be added: Amelia Earhart Hanger Museum
2024-06-27 23:27:39 INFO Location Kansas (45/125): Changes in 2/51 machines found.
2024-06-27 23:42:00 INFO 4/106: Found machine to be added: Buvette du Rocher des Doms
2024-06-27 23:43:26 INFO Location France (72/125): Changes in 1/106 machines found.
2024-06-28 00:07:48 INFO 
 Result: 10 changes, 8 new machines found and 2 machines retired
2024-06-28 00:23:20 ERROR Found 3 problems that require manual intervention
2024-06-28 00:23:20 INFO ======Location differ completed at 2024-06-28 00:23:20=======
2024-06-28 00:23:21 INFO Detected change in server_locations.json - push to github

**Review by jannisborn — APPROVED** [review]

**Pull request merged**
