### PR TITLE
Updates from website (server_locations)

### PR DESCRIPTION
**Pull request by jannisborn**
INFO:__main__:======Location differ joblog from 2023-10-27 05:05:04=======
INFO:googlemaps.client:API queries_quota: 60
ERROR:__main__:Machine Mack's Sport Shop & Alaskan Gifts in Alaska shown as available but http://209.221.138.252/Details.aspx?location=214 responds Internal Server Error (500)
ERROR:__main__:Machine Insectarium in Pennsylvania shown as available but http://209.221.138.252/Details.aspx?location=204156 responds Internal Server Error (500)
ERROR:__main__:Machine Minnesota State Fair - Old Arcade building in Minnesota shown as available but http://209.221.138.252/Details.aspx?location=257684 responds Internal Server Error (500)
ERROR:__main__:Machine True Grits Gift & Cards in Georgia shown as available but http://209.221.138.252/Details.aspx?location=1860 responds Internal Server Error (500)
ERROR:pennyme.pennycollector:Geolocation failed for: Unknown Location 	 sub: , Arco
ERROR:__main__:Machine Exploration Place in Kansas shown as available but http://209.221.138.252/Details.aspx?location=2240 responds Internal Server Error (500)
ERROR:__main__:Machine Lexington Style Trimmings BBQ     in North Carolina shown as available but http://209.221.138.252/Details.aspx?location=59354 responds Internal Server Error (500)
ERROR:__main__:Machine Maggie Mountaineer Crafts in North Carolina shown as available but http://209.221.138.252/Details.aspx?location=3684 responds Internal Server Error (500)
ERROR:__main__:Machine The Big Merino  in Australia shown as available but http://209.221.138.252/Details.aspx?location=993 responds Internal Server Error (500)
ERROR:__main__:Machine Naturpark Herberstein in Austria shown as available but http://209.221.138.252/Details.aspx?location=388 responds Internal Server Error (500)
ERROR:__main__:Machine Festung Kufstein Tirol in Austria shown as available but http://209.221.138.252/Details.aspx?location=394 responds Internal Server Error (500)
ERROR:__main__:Machine Schloss Tratzberg in Austria shown as available but http://209.221.138.252/Details.aspx?location=398 responds Internal Server Error (500)
INFO:__main__:Location Austria (54/125): Changes in 1/51 machines found.
ERROR:__main__:Machine Sea Life Centre in England shown as available but http://209.221.138.252/Details.aspx?location=3232 responds Internal Server Error (500)
ERROR:__main__:Machine Sunderland Football Stadium in England shown as available but http://209.221.138.252/Details.aspx?location=4284 responds Internal Server Error (500)
INFO:__main__:Location Germany (73/125): Changes in 1/373 machines found.
ERROR:__main__:Machine Six Flags Mexico in Mexico shown as available but http://209.221.138.252/Details.aspx?location=713 responds Internal Server Error (500)
ERROR:__main__:Machine Dierenpark (ZOO) in Netherlands shown as available but http://209.221.138.252/Details.aspx?location=708 responds Internal Server Error (500)
ERROR:__main__:Machine Duinrell in Netherlands shown as available but http://209.221.138.252/Details.aspx?location=621 responds Internal Server Error (500)
ERROR:__main__:Machine National Waterfront Museum in Wales shown as available but http://209.221.138.252/Details.aspx?location=94025 responds Internal Server Error (500)
INFO:__main__:
 Result: 2 changes, 1 new machines found and 1 machines retired
ERROR:__main__:Found 18 problems that require manual intervention
INFO:__main__:======Location differ completed at 2023-10-27 06:46:13=======
Processing now Alabama: 0/125
Processing now Louisiana: 1/125
Processing now Ohio: 2/125
Processing now Alaska: 3/125
Processing now Maine: 4/125
Processing now Oklahoma: 5/125
Processing now Arizona: 6/125
Processing now Maryland: 7/125
Processing now Oregon: 8/125
Processing now Arkansas: 9/125
Processing now Massachusetts: 10/125
Processing now Pennsylvania: 11/125
Processing now California: 12/125
Processing now Michigan: 13/125
Processing now Rhode Island: 14/125
Processing now Colorado: 15/125
Processing now Minnesota: 16/125
Processing now South Carolina: 17/125
Processing now Connecticut: 18/125
Processing now Mississippi: 19/125
Processing now South Dakota: 20/125
Processing now Delaware: 21/125
Processing now Missouri: 22/125
Processing now Tennessee: 23/125
Processing now Florida: 24/125
Processing now Montana: 25/125
Processing now Texas: 26/125
Processing now Georgia: 27/125
Processing now Nebraska: 28/125
Processing now Utah: 29/125
Processing now Hawaii: 30/125
Processing now Nevada: 31/125
Processing now Vermont: 32/125
Processing now Idaho: 33/125
Processing now New Hampshire: 34/125
Processing now Virginia: 35/125
Processing now Illinois: 36/125
Processing now New Jersey: 37/125
Processing now Washington: 38/125
Processing now Indiana: 39/125
Processing now New Mexico: 40/125
Processing now Washington DC: 41/125
Processing now Iowa: 42/125
Processing now New York: 43/125
Processing now West Virginia: 44/125
Processing now Kansas: 45/125
Processing now North Carolina: 46/125
Processing now Wisconsin: 47/125
Processing now Kentucky: 48/125
Processing now North Dakota: 49/125
Processing now Wyoming: 50/125
Processing now Australia: 53/125
Processing now Austria: 54/125
Processing now Bahamas: 55/125
Processing now Belarus: 56/125
Processing now Belgium: 57/125
Processing now Bermuda: 58/125
Processing now Brazil: 59/125
Processing now Bulgaria: 60/125
Processing now Canada: 61/125
Processing now Cayman Islands: 62/125
Processing now China: 63/125
Processing now Croatia: 64/125
Processing now Cyprus: 65/125
Processing now Czech Republic: 66/125
Processing now Denmark: 67/125
Processing now Ecuador: 68/125
Processing now England: 69/125
Processing now Estonia: 70/125
Processing now Finland: 71/125
Processing now France: 72/125
Processing now Germany: 73/125
Processing now Gibraltar: 74/125
Processing now Greece: 75/125
Processing now Guam: 76/125
Processing now Hong Kong: 77/125
Processing now Hungary: 78/125
Processing now India: 79/125
Processing now Ireland: 80/125
Processing now Israel: 81/125
Processing now Italy: 82/125
Processing now Jamaica: 83/125
Processing now Japan: 84/125
Processing now Jersey: 85/125
Processing now Kazakhstan: 86/125
Processing now Latvia: 87/125
Processing now Liechtenstein: 88/125
Processing now Lithuania: 89/125
Processing now Macao: 90/125
Processing now Malaysia: 91/125
Processing now Malta: 92/125
Processing now Mexico: 93/125
Processing now Netherlands: 94/125
Processing now New Zealand: 95/125
Processing now Northern Ireland: 96/125
Processing now Norway: 97/125
Processing now Nova Scotia: 98/125
Processing now Panama: 99/125
Processing now Poland: 100/125
Processing now Portugal: 101/125
Processing now Principality of Monaco: 102/125
Processing now Puerto Rico: 103/125
Processing now Romania: 104/125
Processing now Russia: 105/125
Processing now San Marino: 106/125
Processing now Scotland: 107/125
Processing now Singapore: 108/125
Processing now Slovenia: 109/125
Processing now South Africa: 110/125
Processing now South Korea: 111/125
Processing now Spain: 112/125
Processing now St. Lucia: 113/125
Processing now St. Martin: 114/125
Processing now Sweden: 115/125
Processing now Sweeded: 116/125
Processing now Switzerland: 117/125
Processing now Taiwan: 118/125
Processing now Thailand: 119/125
Processing now Turkey: 120/125
Processing now Ukraine: 121/125
Processing now United Arab Emirates: 122/125
Processing now US Virgin Islands: 123/125
Processing now Wales: 124/125

### CODE REVIEW

**Comment by jannisborn** [comment]
INFO:__main__:======Location differ joblog from 2023-10-27 05:05:04=======
INFO:googlemaps.client:API queries_quota: 60
ERROR:__main__:Machine Mack's Sport Shop & Alaskan Gifts in Alaska shown as available but http://209.221.138.252/Details.aspx?location=214 responds Internal Server Error (500)
ERROR:__main__:Machine Insectarium in Pennsylvania shown as available but http://209.221.138.252/Details.aspx?location=204156 responds Internal Server Error (500)
ERROR:__main__:Machine Minnesota State Fair - Old Arcade building in Minnesota shown as available but http://209.221.138.252/Details.aspx?location=257684 responds Internal Server Error (500)
ERROR:__main__:Machine True Grits Gift & Cards in Georgia shown as available but http://209.221.138.252/Details.aspx?location=1860 responds Internal Server Error (500)
ERROR:pennyme.pennycollector:Geolocation failed for: Unknown Location 	 sub: , Arco
ERROR:__main__:Machine Exploration Place in Kansas shown as available but http://209.221.138.252/Details.aspx?location=2240 responds Internal Server Error (500)
ERROR:__main__:Machine Lexington Style Trimmings BBQ     in North Carolina shown as available but http://209.221.138.252/Details.aspx?location=59354 responds Internal Server Error (500)
ERROR:__main__:Machine Maggie Mountaineer Crafts in North Carolina shown as available but http://209.221.138.252/Details.aspx?location=3684 responds Internal Server Error (500)
ERROR:__main__:Machine The Big Merino  in Australia shown as available but http://209.221.138.252/Details.aspx?location=993 responds Internal Server Error (500)
ERROR:__main__:Machine Naturpark Herberstein in Austria shown as available but http://209.221.138.252/Details.aspx?location=388 responds Internal Server Error (500)
ERROR:__main__:Machine Festung Kufstein Tirol in Austria shown as available but http://209.221.138.252/Details.aspx?location=394 responds Internal Server Error (500)
ERROR:__main__:Machine Schloss Tratzberg in Austria shown as available but http://209.221.138.252/Details.aspx?location=398 responds Internal Server Error (500)
INFO:__main__:Location Austria (54/125): Changes in 1/51 machines found.
ERROR:__main__:Machine Sea Life Centre in England shown as available but http://209.221.138.252/Details.aspx?location=3232 responds Internal Server Error (500)
ERROR:__main__:Machine Sunderland Football Stadium in England shown as available but http://209.221.138.252/Details.aspx?location=4284 responds Internal Server Error (500)
INFO:__main__:Location Germany (73/125): Changes in 1/373 machines found.
ERROR:__main__:Machine Six Flags Mexico in Mexico shown as available but http://209.221.138.252/Details.aspx?location=713 responds Internal Server Error (500)
ERROR:__main__:Machine Dierenpark (ZOO) in Netherlands shown as available but http://209.221.138.252/Details.aspx?location=708 responds Internal Server Error (500)
ERROR:__main__:Machine Duinrell in Netherlands shown as available but http://209.221.138.252/Details.aspx?location=621 responds Internal Server Error (500)
ERROR:__main__:Machine National Waterfront Museum in Wales shown as available but http://209.221.138.252/Details.aspx?location=94025 responds Internal Server Error (500)
INFO:__main__:
 Result: 2 changes, 1 new machines found and 1 machines retired
ERROR:__main__:Found 18 problems that require manual intervention
INFO:__main__:======Location differ completed at 2023-10-27 06:46:13=======
Processing now Alabama: 0/125
Processing now Louisiana: 1/125
Processing now Ohio: 2/125
Processing now Alaska: 3/125
Processing now Maine: 4/125
Processing now Oklahoma: 5/125
Processing now Arizona: 6/125
Processing now Maryland: 7/125
Processing now Oregon: 8/125
Processing now Arkansas: 9/125
Processing now Massachusetts: 10/125
Processing now Pennsylvania: 11/125
Processing now California: 12/125
Processing now Michigan: 13/125
Processing now Rhode Island: 14/125
Processing now Colorado: 15/125
Processing now Minnesota: 16/125
Processing now South Carolina: 17/125
Processing now Connecticut: 18/125
Processing now Mississippi: 19/125
Processing now South Dakota: 20/125
Processing now Delaware: 21/125
Processing now Missouri: 22/125
Processing now Tennessee: 23/125
Processing now Florida: 24/125
Processing now Montana: 25/125
Processing now Texas: 26/125
Processing now Georgia: 27/125
Processing now Nebraska: 28/125
Processing now Utah: 29/125
Processing now Hawaii: 30/125
Processing now Nevada: 31/125
Processing now Vermont: 32/125
Processing now Idaho: 33/125
Processing now New Hampshire: 34/125
Processing now Virginia: 35/125
Processing now Illinois: 36/125
Processing now New Jersey: 37/125
Processing now Washington: 38/125
Processing now Indiana: 39/125
Processing now New Mexico: 40/125
Processing now Washington DC: 41/125
Processing now Iowa: 42/125
Processing now New York: 43/125
Processing now West Virginia: 44/125
Processing now Kansas: 45/125
Processing now North Carolina: 46/125
Processing now Wisconsin: 47/125
Processing now Kentucky: 48/125
Processing now North Dakota: 49/125
Processing now Wyoming: 50/125
Processing now Australia: 53/125
Processing now Austria: 54/125
Processing now Bahamas: 55/125
Processing now Belarus: 56/125
Processing now Belgium: 57/125
Processing now Bermuda: 58/125
Processing now Brazil: 59/125
Processing now Bulgaria: 60/125
Processing now Canada: 61/125
Processing now Cayman Islands: 62/125
Processing now China: 63/125
Processing now Croatia: 64/125
Processing now Cyprus: 65/125
Processing now Czech Republic: 66/125
Processing now Denmark: 67/125
Processing now Ecuador: 68/125
Processing now England: 69/125
Processing now Estonia: 70/125
Processing now Finland: 71/125
Processing now France: 72/125
Processing now Germany: 73/125
Processing now Gibraltar: 74/125
Processing now Greece: 75/125
Processing now Guam: 76/125
Processing now Hong Kong: 77/125
Processing now Hungary: 78/125
Processing now India: 79/125
Processing now Ireland: 80/125
Processing now Israel: 81/125
Processing now Italy: 82/125
Processing now Jamaica: 83/125
Processing now Japan: 84/125
Processing now Jersey: 85/125
Processing now Kazakhstan: 86/125
Processing now Latvia: 87/125
Processing now Liechtenstein: 88/125
Processing now Lithuania: 89/125
Processing now Macao: 90/125
Processing now Malaysia: 91/125
Processing now Malta: 92/125
Processing now Mexico: 93/125
Processing now Netherlands: 94/125
Processing now New Zealand: 95/125
Processing now Northern Ireland: 96/125
Processing now Norway: 97/125
Processing now Nova Scotia: 98/125
Processing now Panama: 99/125
Processing now Poland: 100/125
Processing now Portugal: 101/125
Processing now Principality of Monaco: 102/125
Processing now Puerto Rico: 103/125
Processing now Romania: 104/125
Processing now Russia: 105/125
Processing now San Marino: 106/125
Processing now Scotland: 107/125
Processing now Singapore: 108/125
Processing now Slovenia: 109/125
Processing now South Africa: 110/125
Processing now South Korea: 111/125
Processing now Spain: 112/125
Processing now St. Lucia: 113/125
Processing now St. Martin: 114/125
Processing now Sweden: 115/125
Processing now Sweeded: 116/125
Processing now Switzerland: 117/125
Processing now Taiwan: 118/125
Processing now Thailand: 119/125
Processing now Turkey: 120/125
Processing now Ukraine: 121/125
Processing now United Arab Emirates: 122/125
Processing now US Virgin Islands: 123/125
Processing now Wales: 124/125

**Comment by NinaWie** [comment]
Machine updates submitted for review

**Comment by NinaWie** [comment]
Machine updates submitted for review

**Review by NinaWie — COMMENTED** [review]
Could you provide more details on the plan how to deal with the machines with broken link?

**Comment by jannisborn** [comment]
First, I decided that it is tolerable that machines marked as retired in our app have broken links. I did so because I thought it was hard to navigate around but now I thought better and believe we should remove the links in favor of "null". Unavailable machines will be skipped in the location differ anyways and if the status changes to active, the fuzzy search should catch it and add the link (if available. If not, it will add it to problems). I will open an issue for this.


The hotfix in the previous PR #192 was to:
1. Test for any machine listed on the website as AVAILABLE whether the link is sane. If not, a warning is raised and it's added to the problems. Every day, the entry will remain in the `problems.json` which is OK since it's a persistent inconsistency
2. I test the links of all remaining machines in the DB. This is because we might have machines with valid links that are not listed on the website. It's unlikely but who knows...


The problem is that this makes the script pretty slow (1.5h) but I think it's tolerable. I'm adding a few small improvements now

**Review by NinaWie — APPROVED** [review]
This one looks fine

**Comment by NinaWie** [comment]
> First, I decided that it is tolerable that machines marked as retired in our app have broken links. I did so because I thought it was hard to navigate around but now I thought better and believe we should remove the links in favor of "null". Unavailable machines will be skipped in the location differ anyways and if the status changes to active, the fuzzy search should catch it and add the link (if available. If not, it will add it to problems). I will open an issue for this.
> 
> The hotfix in the previous PR #192 was to:
> 
>     1. Test for any machine listed on the website as AVAILABLE whether the link is sane. If not, a warning is raised and it's added to the problems. Every day, the entry will remain in the `problems.json` which is OK since it's a persistent inconsistency
> 
>     2. I test the links of all remaining machines in the DB. This is because we might have machines with valid links that are not listed on the website. It's unlikely but who knows...
> 
> 
> The problem is that this makes the script pretty slow (1.5h) but I think it's tolerable. I'm adding a few small improvements now

Thanks for explaining! I also like the idea most to replace the broken links with null. For the meantime, your fix sees good. We could also have two separate cron job (adding an input argument whether the links should be checked), and then run the longer cron job just once per week or so.

**Pull request merged**
