### PR TITLE
Updates from website (server_locations)

### PR DESCRIPTION
**Pull request by jannisborn**
2024-01-28 22:30:02 INFO ======Location differ joblog from 2024-01-28 22:30:02=======
2024-01-28 22:45:38 INFO Highland Market (was Famous Market) is currently unavailable
2024-01-28 22:50:14 INFO Location California (12/125): Changes in 1/751 machines found.
2024-01-28 23:16:08 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-01-29 00:06:46 INFO 
 Result: 1 changes, 0 new machines found and 1 machines retired
2024-01-29 00:19:54 ERROR Found 5 problems that require manual intervention
2024-01-29 00:19:54 INFO ======Location differ completed at 2024-01-29 00:19:54=======
2024-01-29 00:19:55 INFO Detected change in server_locations.json - push to github

### CODE REVIEW

**Comment by NinaWie** [comment]
Request change to machine 5702 named Tabak Witt - Changed:
	Status from: available to: retired
	Address from Kieler Str 56, EckernfÃ¶rde to: Kieler Str 56, Eckernförde

**Comment by jannisborn** [comment]
2024-01-29 22:30:01 INFO ======Location differ joblog from 2024-01-29 22:30:01=======
2024-01-29 23:04:18 INFO Tin City is available again
2024-01-29 23:05:47 INFO Location Florida (24/125): Changes in 1/379 machines found.
2024-01-29 23:15:14 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-01-30 00:09:34 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-01-30 00:22:38 ERROR Found 5 problems that require manual intervention
2024-01-30 00:22:38 INFO ======Location differ completed at 2024-01-30 00:22:38=======
2024-01-30 00:22:39 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
Request change to machine 1118 named Wonders of Wildlife/ American National Fish - Changed:
	Title from: Wonders of Wildlife/ American National Fish & Wildlife Museum to: Wonders of Wildlife/ American National Fish
	Multimachine from: 1 to: 2

**Comment by jannisborn** [comment]
No website updates today!

**Comment by NinaWie** [comment]
Request change to machine 1118 named Wonders of Wildlife/ American National Fish - Changed:
Machine with pending changes is getting changed *AGAIN* @jannisborn @NinaWie:

**Pull request merged**
