### PR TITLE
Updates from website (server_locations)

### PR DESCRIPTION
**Pull request by jannisborn**
2024-01-09 22:30:01 INFO ======Location differ joblog from 2024-01-09 22:30:01=======
2024-01-09 22:55:50 INFO 53/105: Found machine to be added: Sparky's  Burgers & BBQ
2024-01-09 22:56:27 INFO Location Minnesota (16/125): Changes in 1/105 machines found.
2024-01-09 23:17:15 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-01-09 23:31:37 INFO 84/118: Found machine to be added: Shalom Wildlife Sanctuary
2024-01-09 23:31:58 INFO Location Wisconsin (47/125): Changes in 1/118 machines found.
2024-01-09 23:48:49 INFO 265/369: Found machine to be added: Heini Klopfer Skiflugschanze
2024-01-09 23:48:51 INFO 266/369: Found machine to be added: ORLEN-Arena Oberstdorf
2024-01-09 23:50:21 INFO Location Germany (73/125): Changes in 2/369 machines found.
2024-01-10 00:10:11 INFO 
 Result: 4 changes, 4 new machines found and 0 machines retired
2024-01-10 00:24:39 ERROR Found 5 problems that require manual intervention
2024-01-10 00:24:39 INFO ======Location differ completed at 2024-01-10 00:24:39=======
2024-01-10 00:24:40 INFO Detected change in server_locations.json - push to github

### CODE REVIEW

**Comment by jannisborn** [comment]
2024-01-10 22:30:07 INFO ======Location differ joblog from 2024-01-10 22:30:07=======
2024-01-10 22:42:33 INFO Pennsylvania Farm Show is available again
2024-01-10 22:43:55 INFO Location Pennsylvania (11/125): Changes in 1/209 machines found.
2024-01-10 23:17:32 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-01-11 00:10:48 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-01-11 00:26:15 ERROR Found 5 problems that require manual intervention
2024-01-11 00:26:15 INFO ======Location differ completed at 2024-01-11 00:26:15=======
2024-01-11 00:26:15 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-01-11 22:30:02 INFO ======Location differ joblog from 2024-01-11 22:30:02=======
2024-01-11 22:35:20 INFO 0/221: Found machine to be added: Gold Field Ghost Town (Bar G Hat Shop)
2024-01-11 22:37:53 INFO Location Arizona (6/125): Changes in 1/221 machines found.
2024-01-11 23:11:28 INFO Legoland® Discovery Center  is currently unavailable
2024-01-11 23:12:39 INFO Location Georgia (27/125): Changes in 1/126 machines found.
2024-01-11 23:16:51 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-01-12 00:09:00 INFO 
 Result: 2 changes, 1 new machines found and 1 machines retired
2024-01-12 00:23:48 ERROR Found 5 problems that require manual intervention
2024-01-12 00:23:48 INFO ======Location differ completed at 2024-01-12 00:23:48=======
2024-01-12 00:23:49 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-01-12 22:30:02 INFO ======Location differ joblog from 2024-01-12 22:30:02=======
2024-01-12 23:20:37 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-01-13 00:06:25 INFO Dunfermline Carnegie Library is currently unavailable
2024-01-13 00:07:07 INFO Location Scotland (107/125): Changes in 1/89 machines found.
2024-01-13 00:12:45 INFO 
 Result: 1 changes, 0 new machines found and 1 machines retired
2024-01-13 00:27:45 ERROR Found 5 problems that require manual intervention
2024-01-13 00:27:45 INFO ======Location differ completed at 2024-01-13 00:27:45=======
2024-01-13 00:27:45 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-01-13 22:30:02 INFO ======Location differ joblog from 2024-01-13 22:30:02=======
2024-01-13 22:35:29 INFO 37/69: Found machine to be added: Tongass Historical Museum
2024-01-13 22:35:49 INFO Location Alaska (3/125): Changes in 1/69 machines found.
2024-01-13 22:39:04 INFO Saguaro National Park is available again
2024-01-13 22:39:33 INFO Location Arizona (6/125): Changes in 1/221 machines found.
2024-01-13 22:41:03 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=3974': ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-01-13 23:19:32 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-01-14 00:12:29 INFO 
 Result: 2 changes, 2 new machines found and 0 machines retired
2024-01-14 00:28:05 ERROR Found 5 problems that require manual intervention
2024-01-14 00:28:05 INFO ======Location differ completed at 2024-01-14 00:28:05=======
2024-01-14 00:28:06 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
No website updates today!

**Review by NinaWie — APPROVED** [review]
made some small corrections

**Pull request merged**
