### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
New machine 7109 named Bregenzer Festspiele submitted.

### CODE REVIEW

**Comment by NinaWie** [comment]
New machine 7110 named George Inlet Lodge submitted.

**Comment by NinaWie** [comment]
New machine 7111 named Namco Funscape angry birds submitted.

**Comment by NinaWie** [comment]
New machine 7112 named Mount Pleasant Memorial Waterfront Park submitted.

**Comment by jannisborn** [comment]
2024-03-30 22:30:01 INFO ======Location differ joblog from 2024-03-30 22:30:01=======
2024-03-30 22:30:58 INFO Silver Dollar Pawn & Jewelry Center is currently unavailable
2024-03-30 22:31:42 INFO Location Louisiana (1/125): Changes in 1/88 machines found.
2024-03-30 22:33:07 INFO Cabela's is currently unavailable
2024-03-30 22:33:14 INFO Location Ohio (2/125): Changes in 1/136 machines found.
2024-03-30 22:35:05 INFO 58/63: Found machine to be added: Tulsa Air and Space Museum and Planetarium
2024-03-30 22:35:08 INFO Location Oklahoma (5/125): Changes in 1/63 machines found.
2024-03-30 23:10:35 INFO Georgia Aquarium is available again
2024-03-30 23:10:38 INFO 19/127: Found machine to be added: Only You Tattoo
2024-03-30 23:11:49 INFO Location Georgia (27/125): Changes in 2/127 machines found.
2024-03-30 23:15:53 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-03-30 23:19:37 INFO TBD is currently unavailable
2024-03-30 23:19:37 INFO Location Illinois (36/125): Changes in 1/136 machines found.
2024-03-30 23:32:25 INFO Anglesea General Store is currently unavailable
2024-03-30 23:32:43 INFO Location Australia (53/125): Changes in 1/89 machines found.
2024-03-30 23:37:19 INFO 72/435: Found machine to be added: World Of Country Life
2024-03-30 23:41:00 INFO Location England (69/125): Changes in 1/435 machines found.
2024-03-30 23:46:08 INFO 239/374: Found machine to be added: Moritzburg Castle 
2024-03-30 23:48:06 INFO Location Germany (73/125): Changes in 1/374 machines found.
2024-03-30 23:54:41 INFO 193/212: Found machine to be added: Fujiyama Onsen
2024-03-30 23:54:52 INFO Location Japan (84/125): Changes in 1/212 machines found.
2024-03-30 23:55:11 INFO 6/13: Found machine to be added: Palanga Amber Museum 
2024-03-30 23:55:17 INFO Location Lithuania (89/125): Changes in 1/13 machines found.
2024-03-31 00:07:04 INFO 
 Result: 11 changes, 7 new machines found and 4 machines retired
2024-03-31 00:17:42 ERROR Our machine West Country Shopping Village in England from Device shown as available but http://209.221.138.252/Details.aspx?location=342730 responds Internal Server Error (500)
2024-03-31 00:21:30 ERROR Our machine AP Foods on the Embankment. in England from Server shown as available but http://209.221.138.252/Details.aspx?location=422838 responds Internal Server Error (500)
2024-03-31 00:21:31 ERROR Found 4 problems that require manual intervention
2024-03-31 00:21:31 INFO ======Location differ completed at 2024-03-31 00:21:31=======
2024-03-31 00:21:32 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-03-31 22:30:01 INFO ======Location differ joblog from 2024-03-31 22:30:01=======
2024-03-31 22:43:08 INFO 159/211: Found machine to be added: Grandpa Joe's Candy Shop (Strip District)
2024-03-31 22:43:37 INFO Location Pennsylvania (11/125): Changes in 1/211 machines found.
2024-03-31 23:16:35 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-03-31 23:27:50 INFO 18/48: Found machine to be added: Strataca
2024-03-31 23:28:08 INFO Location Kansas (45/125): Changes in 1/48 machines found.
2024-03-31 23:41:38 INFO Distance match - Seeems that machine Namco Funscape at 244, Metrocentre, Gateshead, TYNE & WEAR - Gateshead already exists as: Namco Funscape angry birds
2024-04-01 00:08:16 INFO 
 Result: 2 changes, 2 new machines found and 0 machines retired
2024-04-01 00:22:53 ERROR Found 4 problems that require manual intervention
2024-04-01 00:22:53 INFO ======Location differ completed at 2024-04-01 00:22:53=======
2024-04-01 00:22:54 INFO Detected change in server_locations.json - push to github

**Review by jannisborn — APPROVED** [review]

**Pull request merged**
