### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 5587 "Pennsylvania":
	Status from: available to: retired

### CODE REVIEW

**Comment by NinaWie** [comment]
New machine 7347 named Hidden Valley Animal Adventure submitted.

**Comment by NinaWie** [comment]
New machine 7348 named Prince Rupert Cruise Line Port submitted.

**Comment by jannisborn** [comment]
2024-08-06 09:45:01 INFO ======Location differ joblog from 2024-08-06 09:45:01=======
2024-08-06 09:47:54 INFO 94/137: Found machine to be added: Serpent Mound Gift Shop
2024-08-06 09:48:21 INFO Location Ohio (2/125): Changes in 1/137 machines found.
2024-08-06 09:49:02 INFO Russell's Gifts is available again
2024-08-06 09:49:13 INFO Location Alaska (3/125): Changes in 1/68 machines found.
2024-08-06 09:49:36 INFO 1/67: Found machine to be added: Pops Soda Ranch
2024-08-06 09:50:01 INFO 27/67: Found machine to be added: Comanche National Museum & Cultural Center
2024-08-06 09:50:30 INFO Location Oklahoma (5/125): Changes in 2/67 machines found.
2024-08-06 09:55:45 INFO National Park Gifts and Souvenirs is available again
2024-08-06 09:56:04 INFO Location Arkansas (9/125): Changes in 1/55 machines found.
2024-08-06 09:57:07 INFO 1/214: Found machine to be added: DiLeo Oral Surgery
2024-08-06 09:57:50 INFO 65/214: Found machine to be added: Gettysburg Tours
2024-08-06 09:58:12 INFO King Of Prussia Stadium 16 & IMAX is currently unavailable
2024-08-06 09:59:23 INFO Location Pennsylvania (11/125): Changes in 3/214 machines found.
2024-08-06 10:06:37 INFO The Taffy Barrel is available again
2024-08-06 10:08:40 INFO Location Michigan (13/125): Changes in 1/194 machines found.
2024-08-06 10:10:22 INFO 124/220: Found machine to be added: Eureka McConnell Science Museum
2024-08-06 10:11:28 INFO Location Colorado (15/125): Changes in 1/220 machines found.
2024-08-06 10:11:36 INFO Mall of America - I Love Minnesota is currently unavailable
2024-08-06 10:12:37 INFO Location Minnesota (16/125): Changes in 1/106 machines found.
2024-08-06 10:14:07 INFO Keith's Superstore is available again
2024-08-06 10:14:19 INFO Location Mississippi (19/125): Changes in 1/28 machines found.
2024-08-06 10:15:13 INFO 67/88: Found machine to be added: Rapid City Mall - Uptown Rapid 
2024-08-06 10:15:29 INFO Location South Dakota (20/125): Changes in 1/88 machines found.
2024-08-06 10:16:25 INFO 75/178: Found machine to be added: Wallys 
2024-08-06 10:17:35 INFO Location Missouri (22/125): Changes in 1/178 machines found.
2024-08-06 10:18:09 INFO Dick's Last Resort  Gatlinburg is available again
2024-08-06 10:20:05 INFO Location Tennessee (23/125): Changes in 1/199 machines found.
2024-08-06 10:26:38 INFO Sea Quest Interactive Aquarium  is available again
2024-08-06 10:27:46 INFO 190/304: Found machine to be added: Lewisville Visitor Center
2024-08-06 10:28:25 INFO Lackland Air Force Base (Mini Mall - Bldg. 7025) is currently unavailable
2024-08-06 10:29:11 INFO Location Texas (26/125): Changes in 3/304 machines found.
2024-08-06 10:31:46 INFO 28/101: Found machine to be added: Blue Clothing Company
2024-08-06 10:32:38 INFO Location Utah (29/125): Changes in 1/101 machines found.
2024-08-06 10:32:52 INFO 17/96: Found machine to be added: Violets Toy Box 
2024-08-06 10:33:17 INFO Location Hawaii (30/125): Changes in 1/96 machines found.
2024-08-06 10:36:38 INFO Cabela's is currently unavailable
2024-08-06 10:37:37 INFO Location Virginia (35/125): Changes in 1/121 machines found.
2024-08-06 10:46:17 INFO 7/39: Found machine to be added: Childrens Museum of the Low Counrty
2024-08-06 10:46:38 INFO Location West Virginia (44/125): Changes in 1/39 machines found.
2024-08-06 10:47:43 INFO Edge case, potentially multiple matches for Pinkys Westside Grill
2024-08-06 10:47:43 INFO Seems that machine Pinkys Westside Grill already exists as: Pinky’s Westside Grill1600 W Morehead St, Charlotte, NC 28208
2024-08-06 10:48:16 INFO Edge case, potentially multiple matches for Pinky's Westside Grill
2024-08-06 10:48:16 INFO Seems that machine Pinky's Westside Grill already exists as: Pinky’s Westside Grill9822 Gilead Rd, Huntersville, NC 28078, USA
2024-08-06 10:50:05 INFO Pepin Depot Museum is currently unavailable
2024-08-06 10:50:44 INFO Location Wisconsin (47/125): Changes in 1/121 machines found.
2024-08-06 10:52:38 INFO Distance match - Seeems that machine Old Faithful General Store, Upper at 2 Old Faithful Rd , Yellowstone National Park - Old Faithful already exists as: Yellowstone - Old Faithful General Store
2024-08-06 10:52:45 INFO 55/57: Found machine to be added: Old Faithful Visitor and Education Center Gift Shop
2024-08-06 10:52:46 INFO Location Wyoming (2281/125): Changes in 1/57 machines found.
2024-08-06 10:54:20 INFO 29/59: Found machine to be added: Museum Almkanal
2024-08-06 10:54:52 INFO Location Austria (54/125): Changes in 1/59 machines found.
2024-08-06 10:57:13 INFO LEGOLAND® Discovery Centre is currently unavailable
2024-08-06 10:57:24 INFO Location Canada (61/125): Changes in 1/148 machines found.
2024-08-06 10:58:43 INFO 26/443: Found machine to be added: The Hole In Wand
2024-08-06 10:58:58 INFO Heligan Lost Gardens is currently unavailable
2024-08-06 11:00:30 INFO Dreamland Margate  is available again
2024-08-06 11:03:28 INFO Location England (69/125): Changes in 3/443 machines found.
2024-08-06 11:03:51 INFO 3/111: Found machine to be added: Zoo dAmnéville
2024-08-06 11:04:03 INFO 17/111: Found machine to be added: Mémorial Charles De Gaulle
2024-08-06 11:04:14 INFO 25/111: Found machine to be added: Office de Tourisme du Lac du Der
2024-08-06 11:05:35 INFO Location France (72/125): Changes in 3/111 machines found.
2024-08-06 11:11:24 INFO 350/391: Found machine to be added: (in front of shop of 1000 clocks)
2024-08-06 11:11:58 INFO Location Germany (73/125): Changes in 1/391 machines found.
2024-08-06 11:15:39 INFO 100/142: Found machine to be added: Souvenir shop (near the Pantheon)
2024-08-06 11:16:08 INFO Location Italy (82/125): Changes in 1/142 machines found.
2024-08-06 11:16:29 INFO KamoBagnoregiogawa Sea World Hotel is currently unavailable
2024-08-06 11:16:29 INFO Kamogawa Sea World is currently unavailable
2024-08-06 11:19:29 INFO Location Japan (84/125): Changes in 2/217 machines found.
2024-08-06 11:28:56 INFO 4/182: Found machine to be added: Verde´s Lotería y Apuestas del Estado
2024-08-06 11:29:04 INFO 11/182: Found machine to be added: Gaztelugatxe Nature Preserve
2024-08-06 11:29:22 INFO Souvenirs Sagrada Família is available again
2024-08-06 11:29:31 INFO 41/182: Found machine to be added: Plaza Mayor Souvenir Shop
2024-08-06 11:30:25 INFO 89/182: Found machine to be added: Caramelos Convenience Store
2024-08-06 11:30:27 INFO 90/182: Found machine to be added: Taller de Artesania y Cerámica Terracota Mérida Extremadura
2024-08-06 11:31:56 INFO Location Spain (112/125): Changes in 6/182 machines found.
2024-08-06 11:35:00 INFO 
 Result: 42 changes, 33 new machines found and 9 machines retired
2024-08-06 11:52:42 ERROR Found 3 problems that require manual intervention
2024-08-06 11:52:42 INFO ======Location differ completed at 2024-08-06 11:52:42=======
2024-08-06 11:52:42 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7374 named Ristorante Bar Nuovo Edelweiss submitted.

**Comment by jannisborn** [comment]
2024-08-07 09:45:02 INFO ======Location differ joblog from 2024-08-07 09:45:02=======
2024-08-07 10:38:57 INFO Pony Tails Chincoteague's Sweets Superstore is available again
2024-08-07 10:40:12 INFO Location Virginia (35/125): Changes in 1/121 machines found.
2024-08-07 10:42:35 INFO Jenkinsons Boardwalk - Pavilion Arcade is available again
2024-08-07 10:42:47 INFO Location New Jersey (37/125): Changes in 1/99 machines found.
2024-08-07 11:31:11 INFO 8/74: Found machine to be added: Barcelos, Braga
2024-08-07 11:32:22 INFO Location Portugal (101/125): Changes in 1/74 machines found.
2024-08-07 11:34:09 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=4197': ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
2024-08-07 11:34:19 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=29655': HTTPConnectionPool(host='209.221.138.252', port=80): Max retries exceeded with url: /Details.aspx?location=29655 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f95e5f22ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-08-07 11:41:47 INFO 
 Result: 3 changes, 3 new machines found and 0 machines retired
2024-08-07 12:01:53 ERROR Found 3 problems that require manual intervention
2024-08-07 12:01:53 INFO ======Location differ completed at 2024-08-07 12:01:53=======
2024-08-07 12:01:54 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
No website updates today!

**Review by jannisborn — APPROVED** [review]

**Pull request merged**
