### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 6429 "Souvenirs Sagrada Familia":
	Status from: available to: out-of-order
	Title from: Souvenirs Sagrada Família to: Souvenirs Sagrada Familia

### CODE REVIEW

**Comment by jannisborn** [comment]
2024-04-24 22:30:02 INFO ======Location differ joblog from 2024-04-24 22:30:02=======
2024-04-24 22:36:30 INFO Dairy Queen Sedona is currently unavailable
2024-04-24 22:36:33 INFO Red Rock Impressions is available again
2024-04-24 22:37:34 INFO Location Arizona (6/125): Changes in 2/223 machines found.
2024-04-24 22:44:37 INFO Stovepipe Wells Village Restaurant Building  is currently unavailable
2024-04-24 22:48:40 INFO 647/752: Found machine to be added: Municipal Wharf - Made in Santa Cruz
2024-04-24 22:49:35 INFO Location California (12/125): Changes in 2/752 machines found.
2024-04-24 23:15:26 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-04-25 00:02:42 INFO 117/171: Found machine to be added: Puente nuevo souvenirs
2024-04-25 00:03:26 INFO Location Spain (112/125): Changes in 1/171 machines found.
2024-04-25 00:05:46 INFO 
 Result: 5 changes, 3 new machines found and 2 machines retired
2024-04-25 00:20:01 ERROR Our machine Dagebll Souvenirshop Meer Flair in Germany from Server shown as available but http://www.elongated-coin.de/phpBB3/viewtopic.php?t=17722 responds Bad Gateway (502)
2024-04-25 00:20:15 ERROR Found 4 problems that require manual intervention
2024-04-25 00:20:15 INFO ======Location differ completed at 2024-04-25 00:20:15=======
2024-04-25 00:20:16 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-04-25 22:30:01 INFO ======Location differ joblog from 2024-04-25 22:30:01=======
2024-04-25 23:15:19 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-04-25 23:57:30 INFO Seeems that machine Zamek Reszel at Podzamcze 3, 11-440, Reszel already exists as: Podzamcze 3, 11-440 Reszel, Poland
2024-04-26 00:05:35 INFO 
 Result: 0 changes, 0 new machines found and 0 machines retired
2024-04-26 00:19:57 ERROR Found 4 problems that require manual intervention
2024-04-26 00:19:57 INFO ======Location differ completed at 2024-04-26 00:19:57=======
2024-04-26 00:19:58 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-04-26 22:30:01 INFO ======Location differ joblog from 2024-04-26 22:30:01=======
2024-04-26 22:48:43 INFO UC Santa Cruz Arboretum and Botanic Garden is currently unavailable
2024-04-26 22:49:33 INFO Location California (12/125): Changes in 1/752 machines found.
2024-04-26 23:15:23 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-04-26 23:36:28 INFO The Milky Way Adventure Park, Downland Farm is currently unavailable
2024-04-26 23:39:34 INFO Namco Funscape is currently unavailable
2024-04-26 23:40:03 INFO Location England (69/125): Changes in 2/436 machines found.
2024-04-27 00:05:32 INFO 
 Result: 3 changes, 0 new machines found and 3 machines retired
2024-04-27 00:20:01 ERROR Found 4 problems that require manual intervention
2024-04-27 00:20:01 INFO ======Location differ completed at 2024-04-27 00:20:01=======
2024-04-27 00:20:02 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7149 named Bastei Bridge 2 submitted.

**Comment by NinaWie** [comment]
New machine 7150 named Bastei Bus Stop submitted.

**Review by jannisborn — APPROVED** [review]

**Pull request merged**
