### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
New machine 7417 named Reeperbahn submitted.

### CODE REVIEW

**Comment by NinaWie** [comment]
New machine 7418 named KAISER WILHELM GEDACHTNIS KIRCHE submitted.

**Comment by NinaWie** [comment]
New machine 7419 named Berlin submitted.

**Comment by jannisborn** [comment]
2024-08-18 22:30:02 INFO ======Location differ joblog from 2024-08-18 22:30:02=======
2024-08-18 23:06:18 INFO Country Music Hall of Fame and Museum is available again
2024-08-18 23:07:15 INFO Location Tennessee (23/125): Changes in 1/199 machines found.
2024-08-18 23:22:36 INFO 20/40: Found machine to be added: Loon Mountain Resort 
2024-08-18 23:22:52 INFO Location New Hampshire (34/125): Changes in 1/40 machines found.
2024-08-18 23:23:17 INFO 37/122: Found machine to be added: Massanutten Resort 
2024-08-18 23:24:05 INFO Location Virginia (35/125): Changes in 1/122 machines found.
2024-08-19 00:10:27 INFO 2/11: Found machine to be added: Sea Life Busan Aquarium
2024-08-19 00:10:34 INFO Location South Korea (111/125): Changes in 1/11 machines found.
2024-08-19 00:15:40 INFO 
 Result: 4 changes, 4 new machines found and 0 machines retired
2024-08-19 00:32:11 ERROR Found 3 problems that require manual intervention
2024-08-19 00:32:11 INFO ======Location differ completed at 2024-08-19 00:32:11=======
2024-08-19 00:32:12 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-08-19 22:30:02 INFO ======Location differ joblog from 2024-08-19 22:30:02=======
2024-08-19 22:52:07 INFO Tahoe T-Shirts Outlet is currently unavailable
2024-08-19 22:52:35 INFO Location California (12/125): Changes in 1/759 machines found.
2024-08-19 22:58:52 INFO Palmettoville is currently unavailable
2024-08-19 22:59:46 INFO Location South Carolina (17/125): Changes in 1/105 machines found.
2024-08-19 23:02:28 INFO Boomland Fireworks Gifts & Collectibles  is available again
2024-08-19 23:03:52 INFO Location Missouri (22/125): Changes in 1/180 machines found.
2024-08-20 00:14:57 INFO 
 Result: 3 changes, 1 new machines found and 2 machines retired
2024-08-20 00:31:18 ERROR Found 3 problems that require manual intervention
2024-08-20 00:31:18 INFO ======Location differ completed at 2024-08-20 00:31:18=======
2024-08-20 00:31:19 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7424 named This and That submitted.

**Comment by jannisborn** [comment]
No website updates today!

**Comment by NinaWie** [comment]
New machine 7425 named Penny Pincher submitted.

**Comment by NinaWie** [comment]
New machine 7426 named Schifffahrt BLS Berner Oberland submitted.

**Comment by jannisborn** [comment]
2024-08-21 22:30:01 INFO ======Location differ joblog from 2024-08-21 22:30:01=======
2024-08-21 22:53:38 INFO Blue Pebbles is available again
2024-08-21 22:53:43 INFO 711/760: Found machine to be added: Empanash 
2024-08-21 22:53:44 INFO Gift Shop at Lake Tahoe  is available again
2024-08-21 22:54:20 INFO Location California (12/125): Changes in 3/760 machines found.
2024-08-21 23:00:04 INFO Mall of America - Legacy Toys is currently unavailable
2024-08-21 23:01:10 INFO Location Minnesota (16/125): Changes in 1/106 machines found.
2024-08-21 23:07:39 INFO 68/200: Found machine to be added: Nashville Shores Lakeside Resort  
2024-08-21 23:09:06 INFO Location Tennessee (23/125): Changes in 1/200 machines found.
2024-08-21 23:16:53 INFO 202/305: Found machine to be added: Museum of the Southwest
2024-08-21 23:18:09 INFO Location Texas (26/125): Changes in 1/305 machines found.
2024-08-21 23:25:58 INFO 13/123: Found machine to be added: National Museum of the United States Army 
2024-08-21 23:26:59 INFO Location Virginia (35/125): Changes in 1/123 machines found.
2024-08-21 23:47:35 INFO Boscombe Pier is currently unavailable
2024-08-21 23:51:10 INFO Emmerdale Studio Experience Tour (Emmerdale Production Centre) is currently unavailable
2024-08-21 23:51:17 INFO Location England (69/125): Changes in 2/444 machines found.
2024-08-22 00:02:19 INFO Ricordi Pompeiani di Antonio Cestra is available again
2024-08-22 00:02:59 INFO Location Italy (82/125): Changes in 1/142 machines found.
2024-08-22 00:03:47 INFO 45/218: Found machine to be added: Hakone Kowakien Yunessun
2024-08-22 00:06:07 INFO Location Japan (84/125): Changes in 1/218 machines found.
2024-08-22 00:19:21 INFO 
 Result: 11 changes, 8 new machines found and 3 machines retired
2024-08-22 00:36:11 ERROR Found 3 problems that require manual intervention
2024-08-22 00:36:11 INFO ======Location differ completed at 2024-08-22 00:36:11=======
2024-08-22 00:36:12 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7432 named Tempio di Apollo submitted.

**Comment by NinaWie** [comment]
New machine 7433 named Souvenir medailles submitted.

**Comment by NinaWie** [comment]
New machine 7434 named Laboe Ehrenmal and Submarine submitted.

**Comment by NinaWie** [comment]
New machine 7435 named Filippo‘s Erlebnisgarten submitted.

**Comment by NinaWie** [comment]
New machine 7436 named Aussichtsplattform Schleuse submitted.

**Comment by NinaWie** [comment]
New machine 7435 named Sparks Pinball Museum submitted.

**Comment by jannisborn** [comment]
No website updates today!

**Comment by NinaWie** [comment]
New machine 7436 named New Baltimore Trade Center submitted.

**Comment by jannisborn** [comment]
2024-08-23 22:30:01 INFO ======Location differ joblog from 2024-08-23 22:30:01=======
2024-08-23 22:49:51 INFO San Diego Trading Company got permanently removed
2024-08-23 22:52:08 INFO Location California (12/125): Changes in 1/760 machines found.
2024-08-23 23:11:36 INFO Galveston Fishing Pier is available again
2024-08-23 23:13:50 INFO Location Texas (26/125): Changes in 1/305 machines found.
2024-08-23 23:18:05 INFO 25/207: Found machine to be added: M.S. Dixie II
2024-08-23 23:19:14 INFO The World Famous Clown Motel is available again
2024-08-23 23:19:23 INFO Location Nevada (31/125): Changes in 2/207 machines found.
2024-08-23 23:20:54 INFO 7/124: Found machine to be added: Department of Forestry
2024-08-23 23:21:59 INFO Location Virginia (35/125): Changes in 1/124 machines found.
2024-08-23 23:30:02 INFO 172/202: Found machine to be added: Seabreeze Amusement Park
2024-08-23 23:30:14 INFO Location New York (43/125): Changes in 1/202 machines found.
2024-08-23 23:33:13 INFO Yogi Bear Jellystone Park is currently unavailable
2024-08-23 23:33:59 INFO WIS-CO / Suzie's Sweets is available again
2024-08-23 23:34:21 INFO Location Wisconsin (47/125): Changes in 2/121 machines found.
2024-08-23 23:55:35 INFO Bar Rione Monti di Palmisano Caterina is currently unavailable
2024-08-23 23:55:37 INFO Via Indipendenza 1 is available again
2024-08-23 23:55:59 INFO Vi-Ta Playtime! Gadget and Souvenir is currently unavailable
2024-08-23 23:56:14 INFO Antica Sartoria is currently unavailable
2024-08-23 23:56:16 INFO 68/143: Found machine to be added: Ottica Glamour
2024-08-23 23:57:08 INFO Location Italy (82/125): Changes in 5/143 machines found.
2024-08-24 00:13:11 INFO 
 Result: 13 changes, 8 new machines found and 4 machines retired
2024-08-24 00:30:02 ERROR Found 3 problems that require manual intervention
2024-08-24 00:30:02 INFO ======Location differ completed at 2024-08-24 00:30:02=======
2024-08-24 00:30:03 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-08-24 22:30:02 INFO ======Location differ joblog from 2024-08-24 22:30:02=======
2024-08-24 22:49:55 INFO Sierra at Tahoe Ski Resort is currently unavailable
2024-08-24 22:50:24 INFO Location California (12/125): Changes in 1/760 machines found.
2024-08-24 23:38:50 INFO 140/149: Found machine to be added: Prince Rupert Dock
2024-08-24 23:38:52 INFO Location Canada (61/125): Changes in 1/149 machines found.
2024-08-24 23:56:11 INFO 12/219: Found machine to be added: Isumi Railway Ohara Station
2024-08-24 23:59:03 INFO Location Japan (84/125): Changes in 1/219 machines found.
2024-08-25 00:07:50 INFO 57/185: Found machine to be added: El Burgo de Osma (Soria) 
2024-08-25 00:09:53 INFO Location Spain (112/125): Changes in 1/185 machines found.
2024-08-25 00:12:25 INFO 
 Result: 4 changes, 3 new machines found and 1 machines retired
2024-08-25 00:29:19 ERROR Found 3 problems that require manual intervention
2024-08-25 00:29:19 INFO ======Location differ completed at 2024-08-25 00:29:19=======
2024-08-25 00:29:20 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7446 named International Mermaid Museum submitted.

**Pull request closed without merging**
