### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 1497 "The Guards Museum":
	Address from: Wellington Barracks, Birdcage Walk, Westminster, London to: Wellington Barracks, Birdcage Walk, LONDON - Westminster

### CODE REVIEW

**Comment by NinaWie** [comment]
New machine 7447 named Dells mining company submitted.

**Comment by NinaWie** [comment]
New machine 7448 named Dells mining company submitted.

**Comment by NinaWie** [comment]
New machine 7449 named OWA Gift Shop (located inside the park) submitted.

**Comment by jannisborn** [comment]
2024-08-28 10:59:55 INFO ======Location differ joblog from 2024-08-28 10:59:55=======
2024-08-28 11:05:00 INFO 30/68: Found machine to be added: Cobblestone Creamery 
2024-08-28 11:05:27 INFO Location Oklahoma (5/125): Changes in 1/68 machines found.
2024-08-28 11:07:00 INFO Dairy Queen Sedona is available again
2024-08-28 11:07:25 INFO Tombstone Ghosts & Legends Tour is available again
2024-08-28 11:07:35 INFO Saguaro National Park is available again
2024-08-28 11:07:44 INFO Last Stop Travel Center is available again
2024-08-28 11:08:04 INFO Location Arizona (6/125): Changes in 4/224 machines found.
2024-08-28 11:09:34 INFO 50/133: Found machine to be added: Wildlife Images
2024-08-28 11:10:23 INFO Location Oregon (8/125): Changes in 1/133 machines found.
2024-08-28 11:10:42 INFO 33/56: Found machine to be added: Clinton Presidential Center
2024-08-28 11:10:56 INFO Location Arkansas (9/125): Changes in 1/56 machines found.
2024-08-28 11:11:09 INFO 13/92: Found machine to be added: Old South Meeting House
2024-08-28 11:11:43 INFO Legoland Discovery Center is currently unavailable
2024-08-28 11:11:55 INFO Location Massachusetts (10/125): Changes in 2/92 machines found.
2024-08-28 11:13:00 INFO 93/218: Found machine to be added: Raystown Lake Welcome Center
2024-08-28 11:13:16 INFO 124/218: Found machine to be added: Meyersdale Area Historical Society
2024-08-28 11:13:43 INFO 160/218: Found machine to be added: Acrisure Stadium
2024-08-28 11:14:18 INFO 217/218: Found machine to be added: Yorktown Hotel
2024-08-28 11:14:18 INFO Location Pennsylvania (11/125): Changes in 4/218 machines found.
2024-08-28 11:17:52 INFO 386/761: Found machine to be added: Pismo Coast Village RV Resort
2024-08-28 11:18:33 INFO Old Town - Dantes Leather is available again
2024-08-28 11:18:43 INFO San Diego Trading Company got permanently removed
2024-08-28 11:19:16 INFO Japantown - Katachi (Anime & Sword Shop) is available again
2024-08-28 11:20:11 INFO Blue Pebbles is available again
2024-08-28 11:20:15 INFO 712/761: Found machine to be added: Empanash 
2024-08-28 11:20:17 INFO Sierra at Tahoe Ski Resort is currently unavailable
2024-08-28 11:20:45 INFO Location California (12/125): Changes in 7/761 machines found.
2024-08-28 11:23:25 INFO Breck 'N' Boujee  is currently unavailable
2024-08-28 11:25:33 INFO Location Colorado (15/125): Changes in 1/220 machines found.
2024-08-28 11:25:41 INFO Mall of America - Legacy Toys is currently unavailable
2024-08-28 11:26:19 INFO Itasca State Park is currently unavailable
2024-08-28 11:26:43 INFO Location Minnesota (16/125): Changes in 2/106 machines found.
2024-08-28 11:26:49 INFO Palmettoville is currently unavailable
2024-08-28 11:27:22 INFO 61/105: Found machine to be added: Broadway Grand Prix
2024-08-28 11:27:44 INFO Location South Carolina (17/125): Changes in 2/105 machines found.
2024-08-28 11:30:11 INFO Sunshine T-Shirt and Souvenirs is currently unavailable
2024-08-28 11:30:22 INFO Boomland Fireworks Gifts & Collectibles  is available again
2024-08-28 11:30:26 INFO 69/180: Found machine to be added: Grand River Historical Society & Museum
2024-08-28 11:30:45 INFO 99/180: Found machine to be added: Joplin History and Mineral Museum
2024-08-28 11:31:41 INFO Location Missouri (22/125): Changes in 4/180 machines found.
2024-08-28 11:32:35 INFO 68/201: Found machine to be added: Nashville Shores Lakeside Resort  
2024-08-28 11:33:06 INFO 110/201: Found machine to be added: GO USA Fun Park
2024-08-28 11:33:10 INFO Country Music Hall of Fame and Museum is available again
2024-08-28 11:34:04 INFO Location Tennessee (23/125): Changes in 3/201 machines found.
2024-08-28 11:37:10 INFO 288/388: Found machine to be added: Worlds Largest Entertainment McDonalds
2024-08-28 11:38:10 INFO Location Florida (24/125): Changes in 1/388 machines found.
2024-08-28 11:40:13 INFO Galveston Fishing Pier is available again
2024-08-28 11:41:16 INFO 202/305: Found machine to be added: Museum of the Southwest
2024-08-28 11:42:22 INFO Baylor Bear Habitat  is available again
2024-08-28 11:42:29 INFO Location Texas (26/125): Changes in 3/305 machines found.
2024-08-28 11:45:12 INFO Simply Moab (was Dirt Shirts) is available again
2024-08-28 11:45:41 INFO Location Utah (29/125): Changes in 1/101 machines found.
2024-08-28 11:46:44 INFO 25/207: Found machine to be added: M.S. Dixie II
2024-08-28 11:47:49 INFO Primm Valley Resort & Casino is currently unavailable
2024-08-28 11:47:53 INFO The World Famous Clown Motel is available again
2024-08-28 11:48:02 INFO Location Nevada (31/125): Changes in 3/207 machines found.
2024-08-28 11:49:14 INFO 20/40: Found machine to be added: Loon Mountain Resort 
2024-08-28 11:49:31 INFO Location New Hampshire (34/125): Changes in 1/40 machines found.
2024-08-28 11:49:42 INFO 7/124: Found machine to be added: Department of Forestry
2024-08-28 11:49:47 INFO 14/124: Found machine to be added: National Museum of the United States Army 
2024-08-28 11:50:04 INFO 39/124: Found machine to be added: Massanutten Resort 
2024-08-28 11:50:56 INFO Location Virginia (35/125): Changes in 3/124 machines found.
2024-08-28 11:51:22 INFO Griffin Museum of Science + Industry (Museum of Science & Industry, MSI is available again
2024-08-28 11:52:23 INFO Location Illinois (36/125): Changes in 1/139 machines found.
2024-08-28 11:52:59 INFO Located somewhere in Historic Smithville is currently unavailable
2024-08-28 11:53:06 INFO Location New Jersey (37/125): Changes in 1/99 machines found.
2024-08-28 11:57:17 INFO 27/42: Found machine to be added: Mahanay Memorial Carillon Tower
2024-08-28 11:57:27 INFO Location Iowa (42/125): Changes in 1/42 machines found.
2024-08-28 11:59:02 INFO 172/203: Found machine to be added: Seabreeze Amusement Park
2024-08-28 11:59:15 INFO Location New York (43/125): Changes in 1/203 machines found.
2024-08-28 11:59:26 INFO 10/39: Found machine to be added: Capital Market
2024-08-28 11:59:44 INFO Location West Virginia (44/125): Changes in 1/39 machines found.
2024-08-28 12:02:16 INFO Yogi Bear Jellystone Park is currently unavailable
2024-08-28 12:03:03 INFO WIS-CO / Suzie's Sweets is available again
2024-08-28 12:03:26 INFO Location Wisconsin (47/125): Changes in 2/121 machines found.
2024-08-28 12:07:10 INFO 57/60: Found machine to be added: Wörschach
2024-08-28 12:07:12 INFO Location Austria (54/125): Changes in 1/60 machines found.
2024-08-28 12:08:26 INFO End of the Thread Cafe is currently unavailable
2024-08-28 12:09:21 INFO 140/149: Found machine to be added: Prince Rupert Dock
2024-08-28 12:09:23 INFO Location Canada (61/125): Changes in 2/149 machines found.
2024-08-28 12:11:16 INFO Boscombe Pier is currently unavailable
2024-08-28 12:12:38 INFO King's Cross Railroad Station is available again
2024-08-28 12:14:11 INFO 351/444: Found machine to be added: Fishermans Cottage 
2024-08-28 12:15:04 INFO Emmerdale Studio Experience Tour (Emmerdale Production Centre) is currently unavailable
2024-08-28 12:15:11 INFO Location England (69/125): Changes in 4/444 machines found.
2024-08-28 12:17:17 INFO 7/392: Found machine to be added: Aschaffenburg Information Center 
2024-08-28 12:22:52 INFO Location Germany (73/125): Changes in 1/392 machines found.
2024-08-28 12:23:07 INFO 7/15: Found machine to be added: Santorini/Thira
2024-08-28 12:23:12 INFO Location Greece (75/125): Changes in 1/15 machines found.
2024-08-28 12:25:01 INFO 6/43: Found machine to be added: The Queenstown Story
2024-08-28 12:25:16 INFO Location Ireland (80/125): Changes in 1/43 machines found.
2024-08-28 12:25:20 INFO Bar Rione Monti di Palmisano Caterina is currently unavailable
2024-08-28 12:25:21 INFO Via Indipendenza 1 is available again
2024-08-28 12:25:44 INFO Vi-Ta Playtime! Gadget and Souvenir is currently unavailable
2024-08-28 12:25:59 INFO Antica Sartoria is currently unavailable
2024-08-28 12:26:01 INFO 68/143: Found machine to be added: Ottica Glamour
2024-08-28 12:26:13 INFO Ricordi Pompeiani di Antonio Cestra is available again
2024-08-28 12:26:30 INFO Edicola Pantheon (Newspaper kiosk) is available again
2024-08-28 12:26:53 INFO Location Italy (82/125): Changes in 7/143 machines found.
2024-08-28 12:27:10 INFO 12/219: Found machine to be added: Isumi Railway Ohara Station
2024-08-28 12:27:43 INFO 46/219: Found machine to be added: Hakone Kowakien Yunessun
2024-08-28 12:30:05 INFO Location Japan (84/125): Changes in 2/219 machines found.
2024-08-28 12:31:36 INFO 20/31: Found machine to be added: Zoológico de Chapultepec 
2024-08-28 12:31:43 INFO Location Mexico (93/125): Changes in 1/31 machines found.
2024-08-28 12:32:44 INFO Distance match - Seeems that machine Focus Lemmer at Kortestreek 5, Lemmer already exists as: Lemmer Souvenir Winkel Focus
 Overwriting link http://www.elongated-coin.de/phpBB3/viewtopic.php?t=20730
2024-08-28 12:34:17 INFO 0/5: Found machine to be added: Atlanterhavsparken (Atlantic Sea-Park)
2024-08-28 12:34:19 INFO Location Norway (97/125): Changes in 1/5 machines found.
2024-08-28 12:34:32 INFO 6/15: Found machine to be added: The Archeological Museum of Krakow
2024-08-28 12:34:39 INFO 12/15: Found machine to be added: Gubalówka Funicular Railway
2024-08-28 12:34:41 INFO Location Poland (100/125): Changes in 2/15 machines found.
2024-08-28 12:35:48 INFO 66/75: Found machine to be added: Marina Souvenirs
2024-08-28 12:35:54 INFO Location Portugal (101/125): Changes in 1/75 machines found.
2024-08-28 12:36:49 INFO Camera Obscura  is currently unavailable
2024-08-28 12:37:00 INFO Seems that machine Nelson Monument already exists as: Nelson’s Monument
2024-08-28 12:37:02 INFO The Scott Monument is currently unavailable
2024-08-28 12:37:03 INFO Nevis Range, Fort William is available again
2024-08-28 12:37:30 INFO Location Scotland (2667/125): Changes in 3/94 machines found.
2024-08-28 12:38:18 INFO 2/11: Found machine to be added: Sea Life Busan Aquarium
2024-08-28 12:38:24 INFO Location South Korea (111/125): Changes in 1/11 machines found.
2024-08-28 12:39:12 INFO Distance match - Seeems that machine Souvenir store near the Cathedral  at Pl. Mayor, 9, 16001 Cuenca, Cuenca already exists as: Artesana shop
2024-08-28 12:39:16 INFO 57/186: Found machine to be added: El Burgo de Osma (Soria) 
2024-08-28 12:40:11 INFO 122/186: Found machine to be added: Pontevedra, Albergues Virxe Peregrina
2024-08-28 12:40:39 INFO 153/186: Found machine to be added: Don Caramelo
2024-08-28 12:41:08 INFO Location Spain (1086/125): Changes in 3/186 machines found.
2024-08-28 12:41:41 INFO 24/27: Found machine to be added: Sunnegga Train Station
2024-08-28 12:41:44 INFO Location Switzerland (117/125): Changes in 1/27 machines found.
2024-08-28 12:43:47 INFO 
 Result: 83 changes, 64 new machines found and 18 machines retired
2024-08-28 12:56:12 ERROR Our machine Fishing Bridge General Store in Montana from Device shown as available but http://209.221.138.252/Details.aspx?location=320044 responds Internal Server Error (500)
2024-08-28 12:56:14 ERROR Our machine Yellowstone - Canyon Village General Store in Wyoming from Server shown as available but http://209.221.138.252/Details.aspx?location=833 responds Internal Server Error (500)
2024-08-28 13:00:32 ERROR Our machine Atlanterhavsparken, The Atlantic Sea Park in Norway from Server shown as retired but http://209.221.138.252/Details.aspx?location=112265 responds Internal Server Error (500)
2024-08-28 13:04:03 ERROR Our machine News kiosk in Italy from Server shown as available but http://209.221.138.252/Details.aspx?location=432242 responds Internal Server Error (500)
2024-08-28 13:04:06 ERROR Found 3 problems that require manual intervention
2024-08-28 13:04:06 INFO ======Location differ completed at 2024-08-28 13:04:06=======
2024-08-28 13:04:07 INFO Detected change in server_locations.json - push to github

**Review by jannisborn — APPROVED** [review]

**Pull request merged**
