### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 381 "Welcome / Tourist Center":
	Status from: available to: retired
	Title from: Welcome / Tourist Center  to: Welcome / Tourist Center

### CODE REVIEW

**Comment by jannisborn** [comment]
2024-09-30 07:42:54 INFO ======Location differ joblog from 2024-09-30 07:42:54=======
2024-09-30 08:12:38 INFO 4/184: Found machine to be added: Alex and Alainas Treasure Chest
2024-09-30 08:13:42 INFO 112/184: Found machine to be added: Supernatural Body Piercing
2024-09-30 08:14:34 INFO Location Missouri (22/125): Changes in 2/184 machines found.
2024-09-30 08:30:58 INFO Rustic Rope NTreasures  is currently unavailable
2024-09-30 08:31:01 INFO Location Nevada (31/125): Changes in 1/208 machines found.
2024-09-30 08:38:19 INFO 102/104: Found machine to be added: The Play Zone
2024-09-30 08:38:20 INFO Location Indiana (39/125): Changes in 1/104 machines found.
2024-09-30 08:50:52 INFO 27/151: Found machine to be added: Gary's Lock & Security Shop Ltd
2024-09-30 08:51:56 INFO Location Canada (61/125): Changes in 1/151 machines found.
2024-09-30 09:12:06 INFO 197/222: Found machine to be added: Tsukuba Expo Center
2024-09-30 09:12:22 INFO Location Japan (84/125): Changes in 1/222 machines found.
2024-09-30 09:20:45 INFO 25/190: Found machine to be added: Temple of the Sacred Heart of Jesus
2024-09-30 09:20:50 INFO Sagrada Família is available again
2024-09-30 09:23:03 INFO Location Spain (112/125): Changes in 2/190 machines found.
2024-09-30 09:25:34 INFO 
 Result: 8 changes, 7 new machines found and 1 machines retired
2024-09-30 09:41:07 ERROR Found 3 problems that require manual intervention
2024-09-30 09:41:07 INFO ======Location differ completed at 2024-09-30 09:41:07=======
2024-09-30 09:41:08 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7571 named Rosicrucian Egyptian Museum submitted.

**Comment by NinaWie** [comment]
New machine 7572 named Kiosko La Catedrale submitted.

**Comment by jannisborn** [comment]
No website updates today!

**Comment by NinaWie** [comment]
New machine 7573 named Los arcos artesania submitted.

**Comment by jannisborn** [comment]
2024-10-01 22:30:01 INFO ======Location differ joblog from 2024-10-01 22:30:01=======
2024-10-01 22:33:17 INFO The Cone in West Chester is currently unavailable
2024-10-01 22:33:25 INFO Location Ohio (2/125): Changes in 1/138 machines found.
2024-10-02 00:14:13 INFO 
 Result: 1 changes, 0 new machines found and 1 machines retired
2024-10-02 00:29:45 ERROR Found 3 problems that require manual intervention
2024-10-02 00:29:45 INFO ======Location differ completed at 2024-10-02 00:29:45=======
2024-10-02 00:29:46 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-10-02 22:30:02 INFO ======Location differ joblog from 2024-10-02 22:30:02=======
2024-10-02 23:17:06 INFO Crazy Ely Mini-Mart Souvenirs  is currently unavailable
2024-10-02 23:18:15 INFO Location Nevada (31/125): Changes in 1/208 machines found.
2024-10-03 00:13:38 INFO 
 Result: 1 changes, 0 new machines found and 1 machines retired
2024-10-03 00:29:13 ERROR Found 3 problems that require manual intervention
2024-10-03 00:29:13 INFO ======Location differ completed at 2024-10-03 00:29:13=======
2024-10-03 00:29:14 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-10-03 22:30:01 INFO ======Location differ joblog from 2024-10-03 22:30:01=======
2024-10-04 00:08:18 INFO Distance match - Seeems that machine BLS Schifffahrt / Boat Pier at Quai 1, Brienz already exists as: Brienz Lake Quai
2024-10-04 00:09:40 INFO Istanbul Toy Museum (Oyuncak Müzesi) is currently unavailable
2024-10-04 00:09:40 INFO Location Turkey (120/125): Changes in 1/5 machines found.
2024-10-04 00:10:35 INFO 
 Result: 1 changes, 0 new machines found and 1 machines retired
2024-10-04 00:26:08 ERROR Found 3 problems that require manual intervention
2024-10-04 00:26:08 INFO ======Location differ completed at 2024-10-04 00:26:08=======
2024-10-04 00:26:09 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-10-04 22:30:01 INFO ======Location differ joblog from 2024-10-04 22:30:01=======
2024-10-04 22:53:37 ERROR Geolocation failed for: Unknown business or location	 sub: , Rose Island
2024-10-04 23:15:12 INFO Thanksgiving Point - Butterfly Biosphere is available again
2024-10-04 23:15:14 INFO Thanksgiving Point - The Natural Curiosity Museum is available again
2024-10-04 23:15:50 INFO Location Utah (29/125): Changes in 2/103 machines found.
2024-10-04 23:16:52 INFO Area 15 is available again
2024-10-04 23:18:06 INFO Location Nevada (31/125): Changes in 1/208 machines found.
2024-10-05 00:11:39 INFO 
 Result: 3 changes, 3 new machines found and 0 machines retired
2024-10-05 00:26:56 ERROR Found 4 problems that require manual intervention
2024-10-05 00:26:56 INFO ======Location differ completed at 2024-10-05 00:26:56=======
2024-10-05 00:26:57 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
New problems require attention.

**Review by jannisborn — APPROVED** [review]
New problem can stay in problems -- it's not a problem with our scripts, the entry is corrupted on the website

**Pull request merged**
