### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 5366 "Buc-ee's":
	Status from: available to: out-of-order

### CODE REVIEW

**Comment by jannisborn** [comment]
2024-03-25 22:30:02 INFO ======Location differ joblog from 2024-03-25 22:30:02=======
2024-03-25 22:39:47 INFO Costco is available again
2024-03-25 22:39:51 INFO Location Oregon (8/125): Changes in 1/129 machines found.
2024-03-25 23:15:53 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-03-25 23:23:22 INFO 59/91: Found machine to be added: Apsen Copies
2024-03-25 23:23:43 INFO Location New Mexico (40/125): Changes in 1/91 machines found.
2024-03-25 23:50:50 INFO 46/138: Found machine to be added: Livorno - Acquario di Livorno
2024-03-25 23:51:55 INFO Location Italy (82/125): Changes in 1/138 machines found.
2024-03-26 00:07:01 INFO 
 Result: 3 changes, 3 new machines found and 0 machines retired
2024-03-26 00:21:18 ERROR Found 4 problems that require manual intervention
2024-03-26 00:21:18 INFO ======Location differ completed at 2024-03-26 00:21:18=======
2024-03-26 00:21:19 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7108 named Disney Springs Town Square Firehouse submitted.

**Comment by jannisborn** [comment]
2024-03-26 22:30:02 INFO ======Location differ joblog from 2024-03-26 22:30:02=======
2024-03-26 23:08:25 INFO Moody Gardens Zoo and Aquarium is currently unavailable
2024-03-26 23:10:28 INFO Location Texas (26/125): Changes in 1/296 machines found.
2024-03-26 23:13:17 INFO Zion Park Gifts and Sweet Treats is currently unavailable
2024-03-26 23:13:26 INFO Location Utah (29/125): Changes in 1/97 machines found.
2024-03-26 23:14:51 INFO Harmon Corner - Rainforest Café is currently unavailable
2024-03-26 23:15:42 INFO Location Nevada (31/125): Changes in 1/204 machines found.
2024-03-26 23:15:57 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-03-26 23:38:34 INFO Dreamland Margate  is currently unavailable
2024-03-26 23:41:18 INFO Location England (69/125): Changes in 1/436 machines found.
2024-03-26 23:46:47 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=22871': HTTPConnectionPool(host='209.221.138.252', port=80): Max retries exceeded with url: /Details.aspx?location=22871 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7db13aec10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-03-26 23:46:57 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=420364': HTTPConnectionPool(host='209.221.138.252', port=80): Max retries exceeded with url: /Details.aspx?location=420364 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7db1a922b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-03-27 00:07:26 INFO 
 Result: 4 changes, 0 new machines found and 4 machines retired
2024-03-27 00:21:48 ERROR Found 4 problems that require manual intervention
2024-03-27 00:21:48 INFO ======Location differ completed at 2024-03-27 00:21:48=======
2024-03-27 00:21:49 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
No website updates today!

**Pull request merged**
