### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
New machine 7217 named Tamarack submitted.

### CODE REVIEW

**Comment by jannisborn** [comment]
No website updates today!

**Comment by NinaWie** [comment]
New machine 7218 named Texas Beat Smokehouse submitted.

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
2024-06-18 22:30:01 INFO ======Location differ joblog from 2024-06-18 22:30:01=======
2024-06-18 22:46:43 INFO 56/756: Found machine to be added: Scenic Outfitters 
2024-06-18 22:53:14 INFO Location California (12/125): Changes in 1/756 machines found.
2024-06-18 22:58:15 INFO 189/219: Found machine to be added: Red Feather Trading Post
2024-06-18 22:58:27 INFO Location Colorado (15/125): Changes in 1/219 machines found.
2024-06-18 23:02:06 INFO 45/86: Found machine to be added: The Emporium
2024-06-18 23:02:38 INFO Location South Dakota (20/125): Changes in 1/86 machines found.
2024-06-18 23:11:48 INFO 9/47: Found machine to be added: Yellowstone Trading Post
2024-06-18 23:12:23 INFO Location Montana (25/125): Changes in 1/47 machines found.
2024-06-18 23:13:20 INFO 69/299: Found machine to be added: Daingerfield State Park
2024-06-18 23:16:14 INFO Location Texas (26/125): Changes in 1/299 machines found.
2024-06-18 23:27:59 INFO Distance match - Seeems that machine Ovation of the Seas (Royal Caribbean Cruise ship) at , Seattle already exists as: Royal Caribbean International
2024-06-18 23:44:10 INFO 2/23: Found machine to be added: Chateau Cejkovice
2024-06-18 23:44:21 INFO Location Czech Republic (66/125): Changes in 1/23 machines found.
2024-06-18 23:58:43 INFO 64/80: Found machine to be added: Castle Sümeg
2024-06-18 23:58:59 INFO Location Hungary (78/125): Changes in 1/80 machines found.
2024-06-19 00:08:11 INFO Atlanterhavsparken (Atlantic Sea-Park) is currently unavailable
2024-06-19 00:08:13 INFO Location Norway (97/125): Changes in 1/5 machines found.
2024-06-19 00:17:11 INFO 
 Result: 8 changes, 7 new machines found and 1 machines retired
2024-06-19 00:28:02 ERROR Our machine Old Faithful General Store in Montana from Device shown as available but http://209.221.138.252/Details.aspx?location=319910 responds Internal Server Error (500)
2024-06-19 00:28:02 ERROR Our machine Yellowstone - Old Faithful General Store in Wyoming from Server shown as available but http://209.221.138.252/Details.aspx?location=663 responds Internal Server Error (500)
2024-06-19 00:33:45 ERROR Found 3 problems that require manual intervention
2024-06-19 00:33:45 INFO ======Location differ completed at 2024-06-19 00:33:45=======
2024-06-19 00:33:46 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
No website updates today!

**Review by jannisborn — APPROVED** [review]

**Pull request merged**
