### PR TITLE
Updates from website (server_locations)

### PR DESCRIPTION
**Pull request by jannisborn**
2024-01-15 22:30:07 INFO ======Location differ joblog from 2024-01-15 22:30:07=======
2024-01-15 23:03:12 INFO Cooter's Place is available again
2024-01-15 23:03:44 INFO Location Tennessee (23/125): Changes in 1/197 machines found.
2024-01-15 23:17:34 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-01-15 23:54:08 INFO 75/137: Found machine to be added: Arredi e Paramenti Sacri Articoli Religiosi
2024-01-15 23:54:45 INFO Location Italy (82/125): Changes in 1/137 machines found.
2024-01-16 00:11:22 INFO 
 Result: 2 changes, 2 new machines found and 0 machines retired
2024-01-16 00:26:10 ERROR Found 5 problems that require manual intervention
2024-01-16 00:26:10 INFO ======Location differ completed at 2024-01-16 00:26:10=======
2024-01-16 00:26:11 INFO Detected change in server_locations.json - push to github

### CODE REVIEW

**Comment by NinaWie** [comment]
New machine 7038 named Millspring Bainbridge submitted.

**Comment by jannisborn** [comment]
2024-01-17 22:35:02 INFO ======Location differ joblog from 2024-01-17 22:35:02=======
2024-01-17 22:43:31 INFO 12/128: Found machine to be added: Millstream Bainbridge
2024-01-17 22:44:46 INFO Location Oregon (8/125): Changes in 1/128 machines found.
2024-01-17 23:19:12 INFO Excalibur Hotel & Casino - 24/7 Gift Shop & Food store is currently unavailable
2024-01-17 23:20:11 INFO Location Nevada (31/125): Changes in 1/203 machines found.
2024-01-17 23:20:25 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-01-17 23:29:53 INFO Madame Tussauds is currently unavailable
2024-01-17 23:30:36 INFO Location New York (43/125): Changes in 1/200 machines found.
2024-01-17 23:43:14 INFO M&Ms World is currently unavailable
2024-01-17 23:43:17 INFO KidZania is currently unavailable
2024-01-17 23:45:18 INFO Location England (69/125): Changes in 2/425 machines found.
2024-01-18 00:11:02 INFO 
 Result: 5 changes, 1 new machines found and 4 machines retired
2024-01-18 00:24:17 ERROR Found 5 problems that require manual intervention
2024-01-18 00:24:17 INFO ======Location differ completed at 2024-01-18 00:24:17=======
2024-01-18 00:24:18 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
Request change to machine 729 named Zermatt Train Station - Changed:
	Address from  to: Zermatt Bahnhof
	 Location from 46.0244, 7.7483 to: 46.0238, 7.7477

**Comment by NinaWie** [comment]
Request change to machine 726 named Rheinfall / Schloss Laufen - Changed:
	Multimachine from: 3 to: 1

**Comment by NinaWie** [comment]
Request change to machine 1593 named Wakehurst Place - Changed:
	Status from: available to: retired

**Comment by jannisborn** [comment]
2024-01-18 22:30:01 INFO ======Location differ joblog from 2024-01-18 22:30:01=======
2024-01-18 23:05:49 INFO 367/379: Found machine to be added: McKee Botanical Garden
2024-01-18 23:05:55 INFO Location Florida (24/125): Changes in 1/379 machines found.
2024-01-18 23:15:26 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-01-18 23:37:48 INFO Blackpool Pleasure Beach is currently unavailable
2024-01-18 23:40:29 INFO Location England (69/125): Changes in 1/425 machines found.
2024-01-18 23:45:28 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=404631': ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
2024-01-18 23:45:38 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=12868': HTTPConnectionPool(host='209.221.138.252', port=80): Max retries exceeded with url: /Details.aspx?location=12868 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f562a1679d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-18 23:49:34 INFO Bunratty Castle & Folk Park is available again
2024-01-18 23:49:52 INFO Location Ireland (80/125): Changes in 1/43 machines found.
2024-01-19 00:06:21 INFO 
 Result: 3 changes, 2 new machines found and 1 machines retired
2024-01-19 00:19:31 ERROR Found 5 problems that require manual intervention
2024-01-19 00:19:31 INFO ======Location differ completed at 2024-01-19 00:19:31=======
2024-01-19 00:19:32 INFO Detected change in server_locations.json - push to github

**Review by NinaWie — APPROVED** [review]

**Comment by NinaWie** [comment]
Request change to machine 4499 named Downtown Las Vegas - Golden Nugget Hotel Casino - Changed:
	Status from: available to: out-of-order

**Comment by jannisborn** [comment]
No website updates today!

**Pull request merged**
