### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
New machine 7203 named Ann & Alfred Goldstein building 2 submitted.

### CODE REVIEW

**Comment by jannisborn** [comment]
2024-06-09 22:30:02 INFO ======Location differ joblog from 2024-06-09 22:30:02=======
2024-06-09 23:59:25 INFO W5 @ Odessey, The Odyssey is available again
2024-06-09 23:59:28 INFO Location Northern Ireland (96/125): Changes in 1/11 machines found.
2024-06-10 00:07:57 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-06-10 00:23:14 ERROR Found 3 problems that require manual intervention
2024-06-10 00:23:14 INFO ======Location differ completed at 2024-06-10 00:23:14=======
2024-06-10 00:23:15 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-06-10 22:30:02 INFO ======Location differ joblog from 2024-06-10 22:30:02=======
2024-06-10 22:56:09 INFO 2nd Avenue Fishing Pier is currently unavailable
2024-06-10 22:56:33 INFO Lost Treasure Golf (Professor Hacker's) is currently unavailable
2024-06-10 22:56:39 INFO Location South Carolina (17/125): Changes in 2/103 machines found.
2024-06-10 23:11:21 INFO Cinnamon Bear Country Store is currently unavailable
2024-06-10 23:11:29 INFO 104/129: Found machine to be added: Savannah/Hilton Head International Airport
2024-06-10 23:11:29 INFO The Cinnamon Bear Country Store is currently unavailable
2024-06-10 23:11:48 INFO Location Georgia (27/125): Changes in 3/129 machines found.
2024-06-11 00:06:57 INFO 
 Result: 5 changes, 1 new machines found and 4 machines retired
2024-06-11 00:21:55 ERROR Found 3 problems that require manual intervention
2024-06-11 00:21:55 INFO ======Location differ completed at 2024-06-11 00:21:55=======
2024-06-11 00:21:55 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-06-11 22:30:01 INFO ======Location differ joblog from 2024-06-11 22:30:01=======
2024-06-11 23:40:08 INFO Wollaton Hall Gift Shop is available again
2024-06-11 23:41:08 INFO Location England (69/125): Changes in 1/441 machines found.
2024-06-11 23:50:33 INFO Basile / Angela Flowers & Gifts is currently unavailable
2024-06-11 23:50:55 INFO Thinkart A di Tina Maragno Souvenir Shop is currently unavailable
2024-06-11 23:51:55 INFO Location Italy (82/125): Changes in 2/138 machines found.
2024-06-12 00:07:07 INFO 
 Result: 3 changes, 1 new machines found and 2 machines retired
2024-06-12 00:22:24 ERROR Found 3 problems that require manual intervention
2024-06-12 00:22:24 INFO ======Location differ completed at 2024-06-12 00:22:24=======
2024-06-12 00:22:25 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-06-12 22:30:02 INFO ======Location differ joblog from 2024-06-12 22:30:02=======
2024-06-12 22:51:54 INFO 155/191: Found machine to be added: Klassic Arcade 3.0
2024-06-12 22:52:19 INFO Location Michigan (13/125): Changes in 1/191 machines found.
2024-06-12 23:16:50 INFO 25/41: Found machine to be added: Lakeside Lodge
2024-06-12 23:17:03 INFO Location Idaho (33/125): Changes in 1/41 machines found.
2024-06-12 23:19:14 INFO Griffin Museum of Science + Industry (Museum of Science & Industry, MSI is currently unavailable
2024-06-12 23:20:12 INFO Location Illinois (36/125): Changes in 1/137 machines found.
2024-06-12 23:29:52 INFO 32/120: Found machine to be added: The Beach Club  (On Madeline Island)
2024-06-12 23:30:49 INFO Location Wisconsin (47/125): Changes in 1/120 machines found.
2024-06-13 00:08:14 INFO 
 Result: 4 changes, 3 new machines found and 1 machines retired
2024-06-13 00:22:36 ERROR Our machine Tnning Multimar Wattforum in Germany from Server shown as available but http://www.elongated-coin.de/phpBB3/viewtopic.php?t=2950 responds Bad Gateway (502)
2024-06-13 00:23:38 ERROR Found 3 problems that require manual intervention
2024-06-13 00:23:38 INFO ======Location differ completed at 2024-06-13 00:23:38=======
2024-06-13 00:23:38 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7208 named Desert View Trading Post submitted.

**Comment by NinaWie** [comment]
New machine 7209 named Klassic Arcade 3.0 submitted.

**Comment by jannisborn** [comment]
2024-06-13 22:30:01 INFO ======Location differ joblog from 2024-06-13 22:30:01=======
2024-06-13 22:36:35 INFO Delgadillo's Snow Cap Drive In is currently unavailable
2024-06-13 22:37:31 INFO Location Arizona (6/125): Changes in 1/223 machines found.
2024-06-13 22:49:09 INFO 715/755: Found machine to be added: Coin-Op Game Room Temecula
2024-06-13 22:49:32 INFO Location California (12/125): Changes in 1/755 machines found.
2024-06-13 23:31:21 INFO Yellowstone - Old Faithful General Store is available again
2024-06-13 23:31:28 INFO Location Wyoming (50/125): Changes in 1/56 machines found.
2024-06-13 23:34:25 INFO Hopewell Rocks is currently unavailable
2024-06-13 23:35:22 INFO Location Canada (61/125): Changes in 1/146 machines found.
2024-06-13 23:36:05 INFO 1/5: Found machine to be added: Guinness World Records Museum
2024-06-13 23:36:07 INFO 2/5: Found machine to be added: Ripleys Believe It or Not Copenhagen
2024-06-13 23:36:08 INFO Location Denmark (67/125): Changes in 2/5 machines found.
2024-06-14 00:04:35 INFO 10/25: Found machine to be added: Ticket-Shop, Interlaken Souvenirs & Travel Services
2024-06-14 00:04:48 INFO Location Switzerland (117/125): Changes in 1/25 machines found.
2024-06-14 00:06:39 INFO 
 Result: 7 changes, 5 new machines found and 2 machines retired
2024-06-14 00:22:03 ERROR Found 3 problems that require manual intervention
2024-06-14 00:22:03 INFO ======Location differ completed at 2024-06-14 00:22:03=======
2024-06-14 00:22:04 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
No website updates today!

**Comment by NinaWie** [comment]
New machine 7214 named Coin machine submitted.

**Comment by NinaWie** [comment]
New machine 7215 named Serpent Mound submitted.

**Review by jannisborn — APPROVED** [review]

**Comment by jannisborn** [comment]
2024-06-15 22:30:59 INFO ======Location differ joblog from 2024-06-15 22:30:59=======
2024-06-15 22:37:37 INFO Historic Seligman Sundries is currently unavailable
2024-06-15 22:38:30 INFO Location Arizona (6/125): Changes in 1/223 machines found.
2024-06-15 22:50:39 INFO Boyne Mountain Resort is currently unavailable
2024-06-15 22:52:39 INFO Location Michigan (13/125): Changes in 1/191 machines found.
2024-06-15 23:08:49 INFO Moody Gardens Zoo and Aquarium is available again
2024-06-15 23:10:52 INFO Location Texas (26/125): Changes in 1/298 machines found.
2024-06-15 23:28:29 INFO Kitty Hawk Kites is available again
2024-06-15 23:28:58 INFO Location North Carolina (46/125): Changes in 1/164 machines found.
2024-06-15 23:50:22 INFO En Gedi National Park is currently unavailable
2024-06-15 23:50:22 INFO Baptismal Site on the Jordan River - Qasr al-Yahud is currently unavailable
2024-06-15 23:50:22 INFO  Gan Israel ("Garden of Israel") is currently unavailable
2024-06-15 23:50:22 INFO Mini Isarel is currently unavailable
2024-06-15 23:50:22 INFO King Solomon's Mines \ Timna is currently unavailable
2024-06-15 23:50:22 INFO Location Israel (81/125): Changes in 5/20 machines found.
2024-06-16 00:06:52 INFO 
 Result: 9 changes, 2 new machines found and 7 machines retired
2024-06-16 00:21:59 ERROR Found 3 problems that require manual intervention
2024-06-16 00:21:59 INFO ======Location differ completed at 2024-06-16 00:21:59=======
2024-06-16 00:22:00 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7216 named Desert View trading post submitted.

**Pull request merged**
