### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by jannisborn**
2024-03-19 22:30:01 INFO ======Location differ joblog from 2024-03-19 22:30:01=======
2024-03-19 22:52:28 INFO 6/218: Found machine to be added: Buc-ee's
2024-03-19 22:54:38 INFO Location Colorado (15/125): Changes in 1/218 machines found.
2024-03-19 22:57:21 INFO 19/25: Found machine to be added: Keith's Superstores
2024-03-19 22:57:25 INFO Location Mississippi (19/125): Changes in 1/25 machines found.
2024-03-19 23:16:06 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-03-19 23:56:20 INFO 17/29: Found machine to be added: Six Flags Mexico
2024-03-19 23:56:27 INFO Location Mexico (93/125): Changes in 1/29 machines found.
2024-03-20 00:07:02 INFO 
 Result: 3 changes, 3 new machines found and 0 machines retired
2024-03-20 00:09:20 ERROR Our machine Macau Tower in Macao from Device shown as available but http://209.221.138.252/Details.aspx?location=332442 responds Internal Server Error (500)
2024-03-20 00:11:25 ERROR Our machine Tsudanomatsubara SA (Heading Kobe) in Japan from Device shown as available but http://209.221.138.252/Details.aspx?location=315378 responds Internal Server Error (500)
2024-03-20 00:11:54 ERROR Our machine Kanazawa Zoo in Japan from Device shown as available but http://209.221.138.252/Details.aspx?location=63701 responds Internal Server Error (500)
2024-03-20 00:15:48 ERROR Our machine Hitsujigaoka Observation Hill in Japan from Device shown as available but http://209.221.138.252/Details.aspx?location=279887 responds Internal Server Error (500)
2024-03-20 00:19:30 ERROR Our machine Disney Store, Shibuya Koen-dori in Japan from Server shown as retired but http://209.221.138.252/Details.aspx?location=371106 responds Internal Server Error (500)
2024-03-20 00:21:17 ERROR Found 5 problems that require manual intervention
2024-03-20 00:21:17 INFO ======Location differ completed at 2024-03-20 00:21:17=======
2024-03-20 00:21:18 INFO Detected change in server_locations.json - push to github

### CODE REVIEW

**Comment by jannisborn** [comment]
2024-03-20 22:30:01 INFO ======Location differ joblog from 2024-03-20 22:30:01=======
2024-03-20 22:52:52 INFO Estate Collectibles, Citadel Mall Upper Level  is currently unavailable
2024-03-20 22:54:47 INFO Location Colorado (15/125): Changes in 1/218 machines found.
2024-03-20 23:16:27 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-03-20 23:17:41 INFO Michie Tavern, General Store is currently unavailable
2024-03-20 23:18:50 INFO Location Virginia (35/125): Changes in 1/121 machines found.
2024-03-21 00:07:29 INFO 
 Result: 2 changes, 0 new machines found and 2 machines retired
2024-03-21 00:21:38 ERROR Found 4 problems that require manual intervention
2024-03-21 00:21:38 INFO ======Location differ completed at 2024-03-21 00:21:38=======
2024-03-21 00:21:39 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
New problems require attention.

**Review by NinaWie — APPROVED** [review]
@jannisborn, could you double check regarding the new machine in the `problems.json` file? I assume it's fine since it's just a new machine listed on the website, where the link does not work though?

**Comment by jannisborn** [comment]
It's not a new problem. It's one problem less, so good news and nothing to do :)

**Comment by NinaWie** [comment]
Ah seems like I wasn't fully awake this morning. Sorry

**Pull request merged**
