### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 1054 "Branson Landing":
	Status from: available to: retired

### CODE REVIEW

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
2024-09-13 22:43:06 INFO ======Location differ joblog from 2024-09-13 22:43:06=======
2024-09-13 23:07:52 INFO Steamboat Trading Company is currently unavailable
2024-09-13 23:07:57 INFO Location Colorado (15/125): Changes in 1/220 machines found.
2024-09-13 23:09:27 INFO Harbourtown Lighthouse is currently unavailable
2024-09-13 23:10:02 INFO Location South Carolina (17/125): Changes in 1/105 machines found.
2024-09-13 23:20:25 INFO C.M. Russell Museum got permanently removed
2024-09-13 23:20:47 INFO Location Montana (25/125): Changes in 1/47 machines found.
2024-09-13 23:27:12 INFO 61/103: Found machine to be added: Red Canyon Visitor Center
2024-09-13 23:27:34 INFO Location Utah (29/125): Changes in 1/103 machines found.
2024-09-13 23:28:41 INFO 40/208: Found machine to be added: Caesars Place Hotel Casino
2024-09-13 23:28:56 INFO Excalibur Hotel & Casino - Broken Knee across from the food court is currently unavailable
2024-09-13 23:29:50 INFO Location Nevada (31/125): Changes in 2/208 machines found.
2024-09-14 00:22:41 INFO 
 Result: 6 changes, 2 new machines found and 3 machines retired
2024-09-14 00:39:14 ERROR Found 3 problems that require manual intervention
2024-09-14 00:39:14 INFO ======Location differ completed at 2024-09-14 00:39:14=======
2024-09-14 00:39:14 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7531 named Penny Souvenir Ortigia submitted.

**Comment by jannisborn** [comment]
2024-09-14 22:30:01 INFO ======Location differ joblog from 2024-09-14 22:30:01=======
2024-09-14 22:36:07 INFO Luke Air Force Base / Luke AFB Public Affairs is currently unavailable
2024-09-14 22:37:52 INFO Location Arizona (6/125): Changes in 1/224 machines found.
2024-09-14 23:21:59 INFO 46/134: Found machine to be added: National Park Inn General Store
2024-09-14 23:22:55 INFO Location Washington (38/125): Changes in 1/134 machines found.
2024-09-15 00:09:38 INFO 
 Result: 2 changes, 1 new machines found and 1 machines retired
2024-09-15 00:26:05 ERROR Found 3 problems that require manual intervention
2024-09-15 00:26:05 INFO ======Location differ completed at 2024-09-15 00:26:05=======
2024-09-15 00:26:05 INFO Detected change in server_locations.json - push to github

**Review by jannisborn — APPROVED** [review]

**Comment by NinaWie** [comment]
New machine 7533 named Conway scenic railroad submitted.

**Comment by jannisborn** [comment]
2024-09-15 22:30:02 INFO ======Location differ joblog from 2024-09-15 22:30:02=======
2024-09-15 23:18:01 INFO Conway Scenic Railway is available again
2024-09-15 23:18:11 INFO Location New Hampshire (34/125): Changes in 1/40 machines found.
2024-09-15 23:42:14 INFO 386/448: Found machine to be added: Chessington Safari Hotel
2024-09-15 23:42:49 INFO Location England (69/125): Changes in 1/448 machines found.
2024-09-15 23:46:26 INFO 122/396: Found machine to be added: Beach Eckernförde
2024-09-15 23:47:36 INFO 202/396: Found machine to be added: Kiel Welcome Center
2024-09-15 23:49:35 INFO Distance match - Seeems that machine Shopping Street at , St. Peter Ording already exists as: St. Peter Ording
2024-09-15 23:49:41 INFO 343/396: Found machine to be added: Beach Surendorf
2024-09-15 23:50:26 INFO Location Germany (1013/125): Changes in 3/396 machines found.
2024-09-16 00:10:22 INFO 
 Result: 5 changes, 5 new machines found and 0 machines retired
2024-09-16 00:27:00 ERROR Found 3 problems that require manual intervention
2024-09-16 00:27:00 INFO ======Location differ completed at 2024-09-16 00:27:00=======
2024-09-16 00:27:01 INFO Detected change in server_locations.json - push to github

**Pull request merged**
