### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 3650 "Capitol Visitor's Center":
	Status from: available to: out-of-order

### CODE REVIEW

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
2024-03-07 22:30:02 INFO ======Location differ joblog from 2024-03-07 22:30:02=======
2024-03-07 22:40:02 INFO 4/55: Found machine to be added: Faulker County History Museum
2024-03-07 22:40:31 INFO Location Arkansas (9/125): Changes in 1/55 machines found.
2024-03-07 23:19:09 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-03-07 23:59:24 INFO 3/37: Found machine to be added: Berjaya Times Square Theme Park 
2024-03-07 23:59:57 INFO Location Malaysia (91/125): Changes in 1/37 machines found.
2024-03-08 00:11:06 INFO 
 Result: 2 changes, 2 new machines found and 0 machines retired
2024-03-08 00:25:31 ERROR Found 5 problems that require manual intervention
2024-03-08 00:25:31 INFO ======Location differ completed at 2024-03-08 00:25:31=======
2024-03-08 00:25:31 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7076 named General store submitted.

**Comment by jannisborn** [comment]
2024-03-08 22:30:01 INFO ======Location differ joblog from 2024-03-08 22:30:01=======
2024-03-08 22:46:47 INFO George C. Page Museum, La Brea Tar Pits is available again
2024-03-08 22:50:55 INFO Location California (12/125): Changes in 1/752 machines found.
2024-03-08 23:07:40 INFO Westgate Lakes Resort got permanently removed
2024-03-08 23:08:41 INFO Location Florida (24/125): Changes in 1/384 machines found.
2024-03-08 23:18:43 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-03-09 00:06:39 INFO Seeems that machine The Scott Monument at East Princes Street Gardens, Edinburgh already exists as: The Mound, Edinburgh
2024-03-09 00:13:35 INFO 
 Result: 2 changes, 1 new machines found and 0 machines retired
2024-03-09 00:32:09 ERROR Found 5 problems that require manual intervention
2024-03-09 00:32:09 INFO ======Location differ completed at 2024-03-09 00:32:09=======
2024-03-09 00:32:10 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-03-09 22:30:02 INFO ======Location differ joblog from 2024-03-09 22:30:02=======
2024-03-09 23:15:56 INFO 164/204: Found machine to be added: Mount Charleston Visitor Center
2024-03-09 23:16:13 INFO Location Nevada (31/125): Changes in 1/204 machines found.
2024-03-09 23:16:28 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-03-10 00:02:46 INFO The Scott Monument is available again
2024-03-10 00:03:12 INFO Location Scotland (107/125): Changes in 1/92 machines found.
2024-03-10 00:08:41 INFO 
 Result: 2 changes, 2 new machines found and 0 machines retired
2024-03-10 00:09:51 ERROR Our machine Universal Studios Florida in Florida from Device shown as available but http://209.221.138.252/Details.aspx?location=381705 responds Internal Server Error (500)
2024-03-10 00:23:03 ERROR Found 5 problems that require manual intervention
2024-03-10 00:23:03 INFO ======Location differ completed at 2024-03-10 00:23:03=======
2024-03-10 00:23:04 INFO Detected change in server_locations.json - push to github

**Pull request merged**
