### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by jannisborn**
2024-10-11 22:30:02 INFO ======Location differ joblog from 2024-10-11 22:30:02=======
2024-10-11 23:16:34 INFO 5/209: Found machine to be added: Tom Devlin's Monster Museum
2024-10-11 23:18:11 INFO Location Nevada (31/125): Changes in 1/209 machines found.
2024-10-12 00:13:20 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-10-12 00:28:59 ERROR Found 3 problems that require manual intervention
2024-10-12 00:28:59 INFO ======Location differ completed at 2024-10-12 00:28:59=======
2024-10-12 00:29:00 INFO Detected change in server_locations.json - push to github

### CODE REVIEW

**Comment by NinaWie** [comment]
New machine 7586 named Budavari Palota/Castle submitted.

**Comment by jannisborn** [comment]
2024-10-12 22:30:02 INFO ======Location differ joblog from 2024-10-12 22:30:02=======
2024-10-12 23:00:47 INFO Grant's Farm - Bauernhof Courtyard is available again
2024-10-12 23:01:04 INFO Location Missouri (22/125): Changes in 1/184 machines found.
2024-10-13 00:11:13 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-10-13 00:27:02 ERROR Found 3 problems that require manual intervention
2024-10-13 00:27:02 INFO ======Location differ completed at 2024-10-13 00:27:02=======
2024-10-13 00:27:02 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7587 named Tierpark Rheinböllen submitted.

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
2024-10-14 22:30:01 INFO ======Location differ joblog from 2024-10-14 22:30:01=======
2024-10-14 22:36:46 INFO Sacajawea Plaza is available again
2024-10-14 22:37:47 INFO Location Arizona (6/125): Changes in 1/224 machines found.
2024-10-14 22:57:37 INFO 10/88: Found machine to be added: Boyds World Famous Antiques
2024-10-14 22:58:32 INFO Location South Dakota (20/125): Changes in 1/88 machines found.
2024-10-15 00:00:42 INFO Wellington Museum is available again
2024-10-15 00:00:44 INFO Location New Zealand (95/125): Changes in 1/35 machines found.
2024-10-15 00:10:02 INFO 
 Result: 3 changes, 3 new machines found and 0 machines retired
2024-10-15 00:25:15 ERROR Found 3 problems that require manual intervention
2024-10-15 00:25:15 INFO ======Location differ completed at 2024-10-15 00:25:15=======
2024-10-15 00:25:16 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7589 named Jelly Belly Center submitted.

**Comment by jannisborn** [comment]
2024-10-15 22:30:02 INFO ======Location differ joblog from 2024-10-15 22:30:02=======
2024-10-15 22:48:18 INFO San Diego Harbor - Old Town Trolley Tours of San Diego is available again
2024-10-15 22:50:18 INFO Location California (12/125): Changes in 1/767 machines found.
2024-10-16 00:09:53 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-10-16 00:24:59 ERROR Found 3 problems that require manual intervention
2024-10-16 00:24:59 INFO ======Location differ completed at 2024-10-16 00:24:59=======
2024-10-16 00:25:00 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7590 named Caldeira Velha submitted.

**Comment by jannisborn** [comment]
2024-10-16 22:30:02 INFO ======Location differ joblog from 2024-10-16 22:30:02=======
2024-10-16 22:56:15 INFO Broadway at the Beach - Broadway Magic is available again
2024-10-16 22:56:20 INFO Broadway at the Beach - Tervis store (Was Body & Bath Cafe) is available again
2024-10-16 22:56:44 INFO Location South Carolina (17/125): Changes in 2/106 machines found.
2024-10-16 23:27:03 INFO 204/206: Found machine to be added: High Falls George
2024-10-16 23:27:04 INFO Location New York (43/125): Changes in 1/206 machines found.
2024-10-16 23:31:14 INFO 19/65: Found machine to be added: Georgetown Rest Area I-75 Northbound
2024-10-16 23:31:45 INFO Location Kentucky (48/125): Changes in 1/65 machines found.
2024-10-17 00:09:35 INFO 
 Result: 4 changes, 4 new machines found and 0 machines retired
2024-10-17 00:24:41 ERROR Found 3 problems that require manual intervention
2024-10-17 00:24:41 INFO ======Location differ completed at 2024-10-17 00:24:41=======
2024-10-17 00:24:42 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7593 named Chá Gorreana submitted.

**Comment by jannisborn** [comment]
2024-10-17 22:30:01 INFO ======Location differ joblog from 2024-10-17 22:30:01=======
2024-10-17 22:55:13 INFO 36/107: Found machine to be added: Duluth Deals
2024-10-17 22:56:03 INFO Location Minnesota (16/125): Changes in 1/107 machines found.
2024-10-17 23:04:50 INFO Walt Disney World, Disney Springs, House of Blues is currently unavailable
2024-10-17 23:07:11 INFO Location Florida (24/125): Changes in 1/389 machines found.
2024-10-17 23:11:16 INFO Milburn-Price Culture Museum is currently unavailable
2024-10-17 23:11:25 INFO Location Texas (26/125): Changes in 1/308 machines found.
2024-10-18 00:10:47 INFO 
 Result: 3 changes, 1 new machines found and 2 machines retired
2024-10-18 00:26:00 ERROR Found 3 problems that require manual intervention
2024-10-18 00:26:00 INFO ======Location differ completed at 2024-10-18 00:26:00=======
2024-10-18 00:26:01 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-10-18 22:30:02 INFO ======Location differ joblog from 2024-10-18 22:30:02=======
2024-10-18 22:36:21 INFO Sugar Saloon is available again
2024-10-18 22:36:23 INFO Wagon Burner's Native Touch  is available again
2024-10-18 22:38:00 INFO Location Arizona (6/125): Changes in 2/224 machines found.
2024-10-18 23:34:49 INFO 8/62: Found machine to be added: Die Schlossbergbahn
2024-10-18 23:34:51 INFO 9/62: Found machine to be added: Schloßberg Biergarten
2024-10-18 23:35:39 INFO Location Austria (54/125): Changes in 2/62 machines found.
2024-10-19 00:10:48 INFO 
 Result: 4 changes, 4 new machines found and 0 machines retired
2024-10-19 00:26:03 ERROR Found 3 problems that require manual intervention
2024-10-19 00:26:03 INFO ======Location differ completed at 2024-10-19 00:26:03=======
2024-10-19 00:26:04 INFO Detected change in server_locations.json - push to github

**Review by NinaWie — APPROVED** [review]

**Pull request merged**
