### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 3817 "The Texas Zoo":
	Status from: available to: retired

### CODE REVIEW

**Comment by jannisborn** [comment]
2024-08-28 22:30:01 INFO ======Location differ joblog from 2024-08-28 22:30:01=======
2024-08-28 23:23:41 INFO 7/34: Found machine to be added: Scotts Bluff National Monument
2024-08-28 23:24:05 INFO Location Nebraska (28/125): Changes in 1/34 machines found.
2024-08-29 00:05:32 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=322076': ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
2024-08-29 00:05:42 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=412667': HTTPConnectionPool(host='209.221.138.252', port=80): Max retries exceeded with url: /Details.aspx?location=412667 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc66cc1a190>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-08-29 00:22:50 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-08-29 00:39:24 ERROR Found 3 problems that require manual intervention
2024-08-29 00:39:24 INFO ======Location differ completed at 2024-08-29 00:39:24=======
2024-08-29 00:39:25 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-08-29 22:30:01 INFO ======Location differ joblog from 2024-08-29 22:30:01=======
2024-08-29 23:13:52 INFO 163/305: Found machine to be added: Houston Museum of Health & Medical Science
2024-08-29 23:15:38 INFO Location Texas (26/125): Changes in 1/305 machines found.
2024-08-30 00:15:32 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-08-30 00:32:19 ERROR Found 3 problems that require manual intervention
2024-08-30 00:32:19 INFO ======Location differ completed at 2024-08-30 00:32:19=======
2024-08-30 00:32:20 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7496 named Gateway Clipper Fleet submitted.

**Comment by jannisborn** [comment]
2024-08-30 22:30:02 INFO ======Location differ joblog from 2024-08-30 22:30:02=======
2024-08-30 22:45:56 INFO World of Gifts is available again
2024-08-30 22:46:13 INFO Location Oregon (8/125): Changes in 1/133 machines found.
2024-08-30 22:46:32 INFO National Park Gifts and Souvenirs is currently unavailable
2024-08-30 22:47:05 INFO Location Arkansas (9/125): Changes in 1/56 machines found.
2024-08-30 22:58:40 INFO Fisherman's Wharf - Jefferson St. - Madame Tussauds is currently unavailable
2024-08-30 23:01:07 INFO Location California (12/125): Changes in 1/761 machines found.
2024-08-30 23:52:40 INFO 159/204: Found machine to be added: Charcoal Corral
2024-08-30 23:53:07 INFO Location New York (43/125): Changes in 1/204 machines found.
2024-08-31 00:09:54 INFO Embsay & Bolton Abbey Railway is currently unavailable
2024-08-31 00:11:26 INFO Location England (69/125): Changes in 1/444 machines found.
2024-08-31 00:39:28 INFO 
 Result: 5 changes, 2 new machines found and 3 machines retired
2024-08-31 00:41:04 ERROR Our machine Good vibes, Good, Great Finds in Massachusetts from Device shown as available but http://209.221.138.252/Details.aspx?location=382942 responds Internal Server Error (500)
2024-08-31 00:56:03 ERROR Found 3 problems that require manual intervention
2024-08-31 00:56:03 INFO ======Location differ completed at 2024-08-31 00:56:03=======
2024-08-31 00:56:04 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7498 named Hochatown saloon submitted.

**Comment by jannisborn** [comment]
2024-08-31 22:30:02 INFO ======Location differ joblog from 2024-08-31 22:30:02=======
2024-09-01 00:21:13 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=295502': ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
2024-09-01 00:21:24 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=427969': ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-09-01 00:22:05 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=388326': HTTPConnectionPool(host='209.221.138.252', port=80): Max retries exceeded with url: /Details.aspx?location=388326 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc66d4f8070>: Failed to establish a new connection: [Errno 110] Connection timed out'))
2024-09-01 00:22:47 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=199300': HTTPConnectionPool(host='209.221.138.252', port=80): Max retries exceeded with url: /Details.aspx?location=199300 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc656c8e490>: Failed to establish a new connection: [Errno 110] Connection timed out'))
2024-09-01 00:23:28 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=419150': HTTPConnectionPool(host='209.221.138.252', port=80): Max retries exceeded with url: /Details.aspx?location=419150 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc66d4f88b0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
2024-09-01 00:24:10 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=419148': HTTPConnectionPool(host='209.221.138.252', port=80): Max retries exceeded with url: /Details.aspx?location=419148 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc66d500100>: Failed to establish a new connection: [Errno 110] Connection timed out'))
2024-09-01 00:24:20 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=260480': HTTPConnectionPool(host='209.221.138.252', port=80): Max retries exceeded with url: /Details.aspx?location=260480 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc66d500910>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-09-01 00:26:23 INFO 
 Result: 0 changes, 0 new machines found and 0 machines retired
2024-09-01 00:27:58 ERROR Our machine Dunkin Donuts Park / Yard Goats Baseball in Connecticut from Device shown as available but http://209.221.138.252/Details.aspx?location=361971 responds Internal Server Error (500)
2024-09-01 00:43:12 ERROR Found 3 problems that require manual intervention
2024-09-01 00:43:12 INFO ======Location differ completed at 2024-09-01 00:43:12=======
2024-09-01 00:43:12 INFO Detected change in server_locations.json - push to github

**Review by jannisborn — APPROVED** [review]

**Comment by NinaWie** [comment]
New machine 7499 named Arcade Mania submitted.

**Comment by jannisborn** [comment]
2024-09-01 22:30:01 INFO ======Location differ joblog from 2024-09-01 22:30:01=======
2024-09-01 22:59:29 INFO 11/26: Found machine to be added: Lyman Orchard Farm Store 
2024-09-01 22:59:36 INFO Location Connecticut (18/125): Changes in 1/26 machines found.
2024-09-01 23:25:46 INFO 92/132: Found machine to be added: Royal Caribbean Cruise Line,  'Quantum of the Seas'
2024-09-01 23:26:08 INFO Location Washington (38/125): Changes in 1/132 machines found.
2024-09-01 23:57:21 INFO 49/144: Found machine to be added: Selinunte Archaeological Park 
2024-09-01 23:58:30 INFO Location Italy (82/125): Changes in 1/144 machines found.
2024-09-02 00:03:49 INFO 49/150: Found machine to be added: Holland Souvenirs
2024-09-02 00:05:12 INFO Location Netherlands (94/125): Changes in 1/150 machines found.
2024-09-02 00:15:01 INFO 
 Result: 4 changes, 4 new machines found and 0 machines retired
2024-09-02 00:27:08 ERROR Our machine Royal Caribbean International in Washington from Server shown as available but http://209.221.138.252/Details.aspx?location=431991 responds Internal Server Error (500)
2024-09-02 00:32:06 ERROR Found 3 problems that require manual intervention
2024-09-02 00:32:06 INFO ======Location differ completed at 2024-09-02 00:32:06=======
2024-09-02 00:32:07 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-09-02 22:30:02 INFO ======Location differ joblog from 2024-09-02 22:30:02=======
2024-09-02 23:13:28 INFO 209/307: Found machine to be added: Camp Fimfo Texas Hill Country
2024-09-02 23:13:56 INFO 248/307: Found machine to be added: Morgan's Wonderland 
2024-09-02 23:14:38 INFO Location Texas (26/125): Changes in 2/307 machines found.
2024-09-02 23:22:08 INFO Mabry Mill Restaurant and Gift Shop is available again
2024-09-02 23:22:56 INFO Location Virginia (35/125): Changes in 1/124 machines found.
2024-09-03 00:10:23 INFO 49/188: Found machine to be added: C. Judería, 4
2024-09-03 00:11:47 INFO 145/188: Found machine to be added: Azahar
2024-09-03 00:12:23 INFO Location Spain (112/125): Changes in 2/188 machines found.
2024-09-03 00:14:57 INFO 
 Result: 5 changes, 5 new machines found and 0 machines retired
2024-09-03 00:32:10 ERROR Found 3 problems that require manual intervention
2024-09-03 00:32:10 INFO ======Location differ completed at 2024-09-03 00:32:10=======
2024-09-03 00:32:11 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
Let's be brave and try again!

**Pull request merged**
