### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 82 "Arenas":
	Status from: available to: retired

### CODE REVIEW

**Comment by jannisborn** [comment]
2024-05-14 22:30:02 INFO ======Location differ joblog from 2024-05-14 22:30:02=======
2024-05-14 22:36:29 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=244686': HTTPConnectionPool(host='209.221.138.252', port=80): Max retries exceeded with url: /Details.aspx?location=244686 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55b0c99610>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-05-14 22:36:39 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=328828': HTTPConnectionPool(host='209.221.138.252', port=80): Max retries exceeded with url: /Details.aspx?location=328828 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55b0c99ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-05-14 23:02:29 INFO Wildhorse Saloon is currently unavailable
2024-05-14 23:03:07 INFO Location Tennessee (23/125): Changes in 1/198 machines found.
2024-05-14 23:05:46 INFO 227/385: Found machine to be added: Disney's Character Warehouse
2024-05-14 23:07:14 INFO Location Florida (24/125): Changes in 1/385 machines found.
2024-05-14 23:16:48 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-05-14 23:37:23 INFO The Dungeon Shanghai  is currently unavailable
2024-05-14 23:37:26 INFO Location China (63/125): Changes in 1/19 machines found.
2024-05-15 00:08:20 INFO 
 Result: 3 changes, 1 new machines found and 2 machines retired
2024-05-15 00:23:20 ERROR Found 4 problems that require manual intervention
2024-05-15 00:23:20 INFO ======Location differ completed at 2024-05-15 00:23:20=======
2024-05-15 00:23:21 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-05-15 22:30:02 INFO ======Location differ joblog from 2024-05-15 22:30:02=======
2024-05-15 23:16:18 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-05-15 23:28:45 INFO 114/164: Found machine to be added: Mayberry Market and Souvenirs 
2024-05-15 23:29:17 INFO Location North Carolina (46/125): Changes in 1/164 machines found.
2024-05-15 23:29:31 INFO 16/119: Found machine to be added: From the Forty LLC - Main Street Shops
2024-05-15 23:30:39 INFO Location Wisconsin (47/125): Changes in 1/119 machines found.
2024-05-15 23:32:59 INFO 62/90: Found machine to be added: West Coast Wilderness Railway
2024-05-15 23:33:16 INFO Location Australia (53/125): Changes in 1/90 machines found.
2024-05-15 23:38:50 INFO 158/438: Found machine to be added: Haven Holiday Park
2024-05-15 23:41:35 INFO Location England (69/125): Changes in 1/438 machines found.
2024-05-16 00:07:32 INFO 
 Result: 4 changes, 4 new machines found and 0 machines retired
2024-05-16 00:22:25 ERROR Found 4 problems that require manual intervention
2024-05-16 00:22:25 INFO ======Location differ completed at 2024-05-16 00:22:25=======
2024-05-16 00:22:26 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7177 named Lauterbach Mole submitted.

**Comment by jannisborn** [comment]
2024-05-16 22:30:01 INFO ======Location differ joblog from 2024-05-16 22:30:01=======
2024-05-16 23:16:13 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-05-16 23:39:04 INFO 218/439: Found machine to be added: Monopoly Lifesized
2024-05-16 23:41:15 INFO Location England (69/125): Changes in 1/439 machines found.
2024-05-17 00:07:07 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-05-17 00:22:03 ERROR Found 4 problems that require manual intervention
2024-05-17 00:22:03 INFO ======Location differ completed at 2024-05-17 00:22:03=======
2024-05-17 00:22:04 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-05-17 22:30:02 INFO ======Location differ joblog from 2024-05-17 22:30:02=======
2024-05-17 22:41:44 INFO Odd-Lot Outlet Superstore is available again
2024-05-17 22:43:29 INFO Location Pennsylvania (11/125): Changes in 1/211 machines found.
2024-05-17 23:16:10 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-05-18 00:07:04 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-05-18 00:22:04 ERROR Found 4 problems that require manual intervention
2024-05-18 00:22:04 INFO ======Location differ completed at 2024-05-18 00:22:04=======
2024-05-18 00:22:05 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7179 named Sint Servaasbrug Maastricht submitted.

**Comment by jannisborn** [comment]
2024-05-18 22:30:02 INFO ======Location differ joblog from 2024-05-18 22:30:02=======
2024-05-18 22:30:12 INFO 2/67: Found machine to be added: Buc-ee's
2024-05-18 22:30:56 INFO Location Alabama (0/125): Changes in 1/67 machines found.
2024-05-18 23:16:12 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-05-18 23:35:13 INFO 45/146: Found machine to be added: Joan Harriss Cruise Pavilion
2024-05-18 23:36:07 INFO Location Canada (61/125): Changes in 1/146 machines found.
2024-05-18 23:53:16 INFO 55/215: Found machine to be added: Train Park Hakusan
2024-05-18 23:55:19 INFO Location Japan (84/125): Changes in 1/215 machines found.
2024-05-19 00:07:28 INFO 
 Result: 3 changes, 3 new machines found and 0 machines retired
2024-05-19 00:22:26 ERROR Found 4 problems that require manual intervention
2024-05-19 00:22:26 INFO ======Location differ completed at 2024-05-19 00:22:26=======
2024-05-19 00:22:27 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7183 named Bautzen Hauptmarkt submitted.

**Review by jannisborn — APPROVED** [review]

**Pull request merged**
