### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 5727 "CITTI-Park":
	Status from: available to: retired
	Address from: MÃ¼hlendamm 1, Kiel to: Mühlendamm 1, Kiel

### CODE REVIEW

**Comment by jannisborn** [comment]
2024-04-18 22:30:01 INFO ======Location differ joblog from 2024-04-18 22:30:01=======
2024-04-18 23:06:27 INFO 0/298: Found machine to be added: Javelinas on Holland
2024-04-18 23:09:47 INFO Location Texas (26/125): Changes in 1/298 machines found.
2024-04-18 23:15:12 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-04-19 00:05:18 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-04-19 00:19:45 ERROR Found 4 problems that require manual intervention
2024-04-19 00:19:45 INFO ======Location differ completed at 2024-04-19 00:19:45=======
2024-04-19 00:19:46 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
2024-04-20 22:30:01 INFO ======Location differ joblog from 2024-04-20 22:30:01=======
2024-04-20 22:35:33 INFO 33/223: Found machine to be added: Bright Angel Lodge
2024-04-20 22:37:36 INFO Location Arizona (6/125): Changes in 1/223 machines found.
2024-04-20 22:52:10 INFO 6/219: Found machine to be added: Buc-ees #60 - Johnstown, CO
2024-04-20 22:54:20 INFO Location Colorado (15/125): Changes in 1/219 machines found.
2024-04-20 23:15:32 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-04-20 23:51:50 INFO 51/213: Found machine to be added: Aqua World Ibaraki Prefecture Oarai Aquarium
2024-04-20 23:53:53 INFO Location Japan (84/125): Changes in 1/213 machines found.
2024-04-20 23:54:15 INFO Vilnius International Airport is currently unavailable
2024-04-20 23:54:16 INFO Location Lithuania (89/125): Changes in 1/13 machines found.
2024-04-21 00:05:52 INFO 
 Result: 4 changes, 3 new machines found and 1 machines retired
2024-04-21 00:20:20 ERROR Found 4 problems that require manual intervention
2024-04-21 00:20:20 INFO ======Location differ completed at 2024-04-21 00:20:20=======
2024-04-21 00:20:21 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-04-21 22:30:02 INFO ======Location differ joblog from 2024-04-21 22:30:02=======
2024-04-21 22:57:28 INFO 16/26: Found machine to be added: Chevron #209169
2024-04-21 22:57:36 INFO Location Mississippi (19/125): Changes in 1/26 machines found.
2024-04-21 23:16:20 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-04-22 00:06:31 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-04-22 00:20:49 ERROR Found 4 problems that require manual intervention
2024-04-22 00:20:49 INFO ======Location differ completed at 2024-04-22 00:20:49=======
2024-04-22 00:20:50 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-04-22 22:30:02 INFO ======Location differ joblog from 2024-04-22 22:30:02=======
2024-04-22 22:41:41 INFO 39/211: Found machine to be added: Crayola Factory Store
2024-04-22 22:43:23 INFO Location Pennsylvania (11/125): Changes in 1/211 machines found.
2024-04-22 22:54:42 INFO Legacy Toys is available again
2024-04-22 22:55:28 INFO Location Minnesota (16/125): Changes in 1/105 machines found.
2024-04-22 23:15:37 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-04-23 00:04:03 INFO 1/46: Found machine to be added: Leofoo Village Theme Park
2024-04-23 00:04:41 INFO Location Taiwan (118/125): Changes in 1/46 machines found.
2024-04-23 00:05:49 INFO 
 Result: 3 changes, 3 new machines found and 0 machines retired
2024-04-23 00:20:11 ERROR Found 4 problems that require manual intervention
2024-04-23 00:20:11 INFO ======Location differ completed at 2024-04-23 00:20:11=======
2024-04-23 00:20:12 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-04-23 22:30:02 INFO ======Location differ joblog from 2024-04-23 22:30:02=======
2024-04-23 23:15:39 INFO Las Vegas North Premium Outlets, Simon Guest Services is currently unavailable
2024-04-23 23:16:24 INFO Location Nevada (31/125): Changes in 1/204 machines found.
2024-04-23 23:16:38 ERROR Geolocation failed for: Unknown Location 	 sub: , Arco
2024-04-23 23:23:32 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=325220': ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
2024-04-23 23:23:43 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=185515': HTTPConnectionPool(host='209.221.138.252', port=80): Max retries exceeded with url: /Details.aspx?location=185515 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff04273d550>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-04-24 00:04:31 INFO Seeems that machine Souvenir shop already exists as: Souvenir Shop
2024-04-24 00:05:13 INFO 167/170: Found machine to be added: Super La Cuesta
2024-04-24 00:05:15 INFO Location Spain (996/125): Changes in 1/170 machines found.
2024-04-24 00:07:34 INFO 
 Result: 2 changes, 1 new machines found and 1 machines retired
2024-04-24 00:21:59 ERROR Found 4 problems that require manual intervention
2024-04-24 00:21:59 INFO ======Location differ completed at 2024-04-24 00:21:59=======
2024-04-24 00:21:59 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7146 named Fisherman’s Wharf SF submitted.

**Review by jannisborn — APPROVED** [review]

**Pull request merged**
