### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 724 "Restaurant “Le Métropole”":
	Status from: available to: retired
	Title from: Restaurant âLe MÃ©tropoleâ to: Restaurant “Le Métropole”

### CODE REVIEW

**Comment by jannisborn** [comment]
2024-12-14 22:30:01 INFO ======Location differ joblog from 2024-12-14 22:30:01=======
2024-12-14 22:41:18 INFO 22/92: Found machine to be added: Harry Potter  The Exhibition Boston in Massachusetts
2024-12-14 23:35:01 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-12-14 23:40:48 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-12-15 00:12:03 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-15 00:12:03 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-15 00:13:17 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-12-15 00:28:16 ERROR Found 9 problems that require manual intervention
2024-12-15 00:28:16 INFO ======Location differ completed at 2024-12-15 00:28:16=======
2024-12-15 00:28:17 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-12-15 22:30:02 INFO ======Location differ joblog from 2024-12-15 22:30:02=======
2024-12-15 22:34:10 INFO Skagway Trading Co. (in Alaska) is currently unavailable
2024-12-15 23:36:05 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-12-15 23:42:02 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-12-16 00:00:05 INFO 119/228: Found machine to be added: Osaka Wheel in Japan
2024-12-16 00:13:52 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-16 00:13:52 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-16 00:15:07 INFO 
 Result: 2 changes, 1 new machines found and 1 machines retired
2024-12-16 00:30:21 ERROR Found 9 problems that require manual intervention
2024-12-16 00:30:21 INFO ======Location differ completed at 2024-12-16 00:30:21=======
2024-12-16 00:30:21 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-12-16 22:30:02 INFO ======Location differ joblog from 2024-12-16 22:30:02=======
2024-12-16 23:12:48 INFO 268/313: Found machine to be added: San Felipe de Austin State Historic Site in Texas
2024-12-16 23:35:58 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-12-16 23:41:50 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-12-17 00:13:39 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-17 00:13:39 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-17 00:14:54 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-12-17 00:30:10 ERROR Found 9 problems that require manual intervention
2024-12-17 00:30:10 INFO ======Location differ completed at 2024-12-17 00:30:10=======
2024-12-17 00:30:11 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-12-17 22:30:02 INFO ======Location differ joblog from 2024-12-17 22:30:02=======
2024-12-17 22:45:18 INFO 54/768: Found machine to be added: Big Bear Snow Play  in California
2024-12-17 22:58:13 INFO Lost Treasure Golf (Professor Hacker's) (in South Carolina) is currently unavailable
2024-12-17 23:36:11 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-12-17 23:42:07 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-12-18 00:12:43 INFO 0/1: Found machine to be added: Add Slovakia in Sweeded
2024-12-18 00:13:59 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-18 00:14:00 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-18 00:15:15 INFO 
 Result: 3 changes, 2 new machines found and 1 machines retired
2024-12-18 00:30:32 ERROR Found 9 problems that require manual intervention
2024-12-18 00:30:32 INFO ======Location differ completed at 2024-12-18 00:30:32=======
2024-12-18 00:30:33 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-12-18 22:30:02 INFO ======Location differ joblog from 2024-12-18 22:30:02=======
2024-12-18 23:02:26 INFO 5/204: Found machine to be added: Paris Landing KOA Campground in Tennessee
2024-12-18 23:35:59 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-12-18 23:41:53 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-12-19 00:13:45 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-19 00:13:45 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-19 00:15:00 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-12-19 00:30:16 ERROR Found 9 problems that require manual intervention
2024-12-19 00:30:16 INFO ======Location differ completed at 2024-12-19 00:30:16=======
2024-12-19 00:30:17 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
No website updates today!

**Comment by NinaWie** [comment]
New machine 7681 named Bass pro shops submitted.

**Review by jannisborn — APPROVED** [review]

**Comment by NinaWie** [comment]
New machine 7682 named Old West Cinnamon Rolls submitted.

**Comment by jannisborn** [comment]
2024-12-21 22:30:02 INFO ======Location differ joblog from 2024-12-21 22:30:02=======
2024-12-21 23:35:17 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-12-21 23:41:05 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-12-22 00:10:42 INFO Seems that machine Sevillia shop already exists as: Sevilla Shop
2024-12-22 00:12:37 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-22 00:12:38 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-22 00:13:52 INFO 
 Result: 0 changes, 0 new machines found and 0 machines retired
2024-12-22 00:28:59 ERROR Found 9 problems that require manual intervention
2024-12-22 00:28:59 INFO ======Location differ completed at 2024-12-22 00:28:59=======
2024-12-22 00:29:00 INFO Detected change in server_locations.json - push to github

**Pull request merged**
