### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 5390 "Chickamauga and Chattanooga National Military Park":
	Status from: available to: retired

### CODE REVIEW

**Comment by jannisborn** [comment]
2024-11-30 22:30:02 INFO ======Location differ joblog from 2024-11-30 22:30:02=======
2024-11-30 22:58:46 INFO 81/89: Found machine to be added: Sturgis Photo & Gifts in South Dakota
2024-11-30 23:33:25 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-11-30 23:39:03 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-12-01 00:09:32 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-01 00:09:32 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-01 00:10:45 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-12-01 00:25:38 ERROR Found 9 problems that require manual intervention
2024-12-01 00:25:38 INFO ======Location differ completed at 2024-12-01 00:25:38=======
2024-12-01 00:25:39 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7664 named Goofy's Candy Co. submitted.

**Comment by jannisborn** [comment]
No website updates today!

**Comment by NinaWie** [comment]
New machine 7665 named Goofy's Candy Company submitted.

**Comment by jannisborn** [comment]
2024-12-02 22:30:02 INFO ======Location differ joblog from 2024-12-02 22:30:02=======
2024-12-02 22:58:56 INFO Seems that machine Lewies Burgers & Brews already exists as: Lewies Burger & Brew
2024-12-02 23:09:09 INFO Pearl Antler Boutique is available again
2024-12-02 23:34:27 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-12-02 23:40:11 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-12-03 00:11:13 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-03 00:11:13 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-03 00:12:24 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-12-03 00:26:53 ERROR Found 9 problems that require manual intervention
2024-12-03 00:26:53 INFO ======Location differ completed at 2024-12-03 00:26:53=======
2024-12-03 00:26:54 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-12-03 22:30:02 INFO ======Location differ joblog from 2024-12-03 22:30:02=======
2024-12-03 22:48:22 INFO Corvette Diner is available again
2024-12-03 23:34:29 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-12-03 23:40:13 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-12-04 00:11:21 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-04 00:11:21 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-04 00:12:34 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-12-04 00:27:26 ERROR Found 9 problems that require manual intervention
2024-12-04 00:27:26 INFO ======Location differ completed at 2024-12-04 00:27:26=======
2024-12-04 00:27:27 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
No website updates today!

**Comment by jannisborn** [comment]
2024-12-06 22:30:01 INFO ======Location differ joblog from 2024-12-06 22:30:01=======
2024-12-06 22:48:16 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=29626': ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
2024-12-06 22:48:26 WARNING Exception encountered when testing link 'http://209.221.138.252/Details.aspx?location=79296': HTTPConnectionPool(host='209.221.138.252', port=80): Max retries exceeded with url: /Details.aspx?location=79296 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8477267d60>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-12-06 23:29:48 INFO Ellis Island Immigration Museum is available again
2024-12-06 23:29:49 INFO Statue of Liberty National Monument is available again
2024-12-06 23:36:25 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-12-06 23:42:17 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-12-07 00:12:26 INFO 168/195: Found machine to be added: Casa de Los Balcones in Spain
2024-12-07 00:14:10 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-07 00:14:10 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-07 00:15:26 INFO 
 Result: 3 changes, 3 new machines found and 0 machines retired
2024-12-07 00:30:43 ERROR Found 9 problems that require manual intervention
2024-12-07 00:30:43 INFO ======Location differ completed at 2024-12-07 00:30:43=======
2024-12-07 00:30:44 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-12-07 22:30:02 INFO ======Location differ joblog from 2024-12-07 22:30:02=======
2024-12-07 22:49:36 INFO Christmas in the Park is available again
2024-12-07 23:21:07 INFO Frontier Culture Museum  (in Virginia) is currently unavailable
2024-12-07 23:35:50 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-12-07 23:41:42 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-12-08 00:13:25 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-08 00:13:25 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-08 00:14:39 INFO 
 Result: 2 changes, 1 new machines found and 1 machines retired
2024-12-08 00:30:12 ERROR Found 9 problems that require manual intervention
2024-12-08 00:30:12 INFO ======Location differ completed at 2024-12-08 00:30:12=======
2024-12-08 00:30:13 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7668 named Waterside Stage submitted.

**Review by jannisborn — APPROVED** [review]

**Comment by jannisborn** [comment]
2024-12-08 22:30:01 INFO ======Location differ joblog from 2024-12-08 22:30:01=======
2024-12-08 23:34:52 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-12-08 23:40:39 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-12-08 23:59:11 INFO 179/227: Found machine to be added: Tachibana-Maru Passenger Ship in Japan
2024-12-09 00:11:55 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-09 00:11:55 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-09 00:13:09 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-12-09 00:28:07 ERROR Found 9 problems that require manual intervention
2024-12-09 00:28:07 INFO ======Location differ completed at 2024-12-09 00:28:07=======
2024-12-09 00:28:08 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7670 named Kurpark / Kiosk am Strandcafé submitted.

**Comment by jannisborn** [comment]
2024-12-10 22:30:03 INFO ======Location differ joblog from 2024-12-10 22:30:03=======
2024-12-10 23:34:15 ERROR http://209.221.138.252/Details.aspx?location=369286 used in multiple pins with different states, requires manual handling.
2024-12-10 23:39:56 ERROR http://209.221.138.252/Details.aspx?location=3239 used in multiple pins with different states, requires manual handling.
2024-12-11 00:07:06 INFO 25/196: Found machine to be added: Pl. de Sant Jaume in Spain
2024-12-11 00:10:42 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-11 00:10:42 ERROR Geolocation failed for: Unknown Location 	 sub: , Unknown. 
2024-12-11 00:11:55 INFO 
 Result: 1 changes, 1 new machines found and 0 machines retired
2024-12-11 00:26:38 ERROR Found 9 problems that require manual intervention
2024-12-11 00:26:38 INFO ======Location differ completed at 2024-12-11 00:26:38=======
2024-12-11 00:26:42 INFO Detected change in server_locations.json - push to github

**Review by jannisborn — APPROVED** [review]

**Pull request merged**
