### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 3285 "The Daytona International Speedway, The Daytona 500 Experience":
	Status from: out-of-order to: available

### CODE REVIEW

**Comment by jannisborn** [comment]
2024-06-28 22:30:01 INFO ======Location differ joblog from 2024-06-28 22:30:01=======
2024-06-28 23:19:56 INFO 109/138: Found machine to be added: Wallys
2024-06-28 23:20:14 INFO Location Illinois (36/125): Changes in 1/138 machines found.
2024-06-29 00:03:28 INFO 4/9: Found machine to be added: Lotte World Adventure
2024-06-29 00:03:31 INFO Location South Korea (111/125): Changes in 1/9 machines found.
2024-06-29 00:08:21 INFO 
 Result: 2 changes, 2 new machines found and 0 machines retired
2024-06-29 00:24:04 ERROR Our machine Tsawwassen Ferry Terminal in Canada from Server shown as available but http://209.221.138.252/Details.aspx?location=432781 responds Internal Server Error (500)
2024-06-29 00:24:04 ERROR Found 3 problems that require manual intervention
2024-06-29 00:24:04 INFO ======Location differ completed at 2024-06-29 00:24:04=======
2024-06-29 00:24:05 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-06-29 22:30:02 INFO ======Location differ joblog from 2024-06-29 22:30:02=======
2024-06-29 23:03:33 INFO Beef Jerky Outlet is available again
2024-06-29 23:05:30 INFO Location Tennessee (23/125): Changes in 1/198 machines found.
2024-06-29 23:25:01 INFO 56/132: Found machine to be added: Sharky's
2024-06-29 23:25:50 INFO Location Washington (38/125): Changes in 1/132 machines found.
2024-06-29 23:34:36 INFO Lost River Cave is available again
2024-06-29 23:35:11 INFO Location Kentucky (48/125): Changes in 1/62 machines found.
2024-06-30 00:03:41 INFO 7/13: Found machine to be added: Museum of the History of Polish Jews
2024-06-30 00:03:44 INFO 8/13: Found machine to be added: Warsaw Zoo
2024-06-30 00:03:48 INFO Location Poland (100/125): Changes in 2/13 machines found.
2024-06-30 00:07:13 INFO 5/10: Found machine to be added: Lotte World Aquarium
2024-06-30 00:07:16 INFO Location South Korea (111/125): Changes in 1/10 machines found.
2024-06-30 00:12:02 INFO 
 Result: 6 changes, 6 new machines found and 0 machines retired
2024-06-30 00:27:32 ERROR Found 3 problems that require manual intervention
2024-06-30 00:27:32 INFO ======Location differ completed at 2024-06-30 00:27:32=======
2024-06-30 00:27:33 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7254 named Fast Fanny’s place submitted.

**Comment by NinaWie** [comment]
New machine 7255 named Native Touch submitted.

**Comment by NinaWie** [comment]
New machine 7256 named Strip District Terminal Building submitted.

**Comment by NinaWie** [comment]
New machine 7257 named Frost Science Museum submitted.

**Comment by jannisborn** [comment]
2024-06-30 22:30:02 INFO ======Location differ joblog from 2024-06-30 22:30:02=======
2024-06-30 22:38:09 INFO Western Maryland Scenic Railroad is available again
2024-06-30 22:38:31 INFO Location Maryland (7/125): Changes in 1/68 machines found.
2024-06-30 23:15:51 INFO 27/33: Found machine to be added: Ponca State Park
2024-06-30 23:15:55 INFO Location Nebraska (28/125): Changes in 1/33 machines found.
2024-07-01 00:12:19 INFO 
 Result: 2 changes, 2 new machines found and 0 machines retired
2024-07-01 00:28:07 ERROR Found 3 problems that require manual intervention
2024-07-01 00:28:07 INFO ======Location differ completed at 2024-07-01 00:28:07=======
2024-07-01 00:28:07 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7259 named Aquarium am Hafen submitted.

**Comment by jannisborn** [comment]
2024-07-01 22:30:02 INFO ======Location differ joblog from 2024-07-01 22:30:02=======
2024-07-01 22:41:59 INFO Butterfly Place, The is currently unavailable
2024-07-01 22:42:01 INFO Location Massachusetts (10/125): Changes in 1/90 machines found.
2024-07-01 22:43:17 INFO 121/212: Found machine to be added: Meyersdale Train Station 
2024-07-01 22:44:16 INFO Location Pennsylvania (11/125): Changes in 1/212 machines found.
2024-07-02 00:10:36 INFO 
 Result: 2 changes, 1 new machines found and 1 machines retired
2024-07-02 00:26:25 ERROR Found 3 problems that require manual intervention
2024-07-02 00:26:25 INFO ======Location differ completed at 2024-07-02 00:26:25=======
2024-07-02 00:26:26 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-07-02 22:30:02 INFO ======Location differ joblog from 2024-07-02 22:30:02=======
2024-07-02 22:34:17 INFO 20/30: Found machine to be added: Funtown Splashton USA
2024-07-02 22:34:22 INFO Location Maine (4/125): Changes in 1/30 machines found.
2024-07-02 22:39:24 INFO Pietros Pizza is currently unavailable
2024-07-02 22:39:58 INFO Location Oregon (8/125): Changes in 1/131 machines found.
2024-07-02 22:42:17 INFO Jennie Wade House is currently unavailable
2024-07-02 22:43:42 INFO Location Pennsylvania (11/125): Changes in 1/212 machines found.
2024-07-02 22:54:56 INFO Mall of America - Nickelodeon Universe is available again
2024-07-02 22:55:56 INFO Location Minnesota (16/125): Changes in 1/106 machines found.
2024-07-02 23:08:19 INFO Distance match - Seeems that machine Texas Best Smokehouse #12 at 2825 Nolan River Rd, Cleburne already exists as: Texas Beat Smokehouse
2024-07-02 23:30:32 INFO 62/121: Found machine to be added: Laura Ingalls Wilder Museum
2024-07-02 23:31:09 INFO Location Wisconsin (47/125): Changes in 1/121 machines found.
2024-07-02 23:51:09 INFO Distance match - Seeems that machine Szantod Ferry at , Szantod Rev already exists as: Szantod Port
2024-07-02 23:51:17 INFO 74/82: Found machine to be added: Tihany - By the Molo Cafe & Bar.
2024-07-02 23:51:24 INFO Location Hungary (78/125): Changes in 1/82 machines found.
2024-07-02 23:58:24 INFO 53/146: Found machine to be added: Eindhoven Airport
2024-07-02 23:59:40 INFO Location Netherlands (94/125): Changes in 1/146 machines found.
2024-07-03 00:08:45 INFO 
 Result: 7 changes, 5 new machines found and 2 machines retired
2024-07-03 00:24:31 ERROR Found 3 problems that require manual intervention
2024-07-03 00:24:31 INFO ======Location differ completed at 2024-07-03 00:24:31=======
2024-07-03 00:24:32 INFO Detected change in server_locations.json - push to github

**Review by jannisborn — APPROVED** [review]

**Comment by jannisborn** [comment]
No website updates today!

**Comment by NinaWie** [comment]
New machine 7265 named Grand Canyon General Store submitted.

**Comment by jannisborn** [comment]
2024-07-04 22:30:02 INFO ======Location differ joblog from 2024-07-04 22:30:02=======
2024-07-04 22:31:07 INFO Louisiana Boardwalk - Fuddruckers is available again
2024-07-04 22:31:45 INFO Location Louisiana (1/125): Changes in 1/89 machines found.
2024-07-04 22:39:17 INFO 52/132: Found machine to be added: Clakamas Town Center - Made in Oregon
2024-07-04 22:40:02 INFO Location Oregon (8/125): Changes in 1/132 machines found.
2024-07-04 23:09:31 INFO Haltom City Public Library is available again
2024-07-04 23:11:12 INFO Location Texas (26/125): Changes in 1/302 machines found.
2024-07-04 23:15:58 INFO 110/206: Found machine to be added: Museum of Selfies
2024-07-04 23:16:36 INFO Location Nevada (31/125): Changes in 1/206 machines found.
2024-07-04 23:21:31 INFO Great Wolf Lodge Water Park is available again
2024-07-04 23:22:40 INFO Location Washington (38/125): Changes in 1/132 machines found.
2024-07-04 23:26:19 INFO New York Aquarium is currently unavailable
2024-07-04 23:27:13 INFO Location New York (43/125): Changes in 1/201 machines found.
2024-07-04 23:28:02 INFO 26/52: Found machine to be added: Mass Street Soda & Sweets
2024-07-04 23:28:19 INFO Location Kansas (45/125): Changes in 1/52 machines found.
2024-07-04 23:59:36 INFO Domtower is currently unavailable
2024-07-04 23:59:52 INFO Location Netherlands (94/125): Changes in 1/146 machines found.
2024-07-05 00:09:00 INFO 
 Result: 8 changes, 6 new machines found and 2 machines retired
2024-07-05 00:24:38 ERROR Our machine Berjaya Times Square Theme Park  in Malaysia from Server shown as available but http://209.221.138.252/Details.aspx?location=424322 responds Internal Server Error (500)
2024-07-05 00:24:41 ERROR Found 3 problems that require manual intervention
2024-07-05 00:24:41 INFO ======Location differ completed at 2024-07-05 00:24:41=======
2024-07-05 00:24:42 INFO Detected change in server_locations.json - push to github

**Pull request merged**
