### PR TITLE
Machine updates

### PR DESCRIPTION
**Pull request by NinaWie**
Change 1070 "Silver Dollar City":
	Multimachine from: 1 to: 9
	 Paywall from: False to: True

### CODE REVIEW

**Comment by jannisborn** [comment]
2024-07-08 22:30:02 INFO ======Location differ joblog from 2024-07-08 22:30:02=======
2024-07-08 22:50:35 INFO 61/193: Found machine to be added: Point Betsie Lighthouse
2024-07-08 22:52:06 INFO Location Michigan (13/125): Changes in 1/193 machines found.
2024-07-08 23:23:45 INFO Roswell Visitor Center is available again
2024-07-08 23:24:01 INFO Location New Mexico (40/125): Changes in 1/92 machines found.
2024-07-09 00:07:51 INFO 
 Result: 2 changes, 2 new machines found and 0 machines retired
2024-07-09 00:23:25 ERROR Found 3 problems that require manual intervention
2024-07-09 00:23:25 INFO ======Location differ completed at 2024-07-09 00:23:25=======
2024-07-09 00:23:26 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7273 named Jaca cathedral submitted.

**Comment by jannisborn** [comment]
2024-07-09 22:30:02 INFO ======Location differ joblog from 2024-07-09 22:30:02=======
2024-07-09 22:50:25 INFO Pea Soup Andersen's Restaurant  is available again
2024-07-09 22:51:14 INFO Location California (12/125): Changes in 1/757 machines found.
2024-07-09 23:35:17 INFO 5/57: Found machine to be added: Ernstbrunn Wildlife Park
2024-07-09 23:36:05 INFO Location Austria (54/125): Changes in 1/57 machines found.
2024-07-09 23:38:10 INFO 136/148: Found machine to be added: Cavendish Beach Adventure Zone
2024-07-09 23:38:13 INFO Location Canada (61/125): Changes in 1/148 machines found.
2024-07-09 23:46:20 INFO LVR-Museum Bonn is currently unavailable
2024-07-09 23:50:47 INFO Location Germany (73/125): Changes in 1/379 machines found.
2024-07-10 00:09:51 INFO 
 Result: 4 changes, 3 new machines found and 1 machines retired
2024-07-10 00:25:31 ERROR Found 3 problems that require manual intervention
2024-07-10 00:25:31 INFO ======Location differ completed at 2024-07-10 00:25:31=======
2024-07-10 00:25:32 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7276 named Shipwreck submitted.

**Comment by jannisborn** [comment]
2024-07-10 22:30:02 INFO ======Location differ joblog from 2024-07-10 22:30:02=======
2024-07-10 23:47:07 INFO 114/384: Found machine to be added: Landschaftspark Nord
2024-07-10 23:47:10 INFO 116/384: Found machine to be added: Pippolino
2024-07-10 23:47:12 INFO 117/384: Found machine to be added: Sportpark
2024-07-10 23:47:14 INFO 118/384: Found machine to be added: Zebrashop at SchauInsLand Reisen Arena
2024-07-10 23:47:17 INFO 120/384: Found machine to be added: Zoo Zajac
2024-07-10 23:51:21 INFO Location Germany (73/125): Changes in 5/384 machines found.
2024-07-10 23:54:05 INFO 53/141: Found machine to be added: Milano Souvenir
2024-07-10 23:55:05 INFO Location Italy (82/125): Changes in 1/141 machines found.
2024-07-10 23:57:40 INFO 174/217: Found machine to be added: Tokyo Bay Night Cruise aboard Sarubia-maru
2024-07-10 23:58:09 INFO Location Japan (84/125): Changes in 1/217 machines found.
2024-07-11 00:11:03 INFO 
 Result: 7 changes, 7 new machines found and 0 machines retired
2024-07-11 00:27:07 ERROR Found 3 problems that require manual intervention
2024-07-11 00:27:07 INFO ======Location differ completed at 2024-07-11 00:27:07=======
2024-07-11 00:27:08 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7284 named Blue Earth Welcome Center/ Green Giant Museum submitted.

**Comment by jannisborn** [comment]
2024-07-11 22:30:02 INFO ======Location differ joblog from 2024-07-11 22:30:02=======
2024-07-11 22:45:09 INFO One Log House is currently unavailable
2024-07-11 22:46:47 INFO 359/758: Found machine to be added: Pacific Beach 
2024-07-11 22:49:51 INFO Location California (12/125): Changes in 2/758 machines found.
2024-07-11 23:10:15 INFO Seeems that machine Kilgore East Texas Oil Museum already exists as: Kilgore College East Texas Oil Museum
2024-07-12 00:10:43 INFO 
 Result: 2 changes, 1 new machines found and 1 machines retired
2024-07-12 00:26:47 ERROR Found 3 problems that require manual intervention
2024-07-12 00:26:47 INFO ======Location differ completed at 2024-07-12 00:26:47=======
2024-07-12 00:26:48 INFO Detected change in server_locations.json - push to github

**Comment by jannisborn** [comment]
2024-07-12 22:30:02 INFO ======Location differ joblog from 2024-07-12 22:30:02=======
2024-07-12 22:40:11 INFO Washington Park - Oregon Zoo (Formerly Washington Park Zoo) is available again
2024-07-12 22:40:32 INFO Location Oregon (8/125): Changes in 1/132 machines found.
2024-07-12 23:37:12 INFO 32/58: Found machine to be added: Untersbergbahn Bergstation
2024-07-12 23:37:36 INFO Location Austria (54/125): Changes in 1/58 machines found.
2024-07-12 23:45:31 INFO "Compagnie Océane" Ferry Building Quiberon is currently unavailable
2024-07-12 23:46:54 INFO Location France (72/125): Changes in 1/106 machines found.
2024-07-12 23:48:42 INFO 128/390: Found machine to be added: Haus Ennepetal - Kluterthöhle
2024-07-12 23:49:25 INFO 176/390: Found machine to be added: Fahrräder Hecken
2024-07-12 23:49:27 INFO 177/390: Found machine to be added: Henrichshütte
2024-07-12 23:51:16 INFO 301/390: Found machine to be added: Regensburger Wundertüte
2024-07-12 23:52:06 INFO 356/390: Found machine to be added: Mariendom 
2024-07-12 23:52:28 INFO 382/390: Found machine to be added: Stadion am Zoo
2024-07-12 23:52:34 INFO Location Germany (73/125): Changes in 6/390 machines found.
2024-07-13 00:11:33 INFO 
 Result: 9 changes, 8 new machines found and 1 machines retired
2024-07-13 00:27:18 ERROR Found 3 problems that require manual intervention
2024-07-13 00:27:18 INFO ======Location differ completed at 2024-07-13 00:27:18=======
2024-07-13 00:27:19 INFO Detected change in server_locations.json - push to github

**Comment by NinaWie** [comment]
New machine 7293 named Pleasurewood Hills submitted.

**Comment by NinaWie** [comment]
New machine 7294 named Sound Of Music Church submitted.

**Comment by jannisborn** [comment]
No website updates today!

**Comment by NinaWie** [comment]
New machine 7295 named Evergreen Aviation & Space Museum submitted.

**Comment by NinaWie** [comment]
New machine 7296 named Buc-ee’s submitted.

**Review by jannisborn — APPROVED** [review]

**Comment by jannisborn** [comment]
No website updates today!

**Pull request merged**
